IBM/ibm-common-service-operator

pkg/bootstrap/constant.go

Update following operator to dev channel
```
ibm-helm-api-operator-app
ibm-mongodb-operator-app
ibm-catalog-ui-operator-app
ibm-helm-repo-operator-app
ibm-platform-api-operator-app
```

Update operator channel to dev

---

pkg/bootstrap/constant.go

OperandRrgistry: Set operator scope to public
OperandConfig: add operandRequest and operandBindInfo

Update OperandRrgistry and OperandConfig

---

build/resources/extra/example-sa.yaml
pkg/bootstrap/init.go

you can now put extra yaml files under `build/resources/extra` directory, the operator will create them one by one.

create extra yaml resources

---

build/resources/extra/webhook_deploy.yaml

This PR is used to onboard https://github.com/IBM/ibm-common-service-webhook to the ibm common service operator.

onboard ibm cs webhook

---

build/resources/cs-operandconfig.yaml

new CR for metering report server

add metering report server cr to operand config

---

docs/cloudpak-integration.md
docs/uninstall.md

Add uninstall docs

---

build/resources/extra/secretshare_deploy.yaml
build/resources/extra/webhook_deploy.yaml
deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
deploy/operator.yaml

Revert "update image tag to digest (#61)"

---

build/Dockerfile

TO fix redhat image certify 
https://connect.redhat.com/project/4290411/certification/sha256%3A2397c2249bca77c779bf2338e2a098d56074a58eaf2bdfa2c6c631acc7841993

Add lablel for dockerfile

---

docs/design.md
docs/install-cli.md
docs/uninstall.md

This is a requirement from CP4APP to install ibm common service operator from the command line

Add document for installing with cli

---

build/Dockerfile

Fix image scan issue
https://connect.redhat.com/project/4290411/certification/sha256%3A4bd2f8b4513d86299f2bf0d66c21cf4da4a280714fa123e8be6f1f389abd5012

Add license file in docker image to fix image certify issue

---

pkg/bootstrap/init.go

remove odlm csv v1.2.0

---

Makefile

fixes https://github.com/IBM/ibm-common-service-operator/issues/88
/cc @DanielXLee @horis233

inject vcs info to docker image

---

docs/install.md

fixes https://github.com/IBM/ibm-common-service-operator/issues/110

update install doc to use CatalogSource

---

cs3.4-restore.yaml

Apply the latest CatalogSource image

Update catalogsource image

---

cmd/manager/main.go
go.mod
pkg/check/check_iam.go

Enhance iam status check

---

Makefile
deploy/olm-catalog/ibm-common-service-operator/3.4.4/ibm-common-service-operator.v3.4.4.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.4.5/ibm-common-service-operator.v3.4.5.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.4.5/operator.ibm.com_commonservices_crd.yaml
deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
version/version.go

push 3.4.5 to dev, 3.4.4 to beta and 3.4.3 to stable-v1

promote CSV 3.4.3 to the stable-v1 channel

---

common/config/.golangci.yml
controllers/commonservice_controller.go
controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go

I set the priority of deep merge.
common service CR > sizing configurations > OperandConfig

adjust sizing by common service CR

---

deploy/olm-catalog/ibm-common-service-operator/3.4.4/ibm-common-service-operator.v3.4.4.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.4.5/ibm-common-service-operator.v3.4.5.clusterserviceversion.yaml

using image version 3.4 for cs 3.4

---

deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.0/operator.ibm.com_commonservices_crd.yaml
deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml

Add 3.5.0 CSV into operator package

add 3.5.0 into package

---

Makefile
common/scripts/config_docker.sh
version/version.go

This PR is to integrate ibm common service operator with the IBM artifactory CICD pipeline.

integrate with IBM artifactory

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
deploy/operator.yaml

Remove ProductVersion for common-service operator, webhook operator and secretshare operator.
FYI @chenzhiwei @horis233

Remove productVersion metering annotations

---

deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml

Add subscription rbac for the secretshare operator.

add subscription rbac for secretshare

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml

using the original deployment name for the ibm common service operator

using the original deployment name

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.clusterserviceversion.yaml

add rbac for the secretshare operator

---

controllers/size/medium_amd64.go
controllers/size/small_amd64.go

The code for metering sender isn’t shipping.
**FYI** @chenzhiwei @horis233

remove stanza for metering

---

controllers/size/small_amd64.go

update memory for the commonui

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml

Update secretshare image digest

---

Dockerfile

upgrade golang version to avoid vulnerability issue

---

controllers/size/medium_amd64.go
controllers/size/small_amd64.go

Update sizing for iam

---

controllers/size/medium_amd64.go
controllers/size/small_amd64.go

update cpu sizings for nginx-ingress
/assign @Daniel-Fan

update cpu sizings for nginx-ingress

---

Dockerfile

Could you please review it? Thank you!
/assign @horis233

add license

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml

Update digest for secretshare and cs webhook
- secretshare change: add license into image
- cs webhook: fix log message

Update digest for secretshare and cs webhook

---

controllers/size/medium_amd64.go
controllers/size/small_amd64.go

update sizing for the common ui

---

api/v3/commonservice_types.go
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml

Add the displayname in the CSV.
Otherwise, there is no CRD showing on the operator page.

Add displayname

---

controllers/size/medium_amd64.go
controllers/size/small_amd64.go

removing size for logging

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml

Update secretshare container name

---

controllers/size/medium_amd64.go
controllers/size/small_amd64.go

update in sizing repo
https://github.ibm.com/IBMPrivateCloud/bedrock-size-yaml/pull/14
\assign @horis233

increase limits based on experiment

---

controllers/size/medium_amd64.go
controllers/size/small_amd64.go

update size file for monitor and mongodb

sync size values(monitor/mongodb)

---

controllers/size/medium_amd64.go

Those changes solve the current blocker issues.
/assign @horis233

update size for medium(mcmMonitor/configmap watcher)

---

controllers/constant/constant.go

This PR changes the default profile from Small to Medium.

Use medium as the default sizing profile

---

controllers/size/medium_amd64.go

update medium sizing profile

---

controllers/size/medium_amd64.go
controllers/size/small_amd64.go

Update pdp cpu limits small and medium

Update pdp cpu limits small and medium

---

controllers/size/large_amd64.go

@horis233 Could you please review the initialization of large size profile?

init large size profile and sync the latest sizing data

---

controllers/size/large_amd64.go
controllers/size/medium_amd64.go
controllers/size/small_amd64.go

@horis233 Could you please take a look? Thank you!

update memory limit from latest x86 measurement

---

controllers/size/large_s390x.go
controllers/size/medium_s390x.go
controllers/size/small_s390x.go

init size for Z platform from x86 and update them based on actually usage.

init and update size for Z

---

docs/install-cli.md
docs/install.md

Update install document to install the beta release

Update install document

---

controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go

Update resource size and Enable HA of management ingress and nginx ingress

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
bundle/manifests/operator.ibm.com_commonservices.yaml
config/crd/kustomization.yaml
config/crd/patches/label_in_commonservices.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.0/operator.ibm.com_commonservices_crd.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.1/ibm-common-service-operator.v3.5.1.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.1/operator.ibm.com_commonservices_crd.yaml

This PR is to add labels to pass the ibm certification

Add labels for ibm certification

---

controllers/size/medium_amd64.go
deploy/olm-catalog/ibm-common-service-operator/3.5.1/ibm-common-service-operator.v3.5.1.clusterserviceversion.yaml

Hold, waiting for the secretshare image

Update webhook image and update size

---

controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/small_amd64.go

For management ingress operator

requests are less than limits of size in P and Z

---

controllers/size/small_ppc64le.go

fix request is over limit for nginxIngress in small profile on P

fix request is over limit for nginxIngress

---

controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go

update commonui replicas

---

Makefile
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
deploy/olm-catalog/ibm-common-service-operator/3.5.2/ibm-common-service-operator.v3.5.2.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.3/ibm-common-service-operator.v3.5.3.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.3/operator.ibm.com_commonservices_crd.yaml
deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
version/version.go

Bump beta version to 3.5.3 and push 3.5.2 to the stable-v1 channel

Bump 3.5.2 to stable-v1 channel

---

controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go

missed large & small profile updates for IAM

---

controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go

update oidcclientwatcher memory limits

---

controllers/check/check_iam.go

Remove configmap-watcher from the IAM deployment list, confirm with IAM team it is a component from the CERT team instead of IAM.

remove configmap-watcher

---

deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml

add eventstream into operatoregistry

---

deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml

update odlm package name

---

deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml

1. push 3.5.5 to the stable-v1 channel
2. revert the ODLM package name, will add it back in the next version

push 3.5.5 to stable channel

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
controllers/bootstrap/init.go
controllers/commonservice_controller_test.go
controllers/constant/constant.go
controllers/constant/yaml.go
deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
main.go

* Use constant variables to replace the hard coded strings
* Move the cold YAMLs from CSV to go code
* Reduce the cluster permissions

refactor the code logic

---

controllers/bootstrap/init.go
controllers/check/check_iam.go
controllers/commonservice_controller.go
controllers/commonservice_controller_test.go
controllers/deploy/manager.go
main.go

Update error log format to avoid logs with wrong logs

update error logs

---

controllers/check/check_iam.go

remove iam-policy-controller from IAM check

remove policy controller

---

config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

forget to update version in config manifest.

bump to 3.6.3 and update version

---

controllers/bootstrap/init.go
main.go

Workaround for the upgrade from 3.4.3

workaround for upgrade from 3.4.3

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manager/manager.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.4.2/ibm-common-service-operator.v3.4.2.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.4.3/ibm-common-service-operator.v3.4.3.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.4.4/ibm-common-service-operator.v3.4.4.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.4.5/ibm-common-service-operator.v3.4.5.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.1/ibm-common-service-operator.v3.5.1.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.2/ibm-common-service-operator.v3.5.2.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.3/ibm-common-service-operator.v3.5.3.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.4/ibm-common-service-operator.v3.5.4.clusterserviceversion.yaml
deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml
deploy/operator.yaml
testdata/deploy/deploy.yaml

Update labels
```
beta.kubernetes.io/arch -> kubernetes.io/arch
beta.kubernetes.io/os -> kubernetes.io/os
```

Use lable kubernetes.io

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

We have a configmap to share when Zen is installed

Adding operandBindInfo

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
controllers/bootstrap/init.go
controllers/check/check_iam.go
controllers/common/util.go
controllers/commonservice_controller.go
controllers/constant/constant.go
controllers/operandconfig.go
go.sum
main.go

Need to optimize the method usage and code structure

get masterNs to replace hardcoded ns

---

controllers/constant/constant.go
controllers/constant/secretshare.go
controllers/constant/webhook.go

to handle the multiple Common Services
fix issue #342

add ns suffix for clusterrole binding

---

Makefile
controllers/common/util.go
controllers/commonservice_controller.go
go.sum

fix #343
Remove the finalizer logic to make CRs being deleted easily.

remove finalizer

---

controllers/common/util.go

/assign @Daniel-Fan 
Solve the defect when the configmap doesn't exist.

cover the case configmap doesn't exist

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

It seems that we need to update `alm-example` section in redis operator CSV.
@horis233 Please correct me if the content in OperandConfig and OperandRegistry is wrong.

onboard redis operator

---

controllers/bootstrap/init.go

This PR is to handle the upgrade paths from 3.4, 3.5 and 3.6

Update the pathes for the upgrade

---

testdata/README.md
testdata/deploy/deploy.yaml
testdata/sizing/large_mongodb.yaml
testdata/sizing/large_size.yaml
testdata/sizing/operandrequest.yaml
testdata/sizing/small_size.yaml
testdata/sizing/storage_class.yaml

@bitscuit You can follow the `## 4.Test sizing update` section to test the sizing change.

Add tests for sizing

---

controllers/rules/resource_comparison.go

Convert digitals to string, then compare their size

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
testdata/deploy/deploy.yaml

https://github.com/IBM/ibm-common-service-webhook/pull/35
https://github.com/IBM/ibm-secretshare-operator/pull/36

Update image digest for secretshare and cs webhook

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
controllers/common/util.go
testdata/deploy/deploy.yaml

- Update the cs mapping configmap structure 
```
common-service-maps.yaml:
- requested-from-namespaces:
- cp4iforFord
map-to-common-service-namespace: common-service-ford
map-default: ibm-common-servies
```
- Update image digest for cs webhook

update cs mapping configmap structure

---

Makefile
testdata/actual.yaml
testdata/expected.yaml
testdata/sizing/medium_size.yaml
testdata/test_profile.sh

added test to change custom profiles

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
docs/install-cli.md
docs/install.md
testdata/deploy/deploy.yaml

- remove metering
- update zen operator catalog

update catalog for zen operator 

---

controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go

Do we need to update the size for EUS version as well?

update size for MongoDB

---

controllers/commonservice_controller.go
controllers/operandconfig.go
controllers/rules/resource_comparison.go
go.mod
go.sum
main.go

Working in testing
Is there any advice on the logic, the current method looks complicated and unclear

add event to remind no update although CR changed

---

controllers/constant/namespace.go
controllers/constant/webhook.go
controllers/operandconfig.go
go.mod

We can remove it after we can input the namespace from OperandRegistry into the nss CR.

feat(tmp): Add openshift-redhat-marketplace in nss CR.

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
docs/cloudpak-integration.md
testdata/deploy/deploy.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/43732

remove deprecated clusterissuer cs-ca-clusterissuer

---

common/scripts/upgrade_to_continuous_delivery.sh

Remove step of updating catalogsource
to upgrade the operator in specific namespace. please add namespaces as the command line arguments.
```
./upgrade_to_continuous_delivery.sh common-service-2 common-service-3
```

support multiple ns for upgrading to 3.7

---

common/scripts/upgrade_to_continuous_delivery.sh

minor updates to the user facing messages

updated channel switch messages

---

common/scripts/upgrade_to_continuous_delivery.sh

Currently, check all csv of operators to be in 3.6 version and `succeeded` status, then switch the channel.
Did not add the step for checking the version of OperandConfig, will discuss whether it is necessary in sync up.

hold to switch channel until upgrading to eus

---

common/scripts/upgrade_to_continuous_delivery.sh
common/scripts/upgrade_to_continuous_delivery_airgap.sh

For the airgap, we would switch channel first and then update catalogsource

add upgrade script for airgap

---

common/scripts/upgrade_to_continuous_delivery.sh

The previous associative array are not supported in bash version 3 which is mac default version

update script to be compatible with bash 3

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

Change `IBM Cloud Platform Common Services` to `IBM Cloud Pak foundational services`

rename operator name in the CSV

---

Dockerfile

updated golang to 1.15.10 and ubi8 to 8.3-291 to remediate

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
common/config/.golangci.yml
controllers/bootstrap/init.go
controllers/common/util.go
controllers/constant/webhook.go
controllers/render_template.go
main.go

1. check `saas-config` and `common-service-maps` to check the SaaS deployment and obtain the corresponding configurations.
2. generate control namespace if it is SaaS deployment.
3. Deploy `secretshare` and `webhook` into control namespace

SaaS deployment at resource initialization stage

---

controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go

remove data collector container

Common Ui size update 390 small

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
controllers/bootstrap/init.go
controllers/certmanager/cert_cr.go
controllers/constant/constant.go
controllers/constant/secretshare.go
controllers/constant/webhook.go

use semver as annotation version

---

bundle/manifests/operator.ibm.com_commonservices.yaml
controllers/bootstrap/init.go
controllers/common/util.go

1. convert string to int before compare 2. tolerant unknown field

fix: update crd

---

api/v3/commonservice_types.go
bundle/manifests/operator.ibm.com_commonservices.yaml
common/config/.golangci.yml
config/crd/bases/operator.ibm.com_commonservices.yaml
controllers/bootstrap/init.go
controllers/commonservice_controller.go
go.mod
go.sum
main.go

Ref https://github.com/IBM/operand-deployment-lifecycle-manager/issues/627

set manual approval for CS operators

---

Makefile
README.md
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
version/version.go

bump version to 3.6.5

---

controllers/check/check_iam.go

@pnpavan25 @yannizhang2019 Please review this PR

set two iam deployment list for SaaS deployment and on-prem software

---

controllers/constant/odlm.go

update the channel of the db2u operator from `v1.0` to `v1.1`

update the channel of the db2u operator

---

controllers/multipleInstancesEnabled/multipleInstancesEnabled.go
controllers/render_template.go

Tested in single-instance env & multi-instance env, both worked as expected.

enable `multipleInstancesEnabled` in the management-ingress & ingress-nginx CR

---

.github/dependabot.yml
controllers/certmanager/certmanager.go

In order to trigger a rebuild to fetch the latest base image

update comments and add Dependabot to update base image

---

controllers/bootstrap/init.go
controllers/common/util.go

verified with:
1. cluster with sc
2. cluster without sc

pre-check storage class, if nothing exists, give warning messages

---

common/scripts/force-uninstall.sh
controllers/check/check_iam.go

No IAM subscriptions:
* cs-mapping is not found(pure single mode)
     * clean up cs.data
* cs-mapping is found(both single or multi)
     * remove namespace of the scope(get cs-mapping) from iam-status
Exist IAM subscription:
1. Create ConfigMap if not found
2. Update ConfigMap
* cs-mapping is not found(pure single mode)
         * overwrite the cs.data with current nss ConfigMap
* cs-mapping found
         * Update Ns in Status with ns in cs mapping

iam-status enhancement

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/constant/webhook.go
testdata/deploy/role.yaml
testdata/deploy/role.yaml.bak

https://github.com/IBM/ibm-common-service-webhook/pull/48

add perrmission for validating webhook

---

controllers/bootstrap/init.go
controllers/commonservice_controller.go

Here is my design idea, feel free to give any suggestions.

allow all cs cr in any namespaces can enable crossplane operator

---

common/scripts/upgrade_to_continuous_delivery.sh
common/scripts/upgrade_to_continuous_delivery_airgap.sh

Let merge it after the SERT tests it completely.

check whether the channel switch is completed

---

controllers/bootstrap/init.go

remove checking installedcsv with currentcsv (#559)

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml

Add custer role for crossplane CR

---

common/scripts/patch_image.sh

example
```
./patch_image.sh -cs quay.io/opencloudio/common-service-operator@sha256:352d8d958cffdd11437fbab4953b310c37e295a40727e26b5bdf92e215c2e5a7 -odlm quay.io/opencloudio/odlm@sha256:2eabda311c2c25128996d9a1dbdde3fea4f644c0b327a29fc24ab2a7e142332b
```
I will create an additional branch for scripts only later

patch cs and odlm image

---

bundle.Dockerfile
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
config/samples/operator_v3_commonservice.yaml
controllers/constant/constant.go
controllers/render_template.go
controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go
controllers/size/starterset_amd64.go
controllers/size/starterset_ppc64le.go
controllers/size/starterset_s390x.go
docs/install-cli.md
docs/install.md

use starterset as the default profile to reduce MongoDB replica to 1

---

controllers/constant/odlm.go

onboard postgresql

---

controllers/bootstrap/init.go
controllers/common/util.go
controllers/constant/constant.go

Set OCP default catalogsource have lower priority than other catalogsource

set priority for catalogsource

---

controllers/constant/crossplane.go

Update apiVersions in crossplane.go to current names

Update apiVersions in crossplane.go

---

Dockerfile
Makefile
common/scripts/artifactory_config_docker.sh

* opt-in of ubi base image automated builds
* configure Docker Credential

opt-in of ubi base image automated builds (#591)

---

controllers/constant/odlm.go

adding this fix to avoid conflict with RedHat catalog packageName.

UDS : fixing the operator name and packageName

---

controllers/constant/odlm.go

onboarding UDS to Common services operator

onboarding UDS to Common services operator

---

controllers/constant/odlm.go
controllers/rules/resource_comparison.go
controllers/rules/rules.go
controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go
controllers/size/starterset_amd64.go
controllers/size/starterset_ppc64le.go
controllers/size/starterset_s390x.go

Let's merge it into future branch for more test

api-onboarding and slice comparison

---

controllers/constant/crossplane.go

change mechanism of reading cross-plane configuration

crossplane configuration from env var

---

controllers/constant/odlm.go

secret -> secrets
added get & list to verbs

typo in EDB Job role resource name and add verbs

---

controllers/constant/odlm.go

set the job `restartPolicy` as `OnFailure`, so if the job will retry when failed

set restartPolicy as OnFailure

---

controllers/bootstrap/init.go
controllers/common/util.go

Let review the logic first, will need test on Fyre before merge

update compare resource string version logic

---

controllers/common/util.go
controllers/constant/constant.go

Compare catalogsource annotation to decide the priority

compare catalogsource priority

---

controllers/bootstrap/init.go
controllers/commonservice_controller.go
controllers/constant/crossplane.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50545

add Crossplane Providers

---

controllers/constant/crossplane.go

Update due to new operator names.

update crossplane providers' subscriptions

---

common/scripts/rollback_to_eus.sh
common/scripts/upgrade_to_continuous_delivery_airgap.sh

The current rollback procedure cannot fully pass the SERT regression test.
I have not got the chances to run the second round of test due to the maintenance of Fyre. But we could review the PR first.

add rollback script from CD to EUS

---

controllers/constant/crossplane.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51822

fix apar from GM

---

installplan_approval.sh
operator_checker_patch.sh

```
./installplan_approval.sh ibm-common-services
./operator_checker_patch.sh --csns ibm-common-services --odlmns ibm-common-services
```

add script for upgrade of manual approval mode

---

OWNERS
README.md
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
controllers/constant/secretshare.go
controllers/constant/webhook.go
testdata/deploy/deploy.yaml
version/version.go

bump version to 3.19.0

---

controllers/constant/odlm.go

Signed-off-by: Henry Li <henry.h.li@ibm.com>

updated db2u channel from v1.1 to v2.0

---

controllers/commonservice_controller.go

delete crossplane from control namespace

---

controllers/bootstrap/init.go
main.go

create control namespace in bootstrap

---

controllers/bootstrap/init.go

Open to suggestions on handling the namespace is nil error

make createOrUpdateFromYaml generic to include control ns

---

README.md
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
controllers/constant/secretshare.go
controllers/constant/webhook.go
testdata/deploy/deploy.yaml
version/version.go

bump ltsr version to 3.19.3

---

upgrade_common_services_future.sh

update script to switch channel for cs only

---

README.md
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
controllers/constant/secretshare.go
controllers/constant/webhook.go
testdata/deploy/deploy.yaml
version/version.go

bump version to 3.21

---

controllers/constant/odlm.go

Signed-off-by: aniruddhj <ajhavar@gmail.com>
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53446

adding licensing annotations for pre-zen-config

---

controllers/constant/odlm.go

add product annotation for  postgresql job

---

controllers/bootstrap/init.go
main.go

fix for this issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54365

Subscription check enhancement

---

upgrade_common_services.sh

compare channel version before switch channel

---

controllers/constant/odlm.go

Fix bad indentation for SaaS OperandConfig

---

upgrade_common_services.sh
upgrade_common_services_airgap.sh

channel version check in airgap upgrade script

---

controllers/constant/odlm.go

exclude community catalogSource

---

controllers/bootstrap/init.go
controllers/common/util.go

remove catalogsource switch logic

---

upgrade_common_services.sh
upgrade_common_services_airgap.sh

Trim all characters 'v' and above in versions

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml

update secretshare and webhook

---

convert_to_multi_instance.sh

changed to only create operatorgroup is none exist
Signed-off-by: Henry Li <henry.h.li@ibm.com>

re-install all singleton services into control ns

---

common/scripts/next-csv.sh

Enhance version bump script for cs operator

---

controllers/bootstrap/init.go

if there is a newer version in control NS, CS-operator should skip installing the older version to control NS

keep the newest verison of NSS in controlNS

---

controllers/constant/odlm.go

switch channel of zen cpp operator version back to current one

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/bootstrap/init.go
controllers/common/util.go

crossplane cr clean for LTSR

---

controllers/constant/odlm.go

bump db2u channel to v2.2

---

controllers/operandconfig.go
controllers/rules/resource_comparison.go
controllers/rules/rules.go

fix the bug to enable fips in common-service CR for individual services.

fix fipsEnabled issue in LTSR

---

upgrade_common_services.sh

fix for odlm scale down

---

controllers/bootstrap/init.go
controllers/constant/crossplane.go
controllers/constant/ibmcloud.go
controllers/constant/namespace.go
controllers/constant/odlm.go

make approval mode dynamic instead of hardcoded

---

controllers/constant/secretshare.go
controllers/constant/webhook.go

Signed-off-by: Henry Li <henry.h.li@ibm.com>

added runAsNonRoot to secretshare and webhook

---

upgrade_common_services.sh

detect zen current version

---

controllers/constant/odlm.go

Signed-off-by: Henry Li <henry.h.li@ibm.com>

pin Bedrock services to v3.22 channel except for installer

---

controllers/constant/odlm.go

updated digest value for license provider image

---

api/v3/commonservice_types.go
bundle/manifests/operator.ibm.com_commonservices.yaml
config/crd/bases/operator.ibm.com_commonservices.yaml
controllers/bootstrap/init.go
controllers/constant/crossplane.go

for the issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55208
add a new parameter `crossplaneProviderRemoval` in CommonService CR aligned with `.features.bedrockshim.enabled` 
it is an indicator to perform gracefully uninstallation for provider operator

remove crossplane provider operator

---

controllers/bootstrap/init.go
controllers/constant/certmanager.go
controllers/goroutines/cleanup_deprecated_services.go

migrate from v1alpha1 Certs to v1 Certs

---

controllers/goroutines/namespacescope.go

goroutine enhancement

---

convert_to_multi_instance.sh

Standardize the output across functions and added a version to the beginning of the script. Open to feedback on how output has been changed, I was mostly focused on standardization and readability.

update output messages, add version

---

velero/backup/mongoDB/mongo-backup.sh
velero/backup/mongoDB/mongodbbackup.yaml
velero/restore/mongoDB/mongo-restore.sh
velero/restore/mongoDB/mongodbrestore.yaml
velero/restore/mongoDB/set_access.js

Signed-off-by: Kevin Carr <kgcarr@us.ibm.com>

add mongodb files

---

backup_restore_mongo.sh
convert_to_multi_instance.sh
velero/backup/mongoDB/mongo-backup.sh

Automate the Mongodb Backup and Restore Steps

---

Makefile

remove quay image build support

---

controllers/bootstrap/init.go
controllers/commonservice_controller.go

add Crossplane functionality back

---

controllers/goroutines/namespacescope.go
main.go

add NSS ConfigMap synchronization

---

controllers/bootstrap/init.go
controllers/constant/certmanager.go

deploy certificates without IBM dependencies

---

controllers/constant/odlm.go

install IAM from channel v4.0

---

controllers/bootstrap/init.go

drop compatibility for upgrading from cs 3.4

---

controllers/constant/odlm.go

pick 3.23 channel for existing services

---

controllers/constant/crossplane.go

revert crossplane channel to unblock canary

---

upgrade_common_services_airgap.sh

update comments and fix typo in script

---

upgrade_common_services.sh

skip zen status check if it is not installed

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

ibm-bts-operator is onboard the CSVInjector

---

controllers/constant/odlm.go

patch registryNamespace for licensing BindInfo

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/bootstrap/init.go
controllers/common/util.go
controllers/operandconfig.go

remove cluster permission on CommonService CR

---

controllers/bootstrap/init.go

remove operator waiting to unblock cert creation

---

controllers/bootstrap/init.go
controllers/constant/certmanager.go

wait for cert-manager v1 crd to be ready

---

controllers/bootstrap/init.go

Tolerate customized subscription config

---

controllers/bootstrap/init.go
controllers/constant/certmanager.go

check v1alpha1 crd

---

controllers/bootstrap/init.go

integrate crd checking into cleanup function in CD

---

controllers/constant/certmanager.go
controllers/constant/commonservice.go
controllers/constant/constant.go
controllers/constant/crossplane.go
controllers/constant/ibmcloud.go
controllers/constant/namespace.go
controllers/constant/odlm.go
controllers/constant/secretshare.go
controllers/constant/webhook.go
docs/cloudpak-integration.md

support numeric ns installation

---

controllers/constant/odlm.go

update zen channel to v4.0

---

controllers/constant/odlm.go
controllers/goroutines/variables.go
controllers/rules/rules.go
controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go
controllers/size/starterset_amd64.go
controllers/size/starterset_ppc64le.go
controllers/size/starterset_s390x.go
docs/cloudpak-integration.md
testdata/actual.yaml
testdata/expected.yaml

remove PAP, PDP, oidc client watcher and iam onboarding job

---

controllers/constant/odlm.go
controllers/goroutines/variables.go
controllers/rules/rules.go
controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go
controllers/size/starterset_amd64.go
controllers/size/starterset_ppc64le.go
controllers/size/starterset_s390x.go
docs/cloudpak-integration.md
testdata/actual.yaml
testdata/expected.yaml

remove secret watcher, and policy controller

---

controllers/constant/odlm.go

update cert manager and mongodb channel

---

controllers/constant/odlm.go

revert mongodb channel back to v3.23

---

.github/workflows/ocp.yaml
Dockerfile
Makefile
common/scripts/artifactory_config_docker.sh
testing.md

new artifactory image endpoint (cs operator)

---

.github/workflows/ocp.yaml
Dockerfile
Makefile
common/scripts/artifactory_config_docker.sh
testing.md

[ltsr] new artifactory image endpoint (cs operator)

---

controllers/constant/certmanager.go
controllers/constant/commonservice.go
controllers/constant/constant.go
controllers/constant/crossplane.go
controllers/constant/ibmcloud.go
controllers/constant/namespace.go
controllers/constant/odlm.go
controllers/constant/secretshare.go
controllers/constant/webhook.go
docs/cloudpak-integration.md

[ltsr] support numeric ns installation

---

controllers/constant/odlm.go
controllers/goroutines/check_iam.go
controllers/goroutines/variables.go
controllers/rules/rules.go
controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go
controllers/size/starterset_amd64.go
controllers/size/starterset_ppc64le.go
controllers/size/starterset_s390x.go
docs/cloudpak-integration.md
testdata/actual.yaml
testdata/expected.yaml

remove iam jobs

---

controllers/goroutines/check_iam.go

IM subscription check

---

.github/workflows/ocp.yaml
Dockerfile
Makefile
common/scripts/artifactory_config_docker.sh
testing.md

[future]  new artifactory image endpoint (cs operator)

---

README.md
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manager/manager.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
controllers/constant/secretshare.go
controllers/constant/webhook.go
testdata/deploy/deploy.yaml
version/version.go

bump version to 3.23.1

---

controllers/constant/odlm.go

bump licensing operator to v4.0 channel

---

controllers/constant/odlm.go

discontinue platform-api and cert-manager

---

controllers/constant/certmanager.go

add leaf-refresh opt-in label to cs-ca-certificate-secret

---

controllers/constant/odlm.go

pick up cert-manager from v3.23 via OperandRequest

---

controllers/goroutines/check_iam.go
controllers/goroutines/variables.go

add oidc-client-registration job check

---

controllers/constant/odlm.go

bump management ingress operator to v4.0 channel

---

controllers/constant/odlm.go

remove zen APIKey from OperandConfig

---

controllers/constant/commonservice.go
controllers/constant/constant.go
controllers/constant/crossplane.go
controllers/constant/ibmcloud.go
controllers/constant/namespace.go
controllers/constant/odlm.go

removed unnecessary stringify

---

controllers/constant/odlm.go

discontinue management-ingress, audit logging and ingress-nginx

---

controllers/bootstrap/init.go
controllers/constant/namespace.go
main.go

remove nss synchronization with OperatorGroup

---

controllers/constant/odlm.go

mark tombstone for cert-manager

---

upgrade_common_services.sh

Signed-off-by: YuChen Shen
This PR can solve the issue that the adopters mentioned in
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56311#issuecomment-52054382
that some values can not be returned in a correct way in adopters' clusters

use fullname with api name for oc get commands

---

upgrade_common_services_airgap.sh

Signed-off-by: YuChen Shen
related issue:
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56311#issuecomment-52054382

[airgap upgrade] use fullname for oc get commands

---

controllers/constant/odlm.go

bump MongoDB channel to v4.0

---

upgrade_common_services_ltsr.sh

[ltsr upgrade] enhance upgrade script with all channels switched

---

controllers/bootstrap/init.go
controllers/goroutines/cppConfig.go
main.go

create ibm-cpp-config configmap in servicesNamespace

---

controllers/constant/odlm.go

- Add new entry for `ibm-platformui-operator`
- Add new entry for `ibm-platformui-operator-v4.0`
- Update the corresponding OperandConfig templates

add new entry for ibm-platformui-operator

---

go.mod
go.sum

Merged in a pr that should make a difference in the pr tests https://github.com/IBM/test-infra/pull/524

update pkg for twistlock

---

networkpolicy/zen-access-to-nginx.yaml

fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56980

open nginx ingress to every ns

---

controllers/bootstrap/init.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57453
Reason: when there is only one namespace (`operatorNs`) in `WatchNamespaces`, skip copying `CommonService` CR into other namespaces.

Exclude cloned CommonService CR from being copied in AllNamespace Mode

---

controllers/webhooks/commonservice/validatingwebhook.go
controllers/webhooks/reconciler.go

for the ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56481
validating `serviceNamespace` and `operatorNamespace` in commonservice cr are in targetnamespace in operatorgroup.

add validating webhook for CommonService cr

---

controllers/constant/odlm.go

Update IM OperandRequest in OperandConfig:
- adding two operands: `ibm-mongodb-operator` and `ibm-commonui-operator`
- removing `ibm-cert-manager-operator`, `ibm-management-ingress-operator` and `ibm-ingress-nginx-operator`

update IM OperandRequest in OperandConfig template

---

cp3pt0-deployment/setup_singleton.sh

Execute the script with following command
```
> ./cp3pt0-deployment/setup_singleton.sh --enable-private-catalog --enable-licensing
```
Both cert-manager and Licensing service's subscriptions are created with namespace scoped CatalogSource
```
[INFO] Creating following Subscription:
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
name: ibm-cert-manager-operator
namespace: ibm-cert-manager
spec:
channel: v4.0
installPlanApproval: Automatic
name: ibm-cert-manager-operator
source: opencloud-operators
sourceNamespace: ibm-cert-manager
subscription.operators.coreos.com/ibm-cert-manager-operator created
[INFO] Creating following Subscription:
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
name: ibm-licensing-operator-app
namespace: ibm-licensing …
```

Introduce private catalog flag

---

networkpolicy/egress/zen-egress-zen-metastore-backup-cron-job.yaml

back-reference: https://github.ibm.com/IBMPrivateCloud/cs-dev-tools/pull/175

fix metadata.name for metastore-backup-cron-job

---

convert_to_multi_instance.sh

left two lines from testing in the last pr

cleanup previous commit

---

controllers/constant/odlm.go

fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57789

generate pre-zen job under operator namespace

---

cp3pt0-deployment/common/utils.sh

It will 
1. clean up webhook deployment and webhookconfiguration
2. clean up secretshare deployment and CR
3. clean up crossplane subscriptions and CRs in some specific order( otherwise it will be blocked by the finalizer)

cleanup cp2.0 webhook,secretshare and crossplane

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/setup_tenant.sh

for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57744

config_cscr in watch_namespaces

---

controllers/constant/odlm.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57774

rename commonui to ibm-idp-config-ui-operator in CP3.0

---

cp3pt0-deployment/setup_singleton.sh

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57845

add catalogsource label for cert mgr and licensing

---

controllers/constant/odlm.go

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57889

update IM OpConfig

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/setup_singleton.sh

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57622

provide custom namespace for cert manager and licensing operators

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manager/manager.yaml

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53999
and enhancement work for: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57592#issuecomment-55240538

change update strategy to recreate

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manager/manager.yaml

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53999
and enhancement work for: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57592#issuecomment-55240538

change update strategy to recreate in ltsr

---

controllers/commonservice_controller.go
main.go

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58081
if it is not ocp, we skip deploying webhook server and skip reconciling webhook

disable webhook in cncf

---

controllers/common/util.go

When CP2.0s `cloudpak-2pt0-1` and `cloudpak-2pt0-2` are deployed in isolated instance, and they are sharing the same CS instance `ibm-common-services`
```
data:
- map-to-common-service-namespace: ibm-common-services
requested-from-namespace:
- common-service
- cloudpak-2pt0-1
- cloudpak-2pt0-2
```
Upgrade of common service operator in Cloud Pak namespace `cloudpak-2pt0-1` will automatically bring up a new CP3.0 instance in own Cloud Pak namespace. And it leads to a updated ConfigMap
```
data:
- map-to-common-service-namespace: ibm-common-services
requested-from-namespace:
- common-service
- cloudpak-2pt0-2               <----- …
```

exclude its WATCH_NAMESPACE from existing common-service-maps entry, and create new entry

---

networkpolicy/bedrock-access-to-ibm-common-service-operator.yaml

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56443
add new net work policy 
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
name: access-to-ibm-common-service-operator
namespace: "csNamespace"
labels:
component: cpfs
spec:
podSelector:
matchLabels:
name: ibm-common-service-operator
ingress:
- {}
policyTypes:
- Ingress
```

add new networkpolicy

---

controllers/bootstrap/init.go
controllers/commonservice_controller.go

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57312
It will check if `cs-ca-certificate-secret` is already there during the installation. If we find this secret but do not find the certificate, we will skip deploying `cs-ca-cert`

BYOC support without label

---

backup_preload_mongo.sh

incorporating feedback made after last pr was merged https://github.com/IBM/ibm-common-service-operator/pull/1130
Change a success message to be more accurate, change statefulset images to find and use what the existing mongo is using
@pgodowski fyi

use existing mongo images

---

controllers/rules/rules.go
controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go
controllers/size/starterset_amd64.go
controllers/size/starterset_ppc64le.go
controllers/size/starterset_s390x.go
docs/cloudpak-integration.md
testdata/actual.yaml
testdata/expected.yaml

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58330

re-enable the size configuration for new CommonUI component

---

controllers/bootstrap/init.go
controllers/commonservice_controller.go
controllers/constant/certmanager.go
controllers/webhooks/operator_webhooks.go
controllers/webhooks/webhookreconciler.go
main.go

Webhook changes are blocking CICD pipeline

Revert change on CNCF support webhook

---

cp3pt0-deployment/common/utils.sh

fix for patch operation failed: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57978#issuecomment-56237562
`update_operator` function attempts to patch the subscription with the desired changes, and if it fails due to a conflict, it retries the patch operation with a delay of 5 seconds for 5 times. If the maximum number of retries is reached and the patch operation still fails, an error message is displayed

retry the subscription patch operation for 5 times

---

backup_preload_mongo.sh

Reverts IBM/ibm-common-service-operator#1151
This change caused preload to fail with an empty storageClassName in the cs-mongodumps PVC. It was supposed to be a fix for ROKS environments but it is affecting our other test environments. We will need to investigate this further before reimplmenting

Revert "cleanup based on feedback"

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/migrate_tenant.sh

fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57978#issuecomment-56454280
- Update the number of replicas specified in a deployment section of a CSV  before scaling deployment
- Re-organize scaling up time for ODLM and CS operator

update the replicas in a deployment section of CSV

---

cp3pt0-deployment/common/utils.sh

If there is no crossplane operator in the cluster, we skip remove its resources
Base on comment: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57978#issuecomment-56591736

crossplane subscription check

---

backup_preload_mongo.sh
cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/migrate_tenant.sh
cp3pt0-deployment/setup_singleton.sh
cp3pt0-deployment/setup_tenant.sh

Added function to accept and update the license for cert manager in the setup_singletons script. Especially interested in feedback on line 173.

accept the license for cert manager, cs op, nss, and licensing based on parameter

---

cp3pt0-deployment/common/utils.sh

pass namespace as a string
for comment: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57978#issuecomment-56636169

change namespace name

---

controllers/constant/odlm.go

for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/58486

update BTS OperandRequest with ibm-im-operator included

---

cp3pt0-deployment/setup_singleton.sh

No point in checking for license accept when nothing is being installed

ignore license accept in check mode

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/migrate_tenant.sh
cp3pt0-deployment/setup_singleton.sh
cp3pt0-deployment/setup_tenant.sh

script enhancement for ticket: https://github.ibm.com/ibmprivatecloud/roadmap/issues/57080

update install mode with manual option

---

cp3pt0-deployment/migrate_tenant.sh
cp3pt0-deployment/setup_singleton.sh
cp3pt0-deployment/setup_tenant.sh

script enhancement for ticket:
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57415

pre-requisite check for channel and profile size

---

cp3pt0-deployment/migrate_tenant.sh

patch license with CS CR

---

cp3pt0-deployment/setup_tenant.sh

Check if CommonService CRD exists without cluster permission
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58489#issuecomment-56966517

Avoid cluster permission

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml

Updated for CS 3.19.x
for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58680

[3.19] update imagePullPolicy to IfNotPresent

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml

Updated for CS 3.23.x 
for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58680

[3.23] update imagePullPolicy to IfNotPresent

---

isolate.sh

and remove bindinfo, which will be left-over

don't remove IBMLicensing singleton CR which has customisations

---

controllers/bootstrap/init.go
controllers/commonservice_controller.go

fix an issue in the BYOCA certificate test.
We should only detect if it is BYOCA when we reconciling Master CR

BYOCA enhancement

---

controllers/constant/odlm.go

for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58739

exclude cp automation CatalogSource

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/setup_tenant.sh

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58771
if we fail to patch CommonService CR we should retry it after installing cs-operator

retry patch commonservice cr for webhook issue

---

cp3pt0-deployment/common/migrate_singleton.sh
isolate.sh

FYI @pgodowski 
Test result
```
[INFO] No licensing configmaps to migrate
clusterserviceversion.operators.coreos.com "ibm-licensing-operator.v4.0.0" deleted
error: timed out waiting for the condition on operandbindinfos/ibm-licensing-bindinfo
[✗] Failed to delete OperandBindInfo, patching its finalizer to null...
operandbindinfo.operator.ibm.com/ibm-licensing-bindinfo patched
[INFO] Deleting existing Deployment secretshare in namespace ibm-common-services...
[✔] Singletons successfully uninstalled
```

Patch finalizer for licensing OperandBindInfo

---

cp3pt0-deployment/common/migrate_singleton.sh
isolate.sh

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58774#issuecomment-57455251

Bug/58774: finalizer needs to be removed for licensing OperandBindInfo

---

controllers/commonservice_controller.go
main.go

For issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57890
Testing image: `quay.io/yuchen_shen/cs_operator:csmaps_update`
`common-service-maps` ConfigMap will be updated whenever `servicesNamespace` is changed in CommonService CR even the new servicesNamespace is already in the tenant scope. Therefore, no restart is triggered.
- Option 1 
1. Install new IBM Cloud Pak foundational services (v4.0) by using the same namespace for `servicesNs` and `operatorNs`
2. Apply the testing image 
3. Patch CommonService CR with different services namespace which is already in the `WATCH_NAMESPACE`
4. Observe `namespaceMapping` is updated with new servicesNamespace
- Option 2
1. delete a namespace in `spec.namespaceMembers` in nss CR
2. the namespace will be auto removed from …

Creating and updating common-service-maps when reconciling master CS CR

---

cp3pt0-deployment/uninstall_tenant.sh

If the namespace deletion is stuck, it will automatically start to uninstall the resources forcefully in that namespace by patching the finalizers

Enhance force uninstallation

---

cp3pt0-deployment/common/utils.sh

cover corner case where the cluster does not have ODLM

fix scale down function for csv and deployment missing

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manager/manager.yaml
testdata/deploy/deploy.yaml

enhance for: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58680

Update ImagePullPolicy to IfNotPresent

---

controllers/bootstrap/init.go
controllers/operandconfig.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58257
The issue only happens on Advance Topology involving multiple namespaces.
When we update the default CommonService CR `.spec.size` from `large` back to `starterset`, The OperandConfig still contains large profile with `replicas: 3`
In advance topology, common service operator will clone default CommonService CR into all other namespaces in this tenant. It is used to help other common service operator installed in the tenant to identify its position.
Those cloned CommonService CRs are identical to the default CommonService CR, except a special label
```
operator.ibm.com/common-services.cloned-from: <operator-namespace>
```
In other words, those cloned CommonService CRs contains the size profile configurations which is the same as …

Add label selector to filter out cloned CS CRs

---

controllers/constant/odlm.go

fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58981

update edb license job digest

---

isolate.sh

Validated in issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58993, this error was blocking cpd today so higher priority to merge

Check if IBMLicensing CRD exists or not (#1300)

---

preload_data.sh

See #1308 for more details
* z specific changes to preload process
* syntax error
* troubelshooting
* troubleshooting and error handling
* restart mongo pods again
* typo
* change oc to variable, add timing
* troubleshooting
* reduce replicas
* disable ssl for dummy
* change back to prefer
* more targeted check for job completion
* standardize wait function
* remove unused code
---------

z specific changes to preload process (#1308)

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/58764

[CS LTSR] "disconnected" annotation for assessment

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/58764

[CS 323] "disconnected" annotation for assessment

---

controllers/bootstrap/init.go
controllers/commonservice_controller.go

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58575

cs operator should laways deploy certmanager cr if crd exist

---

convert_to_multi_instance.sh

variable names were mixed up causing script to fail, ran new version and it is working now

fix bug in conversion script

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/setup_tenant.sh

for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59207
Enhancement will check the Cert Manager CSV in Operator Namespace

[BD 4.1] specify namespace for Cert Manager checking

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58763

[Bedrock 4.1] "disconnected" annotation for certification assessment

---

controllers/constant/odlm.go

ticket: https://github.ibm.com/ibmprivatecloud/roadmap/issues/59254

[Fixpack 323] Update EDB License Image

---

controllers/constant/odlm.go

ticket: https://github.ibm.com/ibmprivatecloud/roadmap/issues/59254

[LTSR] Update EDB License Image

---

controllers/size/large_ppc64le.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59443

Remove additional space to fix yaml format issue

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/setup_tenant.sh

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57618
- All temporary yaml files are save under `/tmp/preview`
- Using `oc --dry-run=client` command to apply all the yaml files when preview mode is on
- Re-organized the test logs
- Enhanced some condition check

Preview mode for setup tenant script

---

cs-onprem-tenant-config.sh

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59271

Onboard IAM script for customizing hostname

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/setup_tenant.sh

for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57417
- patch channel and catalogsource in NSS sub
- wait for upgrade done with checking installedCSV NSS sub
- patch channel and catalogsource in CS sub
- wait for upgrade done with checking installedCSV CS sub

Patch channel and catalogsource for 4.1 upgrade

---

cp3pt0-deployment/setup_tenant.sh

- If `setup_tenant.sh` is running on a tenant which already contains main CommonService CR in the operatorNamespace, it will obtain the configurations from existing CS CR, and assign it to variables as default value
- When updating the CommonService CR, it will patch on existing CR to preserve other unchanged fields.
```
> ./cp3pt0-deployment/setup_tenant.sh --operator-namespace cloudpak-shared --tethered-namespaces cp4i,cp4ba  --license-accept -c v4.0 -p small
[INFO] CommonService CRD exists but main CommonService CR does not exist, skipping defaulting from original CommonService CR
...
[INFO] Creating the CommonService object: …
```

Preserve CR Configurations during the upgrade

---

cp3pt0-deployment/setup_tenant.sh

`setup_tenant.sh` would support upgrade inside v4.x version e.g., from `v4.0` to `v4.1` for simple and all namespace topology
- It is still NOT allowed
```
./cp3pt0-deployment/setup_tenant.sh --license-accept -c v4.0 --operator-namespace cloudpak-simple    
[INFO] CommonService CRD exists but main CommonService CR does not exist, skipping defaulting from original CommonService CR
[✗] It is simple topology or all namespaces topology
[✔] Profile size is not specified. Use default value: starterset
[✘] Must provide additional namespaces for --tethered-namespaces or --excluded-namespaces when services-namespace is the same as operator-namespace
```
- Upgrade for simple topology is …

support upgrade for simple and all namespaces mode

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manager/manager.yaml

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53999

[3.23] change update strategy to recreate

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml

for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59648

add delete permission on cert for SOD

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/setup_singleton.sh
cp3pt0-deployment/setup_tenant.sh

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59565
We hit an issue that OLM is not able to propagate WATCH_NAMESPACE from CSV into its deployment. The mitigation is to patch `ibm-common-service-operator` deployment with expected `WATCH_NAMESPACE` when OLM fails to do so.
```
> ./cp3pt0-deployment/setup_tenant.sh --license-accept -c v4.0 --operator-namespace cloudpak-control --services-namespace cloudpak-data
...
subscription.operators.coreos.com/ibm-common-service-operator created
[INFO] Waiting for operator ibm-common-service-operator CSV in namespace cloudpak-control to be generated
[✔] Operator ibm-common-service-operator CSV in namespace cloudpak-control is generated
[INFO] Waiting for operator ibm-common-service-operator CSV to be patched with NamespaceScope ConfigMap …
```

Remediate NSS CSV Injector propagation issue

---

cp3pt0-deployment/uninstall_tenant.sh

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59683
We could hold it until 4.2

add wait timeout for delete

---

convert_to_multi_instance.sh

For issue 57770, make sure the channel matches the original cs operator subscription value as well as the catalog source. This commit also changes the file in place instead of deleting the existing subscription by removing certain metadata fields and then applying the file on top of the existing subscription.

change channel along with subscription

---

Makefile
bundle.Dockerfile
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
bundle/manifests/operator.ibm.com_commonservices.yaml
bundle/metadata/annotations.yaml
common/Makefile.common.mk
config/crd/bases/operator.ibm.com_commonservices.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/bootstrap/init.go

for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/57188
same as PR: https://github.com/IBM/ibm-common-service-operator/pull/1390

[323] detection of OCP cluster type

---

Makefile
bundle.Dockerfile
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
bundle/manifests/operator.ibm.com_commonservices.yaml
bundle/metadata/annotations.yaml
common/Makefile.common.mk
config/crd/bases/operator.ibm.com_commonservices.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/bootstrap/init.go

for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/57188
- Determine whether the cluster is OCP by verifying the existence of an Infrastructure Custom Resource named `cluster`.
- Give the cluster permission to API `config.openshift.io`
- Test image: quay.io/yuchen_shen/cs_operator:cluster_type_ltsr
- Test result: `Cluster type is OCP: true`

[LTSR] detection of OCP cluster type

---

cs-onprem-tenant-config.sh

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59769

[4.1] Update image tag to 4.0.0

---

cs-onprem-tenant-config.sh

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59769

[4.0] Update image tag to 4.0.0

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/migrate_tenant.sh
cp3pt0-deployment/setup_tenant.sh

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57416
Verify if the phase status of master and each copied CommonService CR in tenant scope is `Succeeded`

Verify master and copied CommonService CR status

---

convert_to_multi_instance.sh

Conditionally restart the webhook pod in the control namespace after deleting the webhook config. This is mostly to deal with subsequent runs as this is not a problem on the first run. Tested myself on amd64 and it is working as expected. 
Test:
- setup env with 2 cp namespaces using ibm-common-services
- convert once by moving one namespace to it's own tenant
- convert a second time by moving the remaining cp namespace to its own tenant
- verify webhook pod is deleted (look for info line "Webhook pod in control namespace, restarting.")
- verify the operandrequests' registryNamespace values have been changed from ibm-common-services to the new registry namespace for the new tenants

restart the webhook pod after deleting config

---

preload_data.sh

While creating a solution for a customer to change the storage class for mongo, we ran into an issue where the storage class had a `volumeBindingMode` value of `WaitForFirstConsumer` hanging the script while waiting for the `cs-mongodump` pvc to bind. This means that the storage class will not bind a pv to a pvc unless the pvc is attached to a running pod. To fix this, I added a conditional check to see if this specific `volumeBindingMode` is set. If it is, we do not wait for the pvc to bind and instead move on. Once the mongo backup pod is created, it will use the `cs-mongodump` pvc which then allows the pvc to bind to a pv provisioned by the storage class and the process continues as expected. The scripts for changing storage class for mongo were based on the preload_data script (the …

check for WaitForFirstConsumer bind mode

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60010

[LTSR] update conversion image with latest tag

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60010

[323] update conversion image with latest tag

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60010

[CD] update conversion image with latest tag

---

cs-onprem-tenant-config.sh

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60010

update iam-custom-hostname tag to latest

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manager/manager.yaml

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59738

add ephemeral-storage request to container

---

bundle/manifests/operator.ibm.com_commonservices.yaml

Revert the undesired changes from PR https://github.com/IBM/ibm-common-service-operator/pull/1449

restore preserver unknown field marker

---

controllers/constant/odlm.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60194

exclude operatorhubio-catalog for cncf cluster

---

convert_to_multi_instance.sh

Cherry Pick of #1446 
All scripts for Bedrock 4.x release is contained in Bedrock CASE bundle, please see more details on [how to obtain scripts for each release](https://www.ibm.com/docs/en/cloud-paks/foundational-services/4.1?topic=co-downloading-scripts-additional-configuration-from-specific-version-case-bundle).

verify yq version (#1446)

---

controllers/rules/rules.go
controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go
controllers/size/starterset_amd64.go
controllers/size/starterset_ppc64le.go
controllers/size/starterset_s390x.go
testdata/actual.yaml
testdata/expected.yaml

issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/56920#issuecomment-52606444

removed auditService from IM Authentication CR

---

cp3pt0-deployment/common/migrate_singleton.sh
cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/migrate_tenant.sh
cp3pt0-deployment/setup_singleton.sh
cp3pt0-deployment/setup_tenant.sh

This is a PR to
- Address several readability issues.
- https://github.ibm.com/ibmprivatecloud/roadmap/issues/59943
- https://github.ibm.com/ibmprivatecloud/roadmap/issues/60056
- Enhance the health check on `.status.installedCSV` for each subscription during the installation.
- https://github.ibm.com/ibmprivatecloud/roadmap/issues/59973

Script and readability enhancements

---

controllers/constant/odlm.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60104
test image: quay.io/yuchen_shen/cs_operator:keycloak_config

add create-postgres-license-config job under edb-keycloak

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/migrate_tenant.sh
cp3pt0-deployment/setup_singleton.sh
cp3pt0-deployment/setup_tenant.sh

issue enhancement: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59447
- Set private CatalogSource flag in setup tenant script
- Check and correct cs operator catalogsource in each scoped namespace

enable private CatalogSource in setup tenant script

---

velero/backup/zen/zen5_backup_job.yaml
velero/backup/zen/zen5_backup_pvc.yaml
velero/restore/restore-configmap.yaml
velero/restore/restore-crd.yaml
velero/restore/restore-zen5-data.yaml
velero/restore/zen/zen5-restore-job.yaml
velero/schedule/zen5-backup-deployment.yaml
velero/schedule/zen5-backup-pvc.yaml
velero/schedule/zen5-br-scripts-cm.yaml
velero/schedule/zen5-clusterrole.yaml
velero/schedule/zen5-clusterrolebinding.yaml
velero/schedule/zen5-sa.yaml
velero/schedule/zen5_backup_pvc.yaml

related to https://github.com/IBM/ibm-common-service-operator/pull/1467

add necessary br files for 4.x br process

---

cp3pt0-deployment/setup_singleton.sh
isolate.sh

1. Move Lvc Reporter isolation process after pre-req is done
2. Support feature release of License Service Reporter upgrade. e.g., `v4.2` to `v4.3` upgrade
3. In case customer did some customization, preserve License Service Report CR additional configuration during the upgrade
```
kind: IBMLicenseServiceReporter
metadata:
name: ibm-lsr-instance
namespace: ibm-lsr
spec:
authentication:
useradmin:
enabled: true
license:
accept: true
resources:    <--------- add by user
limits:
cpu: '1'
```
1. Fresh install LSR on a new cluster should be successful
2. Execute the script with same parameter should be successful as well
```
./cp3pt0-deployment/setup_singleton.sh --enable-licensing --enable-license-service-reporter --license-accept -c v4.2
```

Support LSR 4.x upgrade

---

cp3pt0-deployment/migrate_tenant.sh

Addressing LSR upgrade for **in-place upgrade** scenario: 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60036#issuecomment-63290057
Implemented in `migrate_tenant.sh` a similar step as it is in `isolate.sh`  for LSR isolation.

LSR and in-place upgrade

---

velero/backup/licensing/label-licensing-configmaps.sh

necessary to match what is in the docs and scripts branch

update label licensing to take namespace parameter

---

backup_restore_mongo/backup_restore_mongo.sh

fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57765
-  Look into `spec.volumeName` in a specific PVC named `cs-mongodump` yaml to get exact one PV instead of using `oc get pv | grep cs-mongodump` as PV is a cluster scoped value.
-  Clear previously used restore resources before starting the new restore process, and this will prevent script errors out when running it multiple times.

Clean up redundant cs-mongodump pv and pvc before restore process

---

velero/schedule/schedule-common-services.yaml

match scripts-dev to scripts to actually backup and restore new items

add new tags to scripts dev

---

cp3pt0-deployment/common/cleanup_cp2_control.sh

fix bugs found in testcases in the cleanup-cp2-control script

fix bugs in test

---

controllers/constant/odlm.go

slack discussion: https://ibm-cloudplatform.slack.com/archives/G013X1K33AN/p1695758186991149

bump MongoDB and ODLM channel to v4.2

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml

Resolves https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59790

Add common label to operator Deployment/Pod

---

velero/restore/zen/zen5-restore-job.yaml
velero/schedule/zen5-backup-deployment.yaml
velero/schedule/zen5-br-scripts-cm.yaml

Account for updates to the zen 5 backup and restore procedure to include jwks secret backup and restore

update br scripts to copy over jwks secrets

---

backup_restore_mongo.sh

cherry pick PR: https://github.com/IBM/ibm-common-service-operator/pull/1503 and https://github.com/IBM/ibm-common-service-operator/pull/1507 into scripts branch
fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57765

clean up cs mongodump pvc

---

controllers/constant/odlm.go

It is used to share Keycloak service and credential information
1. Deploy dev build CPFS as usual by creating common service operator subscription, wait for Common Service Operator and ODLM to be installed.
2. Delete existing OperandConfig `common-service` in this tenant
3. Replace the image in Common Service operator CSV to `quay.io/daniel_fan/common-service-operator-amd64:dev`, and set `ImagePullPolicy` to `Always`
4. Create OperandRequest to request `keycloak-operator`, waiting for KeyCloak to be installed
5. We should be able to obtain the KeyCloak Information from Secret/ConfigMap
- <details>
<summary>Secret with the admin user / password `keycloak-bindinfo-cs-keycloak-initial-admin`</summary>
```bash
> oc get secret keycloak-bindinfo-cs-keycloak-initial-admin -n <cloudpak-ns> -o …
```

Add Keycloak BindInfo to OperandConfig

---

cp3pt0-deployment/migrate_tenant.sh
cp3pt0-deployment/setup_tenant.sh

```
> ./cp3pt0-deployment/setup_tenant.sh -v 1 --operator-namespace cloudpak-cp3-control --tethered-namespaces cp4i --license-accept -c v4.3
[✔] Channel v4.3 is valid
[INFO] CommonService CRD exists but main CommonService CR does not exist, skipping defaulting from original CommonService CR
[✔] Profile size is not specified. Use default value: starterset
[✔] CatalogSource opencloud-operators from openshift-marketplace CatalogSourceNamespace is available for ibm-common-service-operator in cloudpak-cp3-control namespace
[INFO] Creating namespace cloudpak-cp3-control
namespace/cloudpak-cp3-control created
[INFO] Waiting for project cloudpak-cp3-control to be created
[✔] Project cloudpak-cp3-control is …
```

Mapping CS and NSS version with awk binary

---

controllers/rules/rules.go

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59738

add ephemeral storage limit to operandConfig rule

---

controllers/constant/odlm.go

Resolves https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60735

remove Keycloak initial admin bind info

---

cp3pt0-deployment/setup_tenant.sh

1.  Add `--ignore-not-found` to nss CR when it is first created and will not display error msg
2. The script will regenerate the role if the role is accidentally deleted and RoleBinding already exists
3. Print out the newly generated Role and RoleBinding only when DEBUG is on
- debug is on (-v 1)
```
role.rbac.authorization.k8s.io/nss-managed-role-from-nss-deduction created
[INFO] Waiting for role nss-managed-role-from-nss-deduction in namespace nss-cp to be created
[✔] Role nss-managed-role-from-nss-deduction in namespace nss-cp is created
rolebinding.rbac.authorization.k8s.io/nss-managed-role-from-nss-deduction created
[INFO] Waiting for rolebinding nss-managed-role-from-nss-deduction in namespace nss-cp to be created
```
- debug is off (-v 0)
```
[DEBUG] Creating following Role: …
```

authorize nss log improvement

---

cp3pt0-deployment/setup_tenant.sh

for ticket https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60825

update yq path

---

cp3pt0-deployment/common/utils.sh

Issue:
- https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60906
- https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59830

increase time for waiting CSV to bypass CatalogSource connection issue

---

velero/backup/cert-manager/label-cert-manager.sh

same thing as #1548 but for the scripts branch

label cert-manager.io specific resources and custom route secrets

---

velero/schedule/zen5-br-scripts-cm.yaml
velero/schedule/zen5-clusterrole.yaml
velero/schedule/zen5-clusterrolebinding.yaml
velero/schedule/zen5-sa.yaml

same as #1550 but for scripts branch

add labels to zen5 permissions, add errexit to zen5 scripts

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/commonservice_controller.go

- and jobs for iam-onboarding status check

added permissions for cert-manager resources

---

velero/backup/cert-manager/label-cert-manager.sh
velero/schedule/zen5-backup-deployment.yaml

Same as #1567 but for scripts branch

bump up zen restore timeout, add error handling for custom secrets

---

controllers/constant/odlm.go

Add a realm that can be shared across consumers.

Add a default realm for sharing

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/migrate_tenant.sh

Script enhancement ticket: https://github.ibm.com/ibmprivatecloud/roadmap/issues/60360
1. The end to end migration flow is done via `migrate_tenant.sh`.
2. The basic workflow 
- Identify the cluster status: All Namespace installation mode / Simple Topology / other (Advanced Topology) 
- Condition check for `Service NS`, `Control NS` and `NS List`
- Scale down original IBM CPFS instances
- IBM CS operator in`openshift-operators` namespace and ODLM in `ibm-common-services` namespace
- Migrate singleton services
- Update CS CR and upgrade CS operator
- Check if CS operators to move ODLM from `ibm-common-services` to `openshift-operators` ns
- Clean unused resources.
- Clean up cp2 resources as usual (including cs-webhook, secretshare, crossplan, OperandBindinfo and NSS CR)
- **New added**: …

enable all namespace mode migration

---

go.mod
go.sum

update grpc pkg

---

controllers/constant/odlm.go
controllers/rules/rules.go
controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go
controllers/size/starterset_amd64.go
controllers/size/starterset_ppc64le.go
controllers/size/starterset_s390x.go

Addresses the EDB profiles as requested in https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60915

Handle EDB and Keycloak profile sizes

---

velero/backup/cert-manager/label-cert-manager.sh

should be the exact same as https://github.com/IBM/ibm-common-service-operator/pull/1586 just need to make it available in the scripts repo

add default admin creds to backup

---

cp3pt0-deployment/migrate_tenant.sh

fix for the issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61091

fix target ns check for all namespace mode

---

velero/backup/cert-manager/label-cert-manager.sh

exact same as #1594 but for the scripts branch to make it public

add two more secrets to backup

---

velero/schedule/zen5-br-scripts-cm.yaml

Update the logic for grabbing extension names to be more consistent based on feedback from CP4BA

update zen extension logic based on feedback

---

isolate.sh

It will patch CS CR and OperandConfig for Management-Ingress CR with `multipleInstancesEnabled: false`, so `cp-console` will not have namespace suffix `cp-console.apps.ocp412-iso.cp.fyre.ibm.com`
```
metadata:
namespace: ibm-common-services
spec:
services:
- name: ibm-management-ingress-operator
spec:
managementIngress:
multipleInstancesEnabled: false
```
1. Deploy a old LTSR version 3.23.8 in the shared instance mode under `ibm-common-services`
2. Run updated `isolate.sh` against `ibm-common-services` namespace from [scripts-dev branch](https://github.com/IBM/ibm-common-service-operator/tree/scripts-dev) - wait for PR to be merged
3. Check `cp-console` Route, which does not have namespace suffix …

Patch multipleInstancesEnabled false for ManagementIngress CR to avoid cp-console change

---

cp3pt0-deployment/common/utils.sh

conditional was checking for empty instead of non-empty value

fixed upgrade_operator not deleting opreq label

---

velero/backup/mongoDB/mongodbbackup.yaml
velero/restore/mongoDB/mongo-restore.sh
velero/restore/mongoDB/mongodbrestore.yaml
velero/schedule/mongodb-backup-deployment.yaml
velero/schedule/mongodb-backup-pvc.yaml
velero/schedule/zen-backup-deployment.yaml
velero/schedule/zen-backup-pvc.yaml
velero/schedule/zen5-backup-deployment.yaml
velero/schedule/zen5-backup-pvc.yaml
velero/schedule/zen5-br-scripts-cm.yaml
velero/schedule/zen5-clusterrole.yaml
velero/schedule/zen5-clusterrolebinding.yaml
velero/schedule/zen5-sa.yaml

See issues 60195, 61131, and 61134

Update Zen extension logic to capture extensions before backup, standardize some values across files

---

velero/backup/mongoDB/mongodbbackup.yaml
velero/restore/mongoDB/mongo-restore.sh
velero/restore/mongoDB/mongodbrestore.yaml
velero/schedule/mongodb-backup-deployment.yaml
velero/schedule/mongodb-backup-pvc.yaml
velero/schedule/zen-backup-deployment.yaml
velero/schedule/zen-backup-pvc.yaml
velero/schedule/zen5-backup-deployment.yaml
velero/schedule/zen5-backup-pvc.yaml
velero/schedule/zen5-br-scripts-cm.yaml
velero/schedule/zen5-clusterrolebinding.yaml
velero/schedule/zen5-sa.yaml

Exact same changes as here https://github.com/IBM/ibm-common-service-operator/pull/1610 to be made available publicly

match scripts dev commits

---

cp3pt0-deployment/common/utils.sh

to use oc patch instead of oc apply because of unknown issue in oc apply causing labels to return after being removed

changed opreq-control label removal implementation

---

velero/schedule/zen5-br-scripts-cm.yaml

While reviewing code to see what is applicable for keycloak, I found this duplicate code snippet. Functionally doesn't change much but prefer it not be there.

remove duplicate code

---

velero/schedule/zen5-role.yaml
velero/schedule/zen5-rolebinding.yaml

Reduce overall permissions for zen 5 backup

update cluster role to role and remove some permissions

---

api/v3/commonservice_types.go
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
bundle/manifests/operator.ibm.com_commonservices.yaml
config/crd/bases/operator.ibm.com_commonservices.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
docs/install.md

Update installer License short link

---

controllers/commonservice_controller.go
controllers/recocile_pause.go

addressed issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59018
cherry pick https://github.com/IBM/ibm-common-service-operator/pull/1661

[323] Introduce basic maintenance mode in CS operator

---

controllers/commonservice_controller.go
controllers/recocile_pause.go

addressed issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59018
cherry pick https://github.com/IBM/ibm-common-service-operator/pull/1661

[LTSR] Introduce basic maintenance mode in CS operator

---

preload_data.sh

With help from the Power and Z teams last month, we have a new mongo image version that includes mongorestore and mongodump binaries for Power and Z that can use the `--ssl` options. This change allows us to remove the platform specific steps used to backup and restore the mongo database and that is what this pr does.
Test:
- setup cluster with an instance of mongo (preferably on a power or z cluster)
- run preload_data.sh to a test namespace
- verify script completes
- check outputted logs to verify backup and restore performed successfully

use new mongo image with new mongorestore and mongodump tools that utilize ssl on power/z clusters

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/migrate_tenant.sh
cp3pt0-deployment/setup_singleton.sh
cp3pt0-deployment/setup_tenant.sh
cp3pt0-deployment/uninstall_tenant.sh
isolate.sh
preload_data.sh

for ticket https://github.ibm.com/ibmprivatecloud/roadmap/issues/61014
check yq version for preload_data.sh

preload_data check yq version

---

controllers/constant/secretshare.go

remove `service` namespace in secretshare default cr yaml (#1658)

---

controllers/common/util.go
controllers/scopewatcher_controller.go

Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61345
Common Service v3 will add latest scope after excluding detached namespace in CS map configmap.
1. install v3 operator in `ibm-common-services` ns and shared with two cloudpaks: `cp4i, cp4i-2`
2. change test image: quay.io/yuchen_shen/cs_operator:ltsr-csmap-update
3. switch cs oeprator channel to v4.3 in `cp4i` ns
4. common-service-maps will be created with:
```
data:
- map-to-common-service-namespace: cp4i
requested-from-namespace:
- cp4i
- map-to-common-service-namespace: ibm-common-services
requested-from-namespace:
- cp4i-2
- ibm-common-services
```

v3 operator update cs map to latest tenant namespaces during self-isolation process

---

controllers/commonservice_controller.go

Skip reconciliation if CR is not in tenant scope

---

controllers/bootstrap/init.go
controllers/common/util.go
controllers/commonservice_controller.go
controllers/scopewatcher_controller.go

cherry pick https://github.com/IBM/ibm-common-service-operator/pull/1666

[323] Enable and Disable CS CR reconciliation in self-isolation

---

controllers/bootstrap/init.go
controllers/goroutines/cleanup_deprecated_services.go
controllers/scopewatcher_controller.go

for ticket: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61347
Delete Crossplane, webhook, and secretshare deployment and resources

Delete Crossplane, webhook, and secretshare deployment

---

controllers/bootstrap/init.go
controllers/goroutines/cleanup_deprecated_services.go
controllers/scopewatcher_controller.go

cherry pick PRs from release-ltsr

[323] clean up resources

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/bootstrap/init.go
controllers/common/util.go
controllers/commonservice_controller.go
controllers/constant/constant.go
controllers/goroutines/cleanup_deprecated_services.go
controllers/goroutines/operator_status.go
controllers/operandconfig.go
controllers/scopewatcher_controller.go

Backup and migrate Licensing Data including possible Licensing ConfigMaps and Licensing CRs

Backup and Migrate Licensing Data

---

Makefile
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/bootstrap/init.go
controllers/common/util.go
controllers/commonservice_controller.go
controllers/constant/constant.go
controllers/goroutines/cleanup_deprecated_services.go
controllers/goroutines/operator_status.go
controllers/operandconfig.go
controllers/scopewatcher_controller.go

Cherry-pick of PR #1675 #1678 #1680

Sync release-323 branch with LTSR branch

---

controllers/constant/odlm.go

Addresses https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61306
How to test: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61306#issuecomment-67886825

Add Keycloak truststore configuration option

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/bootstrap/init.go
controllers/common/util.go
controllers/commonservice_controller.go
controllers/scopewatcher_controller.go

Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61347
Isolate License Service Reporter
- change persistentVolumeReclaimPolicy to Retain
- label LSR PV as LSR PV for further LSR upgrade

Isolate License Service Reporter during self-isolation

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/bootstrap/init.go
controllers/common/util.go
controllers/commonservice_controller.go
controllers/scopewatcher_controller.go

* isolate LSR
* add permission for LSR, PVC and PV
* add get pv function

[323] Isolate License Service Reporter during self-isolation (#1684)

---

controllers/commonservice_controller.go

Address issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61530
After modifying `common-service-maps` ConfigMap, to add test1 namespace into the scope of CS 3.x (along with ibm-common-services), nothing happened
- expected that test1 namespace would be added into CS 3.x scope automatically, since `common-service-maps` was edited
The update on `common-service-maps` ConfigMap should trigger the reconciliation of CS CR.

Trigger CR reconciliation with mapping ConfigMap

---

controllers/common/util.go
controllers/scopewatcher_controller.go

Updates on self-isolation process:
1. Updating NSS CRs `common-service` and `nss-odlm-scope` by adding updatedNsList and removing excludedNsList
2. Remove NSS CRs `nss-managedby-odlm` and `odlm-scope-managedby-odlm`

Update excluded namespace list before removing nss CRs managed by ODLM

---

controllers/common/util.go
controllers/commonservice_controller.go
controllers/scopewatcher_controller.go

cherry pick PRs:
1. [Trigger CR reconciliation with mapping ConfigMap](https://github.com/IBM/ibm-common-service-operator/commit/6f7a22e0509fd2b77f27683e8e9a8d194eadf03d)
2. [update ns in nss cr](https://github.com/IBM/ibm-common-service-operator/commit/e3b1beba188c566bc1049c7fcefadec5c569d0e0)

[LTSR] cherry pick from release-323

---

controllers/operandconfig.go

Same fix as https://github.com/IBM/ibm-common-service-operator/pull/1694. More details can be found there

avoid overwriting CS CR

---

controllers/operandconfig.go

[efix] fix: get extreme value on resources field when spec field does not exist

---

controllers/bootstrap/init.go

Add managedByCsOperator label for ConfigMap

---

controllers/common/util.go
main.go

create empty common-service-maps ConfigMap to add label when ConfigMap does not exist

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml

added permissions explicitly for cloud-native-postgresql-image-list c……… (#1710)

---

velero/restore/zen/zen-restore-job.yaml
velero/schedule/zen-backup-deployment.yaml
velero/schedule/zen4-br-scripts.yaml
velero/schedule/zen4-role.yaml
velero/schedule/zen4-rolebinding.yaml
velero/schedule/zen4-sa.yaml

After discussing with the Zen team, the previous process was insufficient and required more steps. Overhauled the existing process to cover each of the required steps and based the new process implementation on how we handle zen 5 for parity. The documentation is updated to match.
exact same as #1716

Overhaul zen 4 BR, match scripts-dev

---

controllers/constant/odlm.go

ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61715

add Opensearch entry into Operand Registry

---

isolate.sh

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61431

update csv count and add error messages

---

Dockerfile
Makefile
api/v3/commonservice_types.go
controllers/bootstrap/init.go
controllers/common/util.go
controllers/constant/keycloakThemes.go
controllers/constant/odlm.go
hack/keycloak-themes/Makefile

Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61462
1. Install CS operator from daily build in simple topology.
2. Delete OperandConfig generated by CS operator from daily build
```bash
oc -n <your-services-ns> OperandConfig common-service
```
3. Patch CS operator with dev image and change ImagePullPolicy by running following command.
```bash
oc -n <your-operator-ns> patch csv ibm-common-service-operator.v4.4.0 --type="json" -p '[{"op": "replace", "path":"/spec/install/spec/deployments/0/spec/template/spec/containers/0/imagePullPolicy", "value":"Always"}]'
oc -n <your-operator-ns> patch csv ibm-common-service-operator.v4.4.0 --type="json" -p '[{"op": "replace", "path":"/spec/install/spec/deployments/0/spec/template/spec/containers/0/image", …
```

Integerate Keycloak theme

---

controllers/common/util.go
main.go

Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/60900
To prevent user from forgetting to include tenant namespace in `common-service-maps` ConfigMap prior to CPFS v3 deployment, CPFS v3 will automatically update the ConfigMap by adding its own operator namespace as a new entry and mapping to `ibm-common-services namespace`
1. Deploy v4 operator in one cloudpak ns `cp4d`
2. Deploy a new v3 operator in another cpns `cp4i`
3. Observe the there is no entry about `ibm-common-services` and `cp4i` namespaces in `common-service-maps` and only `ibm-common-services` in `namespace-scope` in cs namespace
```yaml
apiVersion: v1
metadata:
name: common-service-maps
namespace: kube-public
labels:
operator.ibm.com/managedByCsOperator: 'true'
data: …
```

[LTSR] automatically update cs maps with adding operator and master namespace into a new entry

---

controllers/common/util.go
controllers/scopewatcher_controller.go

cherry pick from release-ltsr: https://github.com/IBM/ibm-common-service-operator/pull/1769

[323] migrate licensing configmaps in self-isolation

---

cp3pt0-deployment/common/migrate_singleton.sh
isolate.sh

Need to set the key in the LSR secret for the Licensing service instance.
To prevent the error:

Set key token when creating the LSR secret

---

controllers/constant/odlm.go

Github comments: https://github.ibm.com/ibmprivatecloud/roadmap/issues/62065#issuecomment-71987149

[4.5] Config two certificates for Zen and IM by ODLM

---

controllers/constant/odlm.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62067
ODLM creates OperandBindinfo, and configmaps that include default connection information for IM and Zen databases.
Test result:
1. image: quay.io/yuchen_shen/cs_operator:shared_edb
2. two ConfigMaps created

Create IM and Zen ConfigMap and OperandBindInfo

---

controllers/bootstrap/init.go
controllers/commonservice_controller.go
controllers/constant/constant.go

Fix for OprandRegistry and NSS CRs CRD not present in fresh deployment.

Check OprandRegistry and NSS resources CRD in fresh deployment

---

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62352

minimal RBAC file updated for NSS CRs cleaned up by CS operator

---

preload_data.sh

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62061
In order to support IAM MongoDB to EDB migration scenario, we will create a ConfigMap `mongodb-preload-endpoint` containing service endpoint and connection information for IM to discover. Several resources are required for IM to build connection with old MongoDB instance.
- Service endpoint for old MongoDB instance, presenting as `mongodb.$FROM_NAMESPACE.svc.cluster.local`
- A secret `mongodb-root-ca-cert` containing CA Certificate is copied over from original namespace
- A secret `icp-mongodb-client-cert` containing client Certificate is copied over from original namespace
- A secret `icp-mongodb-admin` containing user/pass credential for MongoDB database
Here are two scenarios.
1. User is using `preload_data.sh` to …

Create a ConfigMap `mongodb-preload-endpoint` for IM to connect with MongoDB instance in original namespace

---

cp3pt0-deployment/common/migrate_singleton.sh
cp3pt0-deployment/setup_singleton.sh

remove space in the $LSR_NAMESPACE in the message

LSR CR name consolidate in migration scenario

---

cp3pt0-deployment/common/migrate_singleton.sh
cp3pt0-deployment/setup_singleton.sh

to ensure that a controlNamespace is always available for migration
to decouple from isolation needing to be run first

setup singleton ensures cm-maps created

---

preload_data.sh

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62304
To verify if all the following resources are truly copied over to new namespace. If they are not existing in the original namespace, then skipping cope it.
- Secret `platform-auth-idp-credentials`
- Secret `platform-auth-ldaps-ca-cert`
- ConfigMap `ibm-cpp-config`
- ConfigMap `common-web-ui-config`
- ConfigMap `platform-auth-idp`
- commonservice `preload-common-service-from-$FROM_NAMESPACE`
- Secret `icp-mongodb-client-cert`
- Secret `mongodb-root-ca-cert`
- Secret `icp-mongodb-admin`

check copied resrouces

---

cp3pt0-deployment/migrate_tenant.sh
cp3pt0-deployment/setup_singleton.sh
cp3pt0-deployment/setup_tenant.sh
cp3pt0-deployment/uninstall_tenant.sh
isolate.sh
preload_data.sh

enhancement: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57620#issuecomment-74180478
newly added:
- Print all arguments passed into the script.
- Avoid using an unset variable.
- Include additional error traces.

Adding additional error handling to the scripts

---

cp3pt0-deployment/common/delegate_cp2_cert_manager.sh
cp3pt0-deployment/common/migrate_cp2_licensing.sh
cp3pt0-deployment/common/utils.sh
isolate.sh
preload_data.sh

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59238

create temporary files in /tmp

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/migrate_tenant.sh
cp3pt0-deployment/setup_singleton.sh
cp3pt0-deployment/setup_tenant.sh
cp3pt0-deployment/uninstall_tenant.sh

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57620#issuecomment-74180478
Improved error handling:
- Avoid using an unset variable.
- Include additional error msg.

Improve error handling

---

controllers/constant/odlm.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61733

Upgrade db2u operator channel to v5.

---

preload_data.sh

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62546

update error handling in preload_data.sh

---

controllers/constant/odlm.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62285#issuecomment-74522237

[323] Update EDB License Image

---

controllers/constant/cloudNativePostgresql.go
controllers/constant/odlm.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62285#issuecomment-74522237

Pick up EDB 1.18.10

---

cp3pt0-deployment/common/utils.sh

Enhance issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62623
Introduces a retry in the `validate_operator_catalogsource` function when the return value indicating no CatalogSource available. The function now attempts to correct and validate the CatalogSource for up to five times, with a 20-second delay between each attempt.

Add retry for CatalogSource validation

---

isolate.sh

issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/62428
Introduce a retry logic in the`wait_for_nss_update` function. If the comparison between the actual and expected namespace lists fails, the function will now retry for a maximum of 5 times, waiting for 20 seconds between each attempt. This improvement ensures better handling of cases where namespace updates are not immediately reflected.

Add retry logic to wait for namespaces list in NSS configmap to be updated

---

controllers/constant/odlm.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61732

add Keycloak as the owner of KeycloakRealmImport

---

cp3pt0-deployment/common/utils.sh

fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62702
If the NSS operator is automatically deleted during migration, we will patch the finalizer for the remaining NSS resources that also need to be deleted

Delete NSS resources by patching finalizer

---

controllers/constant/odlm.go

For: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62661

Adding new fields for 1.22 default compatibility

---

controllers/constant/odlm.go

Ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62792

add Apache Flink entry into OperandRegistry

---

controllers/constant/odlm.go

Resolves https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60711#issuecomment-74907167
cc @giacomoch

Valero/OADP support for Keycloak's EDB

---

velero/restore/common-service-db/cs-db-restore-job.yaml
velero/restore/keycloak/keycloak-restore-job.yaml

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62622
create workaround for keycloak and im edb backup and restore, in case Keycloak and IAM EDB BR process fails.

workaround for Keycloak and IM EDB BR

---

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62838

Add permission for operatorconfig for Minimal RBAC

---

controllers/constant/odlm.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62839

Update Cluster CR used by IM to be forwards compatible

---

controllers/constant/odlm.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61733

Upgrade DB2 operator channel to v5.2

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/migrate_tenant.sh

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62702#issuecomment-76091323
If failed to delete crossplane CRs, we will patch the finalizer for the remaining resources to delete them again.

Delete crossplane CR by patching finalizer

---

controllers/size/large_amd64.go

Ticket: https://github.ibm.com/ibmprivatecloud/roadmap/issues/62863

update common-service-db resources for large size on x86

---

cp3pt0-deployment/migrate_tenant.sh
isolate.sh
preload_data.sh

Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/62833

add yq argument and version check

---

cs-onprem-tenant-config.sh

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62325.
- We need not to check response of host to the ping

Removing ping

---

cp3pt0-deployment/common/utils.sh

Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/62702#issuecomment-76597003
Avoid error msg:
1. 
```
[INFO] Deleting podpresets in namespace olm-test...
No resources found in xxx namespace.
error: resource(s) were provided, but no name was specified
```
2.
```
/home/scripts/cpfs/installer_scripts/cp3pt0-deployment/common/utils.sh: line 1120: [: too many arguments
```

Enhance to prevent error messages

---

controllers/operandconfig.go

Fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62729
This intermittent issue occurs when the profile size is configured to anything other than `small/starterset`. After an isolate upgrade, the replica number may occasionally revert to 1, whereas it should actually match the configured profile size.
If multiple CommonServices with varying profile sizes are created within the same tenant, the CommonService operator should prioritize selecting the larger size and higher limitations. This selection should be applied to the OperandConfig consistently, regardless of the order in which the CS CRs were created. This approach ensures that the values chosen are always larger and correct, rather than being chosen randomly.
Test image: …

Resolve replica number reversion issue

---

velero/schedule/common-service-db/cs-db-br-script-cm.yaml

It is currently not being called but should still be removed as it is unecessary

remove wait for job function leftover from keycloak

---

cp3-networkpolicy/egress/generic/deny-all-egress.yaml
cp3-networkpolicy/egress/generic/egress-allow-same-namespace.yaml
cp3-networkpolicy/egress/operators/bedrock-egress-allow-k8s-services.yaml
cp3-networkpolicy/egress/operators/bedrock-egress-allow-services-namespace.yaml
cp3-networkpolicy/egress/services/bedrock-egress-allow-k8s-services.yaml
cp3-networkpolicy/egress/services/bedrock-egress-allow-operator-ns.yaml
cp3-networkpolicy/egress/services/bedrock-egress-platform-auth-service.yaml
cp3-networkpolicy/egress/services/bedrock-egress-platform-identity-management.yaml
cp3-networkpolicy/egress/services/bedrock-egress-platform-identity-provider.yaml
cp3-networkpolicy/egress/services/zen-egress-nginx.yaml
cp3-networkpolicy/egress/services/zen-egress-usermgmt.yaml
cp3-networkpolicy/egress/services/zen-egress-zen-metastoredb-init-job.yaml
cp3-networkpolicy/egress/services/zen-egress-zen-metastoredb.yaml
cp3-networkpolicy/egress/services/zen-egress-zen-minio.yaml
cp3-networkpolicy/ingress/generic/allow-from-openshift-ingress.yaml
cp3-networkpolicy/ingress/generic/deny-all-ingress.yaml
cp3-networkpolicy/ingress/generic/ingress-allow-same-namespace.yaml
cp3-networkpolicy/ingress/services/access-to-services-from-operator-namespace.yaml

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61115
Doc instructions update: https://github.ibm.com/IBMPrivateCloud/common-services-docs/pull/7825

Update network policy for CS 4.6

---

cp3pt0-deployment/common/authorize-namespace.sh

Script enhancement: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61112
We add support for NSS minimum RBAC in `authorize-namespace` script

[4.6.1, 4.7] Support mini RBAC in authorize namespace script

---

velero/restore/restore-singleton-subscriptions.yaml
velero/schedule/schedule-common-services.yaml

merging relevant changes from https://github.com/IBM/ibm-common-service-operator/pull/1918 into the scripts branch

add singleton subsciption to br process

---

cp3pt0-deployment/setup_singleton.sh

Enhance the ticket: https://github.ibm.com/ibmprivatecloud/roadmap/issues/60999
When the user misses to pass the LSR namespace during the upgrade, the script will automatically detect the namespace and proceed with the progress. If the provided namespace differs from the one existing in the cluster, an error will be returned.

Provide custom namespace for LSR

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
hack/keycloak-themes/README.md
hack/keycloak-themes/theme/cloudpak/login/resources/css/styles470.css
hack/keycloak-themes/theme/cloudpak/login/theme.properties
testdata/deploy/deploy.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62977

[4.7] fix checkbox on new user panel

---

controllers/constant/odlm.go

- This PR makes sure the EDB pods get the backup label
- This will also make sure all the secrets that need to be backed up are backed up
Fixes #

fix: making sure pods get the backup label

---

controllers/constant/odlm.go
controllers/operandconfig.go
controllers/rules/rules.go
controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go
controllers/size/starterset_amd64.go
controllers/size/starterset_ppc64le.go
controllers/size/starterset_s390x.go

Cherry-pick: https://github.com/IBM/ibm-common-service-operator/pull/1949

[4.6.2] EDB max connection config

---

controllers/constant/odlm.go

- to v4.6, v4.5, v6.0 respectively

updated channels for IM, commonui, and zen

---

controllers/constant/cloudNativePostgresql.go

Ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63187
Slack: https://ibm-cloudplatform.slack.com/archives/C027VSWBU1F/p1714666033814189
EDB CASE bundle: https://github.ibm.com/IBMPrivateCloud/cloud-pak/tree/master/repo/case/ibm-cloud-native-postgresql/4.25.0

[4.6.2] Pick up EDB 1.18.12

---

controllers/constant/cloudNativePostgresql.go
controllers/constant/odlm.go

Ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63187
Slack: https://ibm-cloudplatform.slack.com/archives/C027VSWBU1F/p1714666033814189
EDB CASE bundle: https://github.ibm.com/IBMPrivateCloud/cloud-pak/tree/master/repo/case/ibm-cloud-native-postgresql/4.25.0

[4.7] Pick up EDB operand Images from CASE 4.25.0

---

velero/schedule/deploy-br-resources.sh

QOL pr for deploying mongo BR resources with the new multi-mongo command, not a priority but also not an impactful change

update mongo sed command to work with mutliple entries per line

---

controllers/constant/odlm.go

cherry-pick: https://github.com/IBM/ibm-common-service-operator/pull/1958

[4.6.2] removed internal OperandRequest from edb-keycloak

---

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml

fix issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63348
Collect and update nss minimal RBAC role yaml

Updated min RBAC role 

---

cp3pt0-deployment/common/authorize-namespace.sh
cp3pt0-deployment/common/cleanup_cp2_control.sh
cp3pt0-deployment/common/migrate_singleton.sh
cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/setup_singleton.sh

Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/63395

parameterized yq and oc variables

---

controllers/constant/cloudNativePostgresql.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63370

[SC2] Update EDB new license image

---

controllers/constant/fipsEnable.go
controllers/constant/odlm.go
controllers/constant/serviceLabel.go
controllers/rules/rules.go
controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go
controllers/size/starterset_amd64.go
controllers/size/starterset_ppc64le.go
controllers/size/starterset_s390x.go
docs/cloudpak-integration.md
testdata/actual.yaml
testdata/expected.yaml

Created new entries in odlm.go after bumped the channel versions for those services
https://github.com/IBM/ibm-common-service-operator/pull/1960

Created new entries for IM, CommonUi, and Zen

---

controllers/constant/cloudNativePostgresql.go

issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63370

Update EDB new license image

---

controllers/constant/odlm.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63422

Add endpoint cs-db-rw into dnsNames

---

cp3-networkpolicy/egress/operators/bedrock-egress-egress-create-postgres-license-config.yaml
cp3-networkpolicy/egress/operators/bedrock-egress-ibm-mongodb-operator.yaml
cp3-networkpolicy/egress/operators/zen-egress-ibm-zen-setup-job.yaml
cp3-networkpolicy/egress/zen/zen-egress-edb-postgres.yaml
cp3-networkpolicy/ingress/zen/zen-access-to-zen-core.yaml

Add egress network policy for operator ns

---

controllers/constant/odlm.go

porting change from https://github.com/IBM/ibm-common-service-operator/pull/1954 into SC2 release stream for CP4I

add keycloak BR label for OADP

---

controllers/constant/odlm.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63489

Update indentation in OperandConfig

---

README.md
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manager/manager.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
controllers/constant/secretshare.go
controllers/constant/webhook.go
testdata/deploy/deploy.yaml
version/version.go

bump version to 3.19.22

---

controllers/constant/odlm.go

Fixes https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/21241
Re-implementing PR https://github.com/IBM/ibm-common-service-operator/pull/1912

consolidate annotations for EDB Cluster CR

---

controllers/constant/odlm.go

related to https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63296 and https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/21623

remove offline specific velero backup annotation

---

controllers/constant/odlm.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63422
cherry pick #1989

[4.6.3] add endpoint cs-db-rw into dnsNames

---

velero/backup/cert-manager/label-cert-manager.sh

To address https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62371 and https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61538

label some additional certificates, un-label a zen secret

---

velero/schedule/common-service-db/cs-db-backup-deployment.yaml
velero/schedule/common-service-db/cs-db-br-script-cm.yaml
velero/schedule/keycloak/keycloak-backup-deployment.yaml
velero/schedule/license_service_reporter/lsr-backup-deployment.yaml
velero/schedule/zen5-backup-deployment.yaml
velero/schedule/zen5-br-scripts-cm.yaml
velero/spectrum-fusion/application.yaml
velero/spectrum-fusion/cpfs-util-resources/cpfs-util-br-configmap.yaml
velero/spectrum-fusion/cpfs-util-resources/cpfs-util-clusterrole.yaml
velero/spectrum-fusion/cpfs-util-resources/cpfs-util-clusterrolebinding.yaml
velero/spectrum-fusion/cpfs-util-resources/cpfs-util-deployment.yaml
velero/spectrum-fusion/cpfs-util-resources/cpfs-util-pvc.yaml
velero/spectrum-fusion/cpfs-util-resources/cpfs-util-role.yaml
velero/spectrum-fusion/cpfs-util-resources/cpfs-util-rolebinding.yaml
velero/spectrum-fusion/cpfs-util-resources/cpfs-util-sa.yaml
velero/spectrum-fusion/cpfs-util-resources/cpfs-util-serv-tethered-role.yaml
velero/spectrum-fusion/cpfs-util-resources/cpfs-util-serv-tethered-rolebinding.yaml
velero/spectrum-fusion/policy.yaml
velero/spectrum-fusion/policy_assignment.yaml
velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml

Copy over the changes made to support Spectrum Fusion backup and restore made in PR https://github.com/IBM/ibm-common-service-operator/pull/2004.

copy over SF changes from scripts-dev

---

velero/backup/common-service/env.properties
velero/backup/common-service/label-common-service.sh

`label-common-service.sh` script
cherry pick: https://github.com/IBM/ibm-common-service-operator/pull/2005

Automatically label resources (#2005)

---

velero/backup/common-service/label-common-service.sh

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62014
Adding the info functions directly into the script instead of calling them from until.sh.

Add info functions

---

api/v3/commonservice_types.go
controllers/bootstrap/init.go
controllers/constant/odlm.go

Add StatusMonitoredServices annotations to OperandRegistry

---

cp3-networkpolicy/egress/cert-manager/bedrock-egress-ibm-cert-manager-operator.yaml
cp3-networkpolicy/egress/license-service-reporter/bedrock-egress-ibm-license-service-reporter-operator.yaml
cp3-networkpolicy/egress/license-service/bedrock-egress-ibm-licensing-operator.yaml
cp3-networkpolicy/egress/operators/bedrock-egress-cloud-native-postgresql.yaml
cp3-networkpolicy/egress/operators/bedrock-egress-egress-create-postgres-license-config.yaml
cp3-networkpolicy/egress/operators/bedrock-egress-ibm-bts-operator.yaml
cp3-networkpolicy/egress/operators/bedrock-egress-ibm-common-service-operator.yaml
cp3-networkpolicy/egress/operators/bedrock-egress-ibm-commonui-operator.yaml
cp3-networkpolicy/egress/operators/bedrock-egress-ibm-events-operator.yaml
cp3-networkpolicy/egress/operators/bedrock-egress-ibm-iam-operator.yaml
cp3-networkpolicy/egress/operators/bedrock-egress-ibm-mongodb-operator.yaml
cp3-networkpolicy/egress/operators/bedrock-egress-ibm-namespace-scope-operator.yaml
cp3-networkpolicy/egress/operators/bedrock-egress-operand-deployment-lifecycle-manager.yaml
cp3-networkpolicy/egress/operators/zen-egress-ibm-zen-operator.yaml
cp3-networkpolicy/egress/operators/zen-egress-ibm-zen-setup-job.yaml
cp3-networkpolicy/egress/services/bedrock-egress-rhbk-operator.yaml

Allow cpfs pods to establish DNS connection

---

cp3pt0-deployment/setup_tenant.sh

Currently, patching CommonService CR will not happen until CS operator pod is ready.
However, in the upgrade scenario, we expect to patch CommonService CR for topology configuration before installing CPFS v4 operator. In this case, CS operator v4 pod does not even exist when we patch CommonService CR.
Therefore, before patching CommonService CR, we will only wait for operator v4 pod to be ready if and only if its subscription exists.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63827
**Test**:
The script result after the fix
```
[INFO] CommonService CRD exist
[INFO] Creating the CommonService object:
metadata:
namespace: …
```

Wait for operator pod ready only when its subscription exists before patching CS CR

---

README.md
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
testdata/deploy/deploy.yaml
version/version.go

Bump version to 4.6.4

---

controllers/constant/odlm.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63946

Update EDB License Job image for LTSR

---

controllers/constant/constant.go

porting over https://github.com/IBM/ibm-common-service-operator/pull/2037 for SC2
@Jamstah fyi

Add BR label to cs cr by default

---

velero/backup/common-service/label-common-service.sh

Automate the lsr resources labelling for Backup and Restore
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63682
cherry-pick: https://github.com/IBM/ibm-common-service-operator/pull/2043

Add label to the license service reporter resources (#2043)

---

velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml

Updated the Spectrum Fusion recipe to include groups and condition check (hook) to backup and restore LSR operator and resources
Issue [63682](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63682)
Cherry-pick: https://github.com/IBM/ibm-common-service-operator/pull/2044

Create Spectrum Fusion recipe for License Service Reporter

---

cp3pt0-deployment/common/utils.sh

fix for unbound variable when namespace-scope cm is missing
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64024

fix for unbound variable when namespace-scope cm is missing

---

velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-multi-ns.yaml
velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-single-ns.yaml

example recipe for spectrum fusion with mongodb and zen

[4.0-4.5] spectrum fusion example recipe 

---

cp3pt0-deployment/common/utils.sh

When the operator is been installed or upgraded by OLM, script will print out additional status from subscription `.status.conditions` during each RETRY.
For debugging
- https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64017
- https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64048
When the operator is been installed or upgraded by OLM, script will print out additional status from subscription `.status.conditions`.
```console
> ./cp3pt0-deployment/setup_tenant.sh --operator-namespace cpd-control-2 --tethered-namespaces cpd-2 --license-accept -c v4.7
...
subscription.operators.coreos.com/ibm-common-service-operator created
[INFO] Waiting for operator ibm-common-service-operator CSV in namespace cpd-control-2 …
```

Add more debug info on subscription during install and upgrade

---

velero/schedule/deploy-br-resources.sh

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63828
Ability to deploy the peripheral resources required for BR of cs db, mongodb, zen 4 & 5, and keycloak. Also deploys the utility resources used in SF.

edit tmp files instead of actual so the script can be rerun multiple times

---

cp3pt0-deployment/setup_tenant.sh

The script will loop through all the namespaces from `.spec.namespaceMembers` in nss `common-service`, and overwrite `nss-managed-role` YAML file in each ns if it already exists with passed-in role when the `--with-minimal-rbac` flag is on.
Fixes: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64035

Overwrite nss managed role during upgrade

---

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml

Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64035

update events permission

---

velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-configmap.yaml
velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-pvc.yaml
velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-role.yaml
velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-rolebinding.yaml
velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-sa.yaml
velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-serv-tethered-role.yaml
velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-serv-tethered-rolebinding.yaml
velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job.yaml

Add setup tenant job files to scripts branch

add setup tenant job to scripts branch

---

cp3pt0-deployment/common/cleanup_cp2_control.sh

return error when contorl namespace not found and add yq arguments
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63694

fix contorl_ns not found

---

backup_restore_mongo.sh
velero/restore/mongoDB/mongo-restore.sh

Ensure we are using latest mongo image and updated mongorestore commands

update older mongo restore scripts

---

controllers/constant/odlm.go

[SC2] add version suffix entry for EDB 1.22

---

cp3pt0-deployment/setup_singleton.sh

update licensing catalogsource namespace when private catalogsource is enabled
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64368

update licensing catalogsource ns

---

preload_data.sh

enhancement for https://github.com/IBM/ibm-common-service-operator/pull/2090

fix $region is empty issue

---

preload_data.sh

Add a parameter that allows for re-running of the preload data script without added manual cleanup

add rerun parameter

---

preload_data.sh

debugging changes from testing https://github.com/IBM/ibm-common-service-operator/pull/2125

Rerun preload

---

cp3-networkpolicy/egress/flink/bedrock-egress-ibm-flink-operand.yaml
cp3-networkpolicy/egress/flink/bedrock-egress-ibm-flink-operator.yaml
cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operand.yaml
cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operator.yaml
cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operand.yaml
cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operator.yaml
cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operand.yaml
cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operator.yaml
cp3-networkpolicy/install_networkpolicy.sh

Cherry-pick of  https://github.com/IBM/ibm-common-service-operator/pull/2109

add networkpolicy for flink and opensearch

---

controllers/constant/odlm.go

Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/64340

Add redis operator in OperandRegistry

---

controllers/constant/odlm.go

Cherry-pick of https://github.com/IBM/ibm-common-service-operator/pull/2131

[SC2] Commonservice-db HA configuration

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manager/manager.yaml

cherry-pick of https://github.com/IBM/ibm-common-service-operator/pull/2143

add securityContext .seccompProfile field

---

cp3pt0-deployment/setup_tenant.sh

upgrade cs-operator in tethered-namespaces
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64068

upgrade cs-operator in tethered-namespaces

---

cp3pt0-deployment/setup_tenant.sh

Set packagemanifest name before use it
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64665

set  packagemanifest name

---

README.md
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

cherry-pick of https://github.com/IBM/ibm-common-service-operator/pull/2163

update cs-operator description in SC2

---

controllers/constant/odlm.go

unblock any manual testing of newer keycloak versions

added opreg entry for dev test new keycloak

---

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64686

add permissions for zenextension finalizer

---

common/scripts/lint_go.sh
controllers/constant/odlm.go

[SC2] bump keycloak to 24 and add fallback channel 22

---

controllers/constant/odlm.go

Missing operandconfig to create EDB License Job for EDB 1.22 from PR https://github.com/IBM/ibm-common-service-operator/pull/2112

[CD] add EDB License Job for entry EDB 1.22

---

controllers/constant/odlm.go

cherry-pick of https://github.com/IBM/ibm-common-service-operator/pull/2172

[SC2] add EDB License Job for entry EDB 1.22

---

controllers/constant/cloudNativePostgresql.go
controllers/constant/odlm.go

Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62138

Bump EDB used by IM to stable-v1.22 channel

---

go.mod
go.sum

[CD] update odlm package version to get latest CRD version with channel fallback

---

hack/keycloak-themes/theme/cloudpak/login/resources/css/styles470.css

styling update for keycloak24

---

preload_data.sh

see https://github.com/IBM/ibm-common-service-operator/pull/2187
Fixes #

cherrypick 64765

---

controllers/constant/odlm.go

add new entry for BTS in operandconfig

[CD] add BTS with version in operandconfig

---

README.md
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
testdata/deploy/deploy.yaml
version/version.go

bump up version to 4.6.7

---

controllers/constant/odlm.go

add new entry for bts in opconfig

[SC2] Add new entry for BTS with version in operandconfig

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
hack/keycloak-themes/README.md
hack/keycloak-themes/theme/cloudpak/login/resources/css/styles467.css
hack/keycloak-themes/theme/cloudpak/login/theme.properties
testdata/deploy/deploy.yaml

updated theming for rhbk24

---

controllers/bootstrap/init.go
controllers/common/util.go

[SC2] Use Unstructured obj to copy CR to other ns

---

controllers/constant/odlm.go

Bump Keycloak to 24 for SC2 stream

---

hack/keycloak-themes/theme/cloudpak/login/resources/css/styles467.css

Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64716

keycloak styling updates

---

hack/keycloak-themes/theme/cloudpak/login/resources/css/styles467.css

Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64716

keyckoak theme updates

---

controllers/constant/odlm.go

Fix operandconfig format error in https://github.com/IBM/ibm-common-service-operator/pull/2212

Fix format error

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
hack/keycloak-themes/README.md
hack/keycloak-themes/theme/cloudpak/login/resources/css/styles4100.css
hack/keycloak-themes/theme/cloudpak/login/theme.properties
testdata/deploy/deploy.yaml

Fixes #
fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64716

keycloak theme updates for 4.10

---

controllers/constant/odlm.go

cherry-pick of https://github.com/IBM/ibm-common-service-operator/pull/2212

[CD] apply customized user-profile for keycloak-24 

---

controllers/constant/odlm.go

[CD] Add new entry at the end of array to bypass ODLM limitation on object update

---

velero/backup/mongoDB/mongo-backup.sh
velero/restore/mongoDB/mongo-restore.sh
velero/restore/mongoDB/mongodbrestore.yaml
velero/schedule/mongodb-backup-deployment.yaml

Ensure that with more restrictive SCC environments the BR resources have appropriate access to fulfill their designated tasks.
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63657

add service account to mongo br resources

---

controllers/constant/odlm.go

Cherry pick: https://github.com/IBM/ibm-common-service-operator/pull/2181

Add fallback channels for EDB operator 

---

controllers/constant/odlm.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64802

[4.10] support instana_user to connect to db

---

controllers/constant/odlm.go
controllers/rules/rules.go
controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go
controllers/size/starterset_amd64.go
controllers/size/starterset_ppc64le.go
controllers/size/starterset_s390x.go
go.mod
go.sum

Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64888
Todo: Update the [module version for ODLM](https://github.com/IBM/ibm-common-service-operator/blob/master/go.mod#L11) after ODLM's change is merged

Add optional fields for Keycloak CR

---

controllers/size/large_amd64.go
controllers/size/large_ppc64le.go
controllers/size/large_s390x.go
controllers/size/medium_amd64.go
controllers/size/medium_ppc64le.go
controllers/size/medium_s390x.go
controllers/size/small_amd64.go
controllers/size/small_ppc64le.go
controllers/size/small_s390x.go
controllers/size/starterset_amd64.go
controllers/size/starterset_ppc64le.go
controllers/size/starterset_s390x.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64521

Update size limit for shared EDB

---

controllers/constant/odlm.go

Update ui operator channel to 4.6

---

cp3pt0-deployment/common/utils.sh
cp3pt0-deployment/setup_singleton.sh

waiting for licensing instance deployment before migrating licensing

waiting for licensing instance deployment

---

velero/backup/cert-manager/label-cert-manager.sh
velero/backup/common-service/env.properties
velero/backup/common-service/label-common-service.sh
velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns-multi-zen.yaml

**What this PR does / why we need it**: Sync changes made to scripts-dev branch to the scripts branch.
PRs https://github.com/IBM/ibm-common-service-operator/pull/2209, https://github.com/IBM/ibm-common-service-operator/pull/2208, https://github.com/IBM/ibm-common-service-operator/pull/2180
Fixes #

sync scripts branch with scripts-dev

---

api/v3/commonservice_types.go

Fixes # https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/28858

[SC2] Make spec field optional in the serviceConfig section in CS CR

---

api/v3/commonservice_types.go

Fixes # https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/28858

make spec field optional in the serviceConfig section in CS CR

---

controllers/constant/odlm.go

[CD] add opreq-control label for EDB License Job

---

cp3-networkpolicy/egress/flink/bedrock-egress-ibm-flink-operand.yaml
cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operand.yaml
cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operator.yaml
cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operand.yaml
cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operator.yaml
cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operand.yaml
cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operator.yaml

enhancement for cp4ba issue
ref:
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63821#issuecomment-83071378
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63821#issuecomment-83829378

update flink and opensearch networkpolicy port

---

controllers/constant/cloudNativePostgresql.go

Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64969

Pick up EDB 1.22.7 images for CS 4.10

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/bootstrap/init.go
controllers/constant/constant.go
main.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64483
Cherry-pick: https://github.com/IBM/ibm-common-service-operator/pull/2267

Clean up v3 leftover resources (#2267)

---

controllers/constant/odlm.go

Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65218

Fix meta api namespace typo

---

turbonomic/README.md
turbonomic/operands/orm-common-web-ui.yaml
turbonomic/operators/orm-ibm-commonui-operator.yaml

UI ORMs
Fixes #
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65176

common-web-ui ORMs

---

README.md
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
testdata/deploy/deploy.yaml
version/version.go

Bump up version to 4.6.9

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml

Related issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65262

remove EDB configmap cluster permission

---

controllers/constant/odlm.go

cherry-pick from: https://github.com/IBM/ibm-common-service-operator/pull/2265

[SC2] new entry for event-v5.1

---

velero/backup/common-service/label-common-service.sh
velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-multi-ns.yaml
velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-single-ns.yaml
velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns-multi-zen.yaml
velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml

Cherry-pick: https://github.com/IBM/ibm-common-service-operator/pull/2311
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65357

Refresh Recipe by removing setup tenant job

---

controllers/constant/odlm.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65556

Bump Common UI version to 4.7

---

velero/schedule/common-service-db/cs-db-br-script-cm.yaml

update name of external db config cm

---

helm/templates/cr.yaml
helm/templates/operator-deployment.yaml
helm/values.yaml

fixed incorrect operator image name

added CommonService CR to helm chart

---

helm-cluster-scoped/values.yaml
helm/templates/cr.yaml
helm/templates/operator-deployment.yaml
helm/templates/rbac.yaml
helm/values.yaml

comment out values for transition to global values file

---

OWNERS

Update OWNERS with my Id

---

controllers/constant/odlm.go

Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65708
Cherry pick: https://github.com/IBM/ibm-common-service-operator/pull/2345

Enable granting permission for token exchange (#2345)

---

controllers/constant/odlm.go

Result is based on performance testing

added new postgres parameter max_slot_wal_keep_size CD

---

helm-cluster-scoped/templates/cluster-rbac.yaml
helm-cluster-scoped/templates/crd.yaml
helm-cluster-scoped/values.yaml
helm/templates/cr.yaml
helm/templates/operator-deployment.yaml
helm/templates/rbac.yaml
helm/values.yaml

Add label to helm generated resources and cpfs object

Add label to helm generated resources

---

preload_data.sh

verify MongoDB statefulset status instead of pod before scaling back MongoDB operator
Eehancement for #  [#65937](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65937)

check mongo statefulset

---

controllers/constant/odlm.go

Cherry pick: https://github.com/IBM/ibm-common-service-operator/pull/2337
Fixes #
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65326#issuecomment-101278516
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65677

Enhance Keycloak 26 pod scheduling

---

controllers/constant/odlm.go

result is based on performance testing

added new postgres parameter max_slot_wal_keep_size SC2

---

bedrock-migration/Chart.yaml
bedrock-migration/templates/bedrock-migration-job.yaml
bedrock-migration/values.yaml

fixed incorrect image registry namespace from operator namespace to operand namespace

updated migration chart to version 0.0.0

---

internal/controller/operandconfig.go
internal/controller/rules/resource_comparison.go

[CD] Add shared_buffers to comparable keys and normalize resource quantity formats (#2414)

---

velero/schedule/schedule-common-services.yaml

**What this PR does / why we need it**: otherwise velero backup will not account for resources labeled "nss"
Fixes #

add nss field to schedule

---

internal/controller/commonservice_controller.go
internal/controller/constant/constant.go

Cherry-pick of #2429 
Fixes https://github.com/IBM/ibm-common-service-operator/pull/2429

Refactor reconciliation logic for operand registry and add support for ODLM managed subscriptions triggering reconciliation

---

helm-cluster-scoped/templates/cluster-rbac.yaml
helm-cluster-scoped/values.yaml

to allow for multiple instances of the operator

appended operator ns to cluster rbac names helm chart

---

helm/templates/cr.yaml
helm/templates/operator-deployment.yaml
helm/templates/rbac.yaml
helm/values.yaml

to allow for generic configuration of helm templates' `.metadata.labels`

added new labels variable to values

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controller/bootstrap/init.go
internal/controller/common/util.go

cherry pick for https://github.com/IBM/ibm-common-service-operator/pull/2446
for https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66196

[SC2] Enhancement on EnsureLabels function

---

bedrock-migration/templates/bedrock-migration-job.yaml
bedrock-migration/templates/rbac.yaml

**What this PR does / why we need it**: Further testing revealed additional problems with migration chart.

add cpfs.imagePullPrefix, remove nss roles

---

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml

Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66264

Add new permissions required for Postgres 1.25.1

---

preload_data.sh

consolidate the [function deletemongocopy](https://github.com/IBM/ibm-common-service-operator/blob/6fc7f09e4a30ef041e1a5aa40644194ceff691c4/preload_data.sh#L2360) and [function cleanup](https://github.com/IBM/ibm-common-service-operator/blob/6fc7f09e4a30ef041e1a5aa40644194ceff691c4/preload_data.sh#L726) in to one function
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65999

preload-data cleanup enhancement

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manager/manager.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
internal/controller/common/util.go

add cpfs util image in related_image
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66202

[cd] add cpfs util image in related_image

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manager/manager.yaml
internal/controller/common/util.go

add cpfs util image in related_image
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66202

[SC2] add cpfs util image in related_image

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65334

[SC2] Add must gather image in relatedImage for Catalog based mirroring

---

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml

Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65334

[CD] Add new images into relatedImages section for catalog based mirror

---

internal/controller/constant/odlm.go

[CD] rename Keycloak conversion resources for pre-upgrade process (#2475)

---

internal/controller/constant/odlm.go

[CD] add labelSelector for common-service-db in topology constraints

---

internal/controller/bootstrap/init.go

[SC2] add handling for no-op mode in operator status checks

---

internal/controller/constant/cloudNativePostgresql.go

Update EDB operand images
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66477

Update EDB operand images

---

internal/controller/constant/cloudNativePostgresql.go

Update EDB operand images
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66477

[CD] Update EDB operand images

---

Makefile
README.md
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manager/kustomization.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
testdata/deploy/deploy.yaml
version/version.go

**What this PR does / why we need it**: Version bump for cs 4.6.14

Bump cs operator to 4.6.14

---

internal/controller/bootstrap/init.go
internal/controller/constant/certmanager.go

updated manage-cert-rotation label values

---

velero/schedule/zen5-br-scripts-cm.yaml

**What this PR does / why we need it**: follow up to https://github.com/IBM/ibm-common-service-operator/pull/2505
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66587

update counter for iam-config-job as well

---

api/v3/commonservice_types.go
config/crd/bases/operator.ibm.com_commonservices.yaml
internal/controller/constant/autoScaleConfig.go
internal/controller/render_template.go

controller handling of t-shirt sizing replicas still to be implemented, but this unblocks certain testing

added configuration to enable/disable HPA

---

helm/templates/operator-deployment.yaml
helm/values.yaml

**What this PR does / why we need it**: Make value configuration more like our other configurable values
Fixes #

change size value location

---

bedrock-migration/templates/bedrock-migration-job.yaml
bedrock-migration/templates/rbac.yaml

Fixes # https://github.ibm.com/PrivateCloud-analytics/Zen/issues/41456

bump up hook weight

---

helm/templates/operator-deployment.yaml
internal/controller/bootstrap/init.go

Add default value `false` to `license.accept` in cs template
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66458

Add default value 'false'

---

internal/controller/constant/odlm.go

cherry pick for: https://github.com/IBM/ibm-common-service-operator/pull/2521

[SC2] add an new entry for event 5.2

---

internal/controller/constant/odlm.go

cherry-pick of https://github.com/IBM/ibm-common-service-operator/pull/2518

Remove unused database

---

cp3-networkpolicy/egress/flink/bedrock-egress-ibm-flink-operand.yaml
cp3-networkpolicy/egress/flink/bedrock-egress-ibm-flink-operator.yaml
cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operand.yaml
cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operator.yaml
cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operand.yaml
cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operator.yaml
cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-elasticsearch-operand.yaml
cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operand.yaml
cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operator.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66426

update network policy for opensearch/elasticsearch

---

internal/controller/constant/odlm.go

Updated IM operator and Config-UI version for release 4.14

Bump up IM and CommonUI version for 4.14

---

must-gather/cs_im_mustgather.sh

Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63692

cs im must-gather script added

---

velero/schedule/common-service-db/cs-db-br-script-cm-4.6.10.4.11.yaml
velero/schedule/common-service-db/cs-db-br-script-cm.yaml

remove backup and restore unused database
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65017

remove backup and restore unused database

---

internal/controller/commonservice_controller.go

Fix the error error logging with correct error variable

Fix error logging in ReconcileMasterCR to use correct error variable

---

velero/backup/common-service/label-common-service.sh

Fix a typo issue in labeling default catalogsource
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67316

typo in labeling script

---

cs-onprem-tenant-config.sh

Removed verify=False for internal API calls and provided appropriate certs 
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66845
Dependent internal PR - https://github.ibm.com/IBMPrivateCloud/iam-custom-hostname/pull/90 
Unit test - Attached test results to the above PR - https://github.ibm.com/IBMPrivateCloud/iam-custom-hostname/pull/90#issuecomment-129302935

Enable SSL verification

---

Makefile
README.md
bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manager/kustomization.yaml
config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
testdata/deploy/deploy.yaml
version/version.go

Bump CS version to 4.6.19
