pkg/bootstrap/constant.go
This PR is to update `operandconfig` instance, remove `navconfiguration: {}` from ibm-commonui.
=> Update operandconfig instance

Makefile, pkg/bootstrap/constant.go
There are 7 operators still don't have `dev` channel
```
ibm-helm-api-operator-app
ibm-metering-operator-app
ibm-mongodb-operator-app
ibm-cert-manager-operator
ibm-catalog-ui-operator-app
ibm-helm-repo-operator-app
ibm-platform-api-operator-app
```
=> Update operator channel to dev

pkg/bootstrap/constant.go
This PR makes adding bindinfo and dependency request for IBM Licensing as default
=> add operandbindinfo, and dependency request for IBM Licensing

pkg/bootstrap/init.go
if a resource already exists, then update it to meet the new one.
=> fix updating resource issue when it already exists

build/resources/extra/example-sa.yaml, build/resources/extra/secretshare_deploy.yaml
Added a yaml file that should be deployed in ibm-common-services to perform secret sharing for backward compatibility with 3.2.4.
This will be adjusted for the proper image registry - the current one is temmporary
=> added yaml file for deployment secretshare_deploy.yaml

build/resources/cs-operandconfig.yaml, build/resources/cs-operandregistry.yaml, docs/cloudpak-integration.md
For development and testing purposes, ibm common service operator will deploy two pairs of the `OperandRegistry` and `OperandConfig`.
`common-service` uses the stable channel.
`common-service-dev` uses the dev channel.
=> creating a separate registry and config for the dev channel

build/resources/extra/secretshare_deploy.yaml
Configmap ibm-cloud-info was added by accident or mistake. There
is no such configmap Common Services 3.2.4 in kube-system namespace.
Remove it from the list.
=> Remove ibm-cloud-info cm from SecretShare CR

build/resources/extra/secretshare_deploy.yaml
Got the message from @liqlin2015 that the `icp-management-ingress-tls-secret` does not need to be copied to `kube-system`.
Sync the secretshare PR: https://github.ibm.com/IBMPrivateCloud/secretshare/pull/2
/cc @mikekaczmarski @liqlin2015
=> remove the unnecessary copies

deploy/role_binding.yaml
Fix bundle error
```
The ClusterRoleBinding "ibm-common-service-operator" is invalid: subjects[0].namespace: Required value
[CMD END : 10:23:05 ] ./tests/test-01/pre-install/pre-install.sh
REPORT:stable/ibm-common-service-operator-case-bundle:PRE-INSTALL:stable/ibm-common-service-operator-case-bundle/tests/test-01/pre-install/pre-install.sh:completed with rc=1
```
=> Fix case bundle issue

deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
Secret ibmcloud-cluster-ca-cert will be copied to kube-public
namespace. But the required RBAC is missing. Add the RBAC so any
k8s user can access the info.
=> Add required RBAC for ibmcloud-cluster-ca-cert

cmd/manager/main.go, pkg/check/check.go
Local test, if secret tiller-secret existing, and iam related annotation existing, exit with code 1.
```console
✗ make run
....... Start Operator locally with go run ......
WATCH_NAMESPACE=ibm-common-services go run ./cmd/manager/main.go
I0525 22:25:02.360505   98988 main.go:49] Operator Version: 3.4.1
I0525 22:25:02.360632   98988 main.go:50] Go Version: go1.14.3
I0525 22:25:02.360636   98988 main.go:51] Go OS/Arch: darwin/amd64
I0525 22:25:02.360640   98988 main.go:52] Version of operator-sdk: v0.16.0
I0525 22:25:06.208490   98988 main.go:115] Registering Components.
I0525 22:25:06.208567   98988 main.go:123] check Helm based IBM Common Services installation
E0525 22:25:06.455382   98988 main.go:130] The Helm based IBM Common Services must be uninstalled before performing operator based …
```
=> Check the old common services if installed

deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
Adds required secrets and configmap to support IBM MCM in CP4MCM
Roadmap issue 38189
=> Update SecretShare resource to support IBM MCM

cmd/manager/main.go, pkg/check/check_iam.go
Check 8 Deployments for IAM
Check 3 Jobs for IAM
Until all the deployments ready and all the Jobs succeed completed, add data `iamstatus: Ready` into configmap `kube-public/ibm-common-services-status`
```go
DeployNames = []string{"ibm-iam-operator", "auth-idp", "auth-pap", "auth-pdp", "configmap-watcher", "iam-policy-controller", "oidcclient-watcher", "secret-watcher"}
JobNames    = []string{"iam-onboarding", "security-onboarding", "oidc-client-registration"}
```
=> Check iam status

deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
Seems on Power node, it requires more CPU than x86.
=> increase ansible operator cpu/memorty

Makefile, README.md, deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml, deploy/olm-catalog/ibm-common-service-operator/3.4.2/ibm-common-service-operator.v3.4.2.clusterserviceversion.yaml, deploy/olm-catalog/ibm-common-service-operator/3.4.2/operator.ibm.com_commonservices_crd.yaml, deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml, version/version.go
Update version to 3.4.2
The beta channel uses 3.4.1
The dev channel uses 3.4.2
Image digest:
- common-service-operator: https://quay.io/repository/opencloudio/common-service-operator/manifest/sha256:50826858364c41a308fa0259baa87b70431249ae8b2bad1664edd0b2d26ca0f9
- ibm-cs-webhook: https://quay.io/repository/opencloudio/ibm-cs-webhook/manifest/sha256:3e03c060166bb5df5afa206e7d32b664243d16931dea0545b01d06909bb60e96
- ibm-secretshare-operator: https://quay.io/repository/opencloudio/ibm-secretshare-operator/manifest/sha256:e6587d27db30e269428e85c2a7a33892051248ffa18a73c7c750f6577a8fc484
=> bump version to 3.4.2 and push 3.4.1 to the beta channel

Makefile, deploy/olm-catalog/ibm-common-service-operator/3.4.2/ibm-common-service-operator.v3.4.2.clusterserviceversion.yaml, deploy/olm-catalog/ibm-common-service-operator/3.4.3/ibm-common-service-operator.v3.4.3.clusterserviceversion.yaml, deploy/olm-catalog/ibm-common-service-operator/3.4.3/operator.ibm.com_commonservices_crd.yaml, deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml, version/version.go
Push 3.4.3 to dev, the content is similar to the original 3.4.2.
Push 3.4.2 to beta, using the image digest used in 3.4.1 
Push 3.4.1 to stable-v1, using the stable-v1 channel to replace the beta channel
**Note:** We need to push the operator bundle into quay.io after other common service operators.
=> push 3.4.3 to dev, 3.4.2 to beta and 3.4.1 to stable-v1

Makefile, cmd/manager/main.go, pkg/bootstrap/init.go
Remove original hard code logic
Current logic:
1. Get ODLM subscription, if don't exist, exit delete method, if existing, continue step 2
2. Get the ODLM CSV name from the subscription of step 1 and delete the CSV
3. Delete ODLM subscription
=> Enhance logic for delete old ODLM

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
This pr picks https://github.com/IBM/ibm-common-service-operator/pull/137 and https://github.com/IBM/ibm-common-service-operator/pull/129 to the IBM common service operator CSV 3.5.0
=> pick changes for common service 3.5.0

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Update secretshare operator and cs webhook to ibm common service operator. 
I bump the annotation.version of ibm-secretshare-operator to '6', which will overwrite the old version during the upgrade.
I didn't change the version of cs-webhook controller because considering it is a temperate workaround, users won't get the updated version during upgrade.
=> update secretshare operator and cs webhook

Makefile, controllers/commonservice_controller.go
If the user doesn't set `size`, the common service operator can merge the sizing configuration anyway
=> supports the user doesn't set the sizing template in the CR

Dockerfile, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
- Using go 1.14.6 to solve vulnerabilities CVE-2020-15586 and CVE-2020-14039
- Using ubi as the base image
=> use ubi as the base image

controllers/size/small_amd64.go
Since`auditLogging` is the default CR for the audit-logging operator, I replace the `commonAudit`  to `auditLogging` according to information from @hbradfield.
/cc @hbradfield
=> replace the CR used for the audit-logging operator

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml, deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml, deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
Discussed with the CICD squad, no matter users use the `dev` and `beta` channel of the common service operator, the ibm-common-service-operator will generate the OperandRegistry with the `beta` channel.
/assign @Daniel-Fan
=> bump CSV 3.5.0 to the beta channel

controllers/size/medium_amd64.go, controllers/size/small_amd64.go
keep the higher value unchanged. Here is the new table of summary:
```
Service Name                        | CPU Limits            | Memory Limits            | MAX CPU Usage w/o limits   | Max Memory Usage w/o limits  
certManager/certManagerCAInjector   | 35m                   | 290Mi -> 350Mi           | 20m                        | 316Mi
certManager/certManagerController   | 60m -> 80m            | 230Mi -> 400Mi           | 31m -> 60m                 | 386Mi -> 142Mi
pap/papService                      | 100m                  | 330Mi -> 600Mi           | 91m -> 43m                 | 578Mi -> 200Mi 
metering/reader/rdr                 | 30m -> 50m            | 200Mi -> 250Mi           | 40m  -> 33m                | 231Mi -> 143Mi
IBMLicensing                        | 200m -> 220m …
```
=> update sizing based new unlimited usage test

controllers/size/small_amd64.go
There are some limit values which are overestimated because of the inaccurate data generated by test.
Revert those inaccurate limits back to the original values.
/assign @horis233 Could you please review it? Thank you!
=> Removing the overestimated values in small size

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml, deploy/olm-catalog/ibm-common-service-operator/3.5.1/ibm-common-service-operator.v3.5.1.clusterserviceversion.yaml
remove metering dependency by deleting operandRequest from Licensing Operator templates and force custom resource change for Licensing to not use metering from deleted dependency
=> update operand config for Licensing Operator

deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml
Events Operator should be added to common services 3.6, not
3.5.5.  Removing
https://github.com/IBM/ibm-common-service-operator/issues/254
Signed-off-by: Emma Humber <emma.humber@uk.ibm.com>
=> Events Operator should be added to common services 3.6, not 3.5.5

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml, deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
We moved the navconfiguration CRD as being owned by the commonui operator. We need to make sure it is installed with the operand request for commonui.
=> Adding navconfiguration to operandrequess

Makefile, controllers/bootstrap/init.go, controllers/constant/namespace.go
Upgrade from version 3.4.x, if we don't create namespace-scope configmap, some operators(depend on this configmap) will not upgrade.
=> Fix upgrade backward compatible issue

controllers/size/large_amd64.go, controllers/size/large_ppc64le.go, controllers/size/large_s390x.go, controllers/size/medium_amd64.go, controllers/size/medium_ppc64le.go, controllers/size/medium_s390x.go, controllers/size/small_amd64.go, controllers/size/small_ppc64le.go, controllers/size/small_s390x.go
IBMLicenseServiceReporter is a CR that wouldn't be created by default. The memory increase wouldn't impact the release test.
=> update the memory limit for receiverContainer

controllers/commonservice_controller.go, controllers/rules/rules.go
1. Initialize resources only happens when reconciling master CR.
2. Apply different rules for the parameters within the Rules and without Rules
**TODO:** Implement the sizing comparison functions.
=> Support reconciling the common service CR from other namespaces

controllers/constant/webhook.go
fix issue #345 
verb `get` is enough for webhook to fetch configmap in `kube-public` ns
=> add permission for webhook to fetch configmap

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, common/scripts/lint-csv.sh, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml, controllers/bootstrap/init.go, controllers/common/util.go, testdata/deploy/deploy.yaml
Update digest for the cs webhook and secretshare.
Only generates operandrequest webhook when there is common service mapping configmap.
=> add csWebhookOperatorEnableOpreqWebhook into csv

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
1. Remove the `replace` section as it is the origin of `v3` channel.
2. Keep `olm.skipRange: '>=3.3.0 <3.7.0'` as it supports upgrading from the version smaller than `3.7.0`.
3. ~~Update the channel to `v3` for the subscription and the operator in the `opencloud-operators` CatalogSource.~~
Currently, we did not update the channel of subscription and operator in `OperandRegistry` in `beta` stage, leaving the task to CICD pipeline.
4. Did not update the version in annotation since there is no release published yet.
=> switch 3.7 to v3 channel

common/scripts/migrate-to-ibm-catalog.sh, common/scripts/utils.sh
To use the script in beta stage, we need to replace `ibm-operator-catalog` by dev catalogsource `opencloud-operators`
```
oc patch sub ${cssub} -n ${ns} --type="json" -p '[{"op": "replace", "path":"/spec/source", "value":"ibm-operator-catalog"}]' 2> /dev/null
```
=> add script for moving to ibm-catalogsource

controllers/operandconfig.go
iterate services in the newconfig instead of services in the common service CR
fix #432
=> fix: Keep both storageclass and size info

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
to expose zen-serviceid-apikey-secret for onboarding users from IAM to
Zen
=> updated ibm-iam-operator OperandBindInfo in CSV's OperandConfig template

.github/workflows/ocp.yaml
both
```
ref: ${{ github.event.pull_request.head.ref }}
repo: ${{ github.event.pull_request.head.repo.full_name }}
```
are necessary to check out the PR code
=> fixed error checking out code in workflow

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, common/scripts/lint-csv.sh, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml, controllers/bootstrap/init.go, controllers/common/util.go, controllers/render_template.go, testdata/deploy/deploy.yaml
What is this PR doing?
1. In CSV, Create brand new templates of `OperandConfig` and `OperandRegistry` for SaaS deployment.
2. Integrate `ControlNs` and `SaasEnable` into `bootstrap`
3. Integrate the installation flow of Namespace-scope operator into one function in order to reduce the complexity of `InitResources` function.
4. don't install `secretshare operator` in SaaS deployment https://github.com/IBM/ibm-common-service-operator/pull/446#discussion_r605361604
5. Install different `OperandConfig` and `OperandRegistry` based on SaaS or non-SaaS deployment. https://github.com/IBM/ibm-common-service-operator/pull/450#issuecomment-809105028
What is unclear?
1. the content of templates for both `OperandConfig` and `OperandRegistry`
=> Update OperandRegistry and OperandConfig for SaaS deployment

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml, controllers/bootstrap/init.go, controllers/certmanager/cert_cr.go, controllers/certmanager/certmanager.go, main.go, testdata/deploy/deploy.yaml
1. Create a separate go routine to deploy the common ca resources, running beside the cs-controller.
2. Those resources will be created in `MasterNamespace` where the default is `ibm-common-services`.
3. The routine will wait to deploy the resource until the CRDs ready which are `Issuer` and `Certificate` under `certmanager.k8s.io/v1alpha1`.
=> create issuer and certificate

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml, controllers/bootstrap/init.go, controllers/common/util.go, controllers/commonservice_controller.go, controllers/constant/constant.go, controllers/constant/namespace.go, controllers/operandconfig.go, go.mod, go.sum, main.go, testdata/deploy/deploy.yaml
1. When the `cs-mapping` ConfigMap is changed, it will reconcile the master CR, going through the steps of initializing the resource to update the scope list in NSS CR for both `common-service` and `odlm-scope` to update the scope for individual cs operator and ODLM.
2. Also `cs-operator` will validate the `cs-mapping` ConfigMap, if it is an unsupported case, the `cs-operator` will raise the error. In the future, we will handle it by validating web hook, to prohibit the invalid change to ConfigMap from the user.
3. Also `cs-operator` will filter its `cs-scope` from `cs-mapping` ConfigMap. If the triggered CR is not in the namespace of this scope. It will skip the reconciliation.
=> watching cs-maps change, validate cs-mapping and filter its cs-scope

controllers/bootstrap/init.go, controllers/constant/namespace.go
`odlm-scope-managedby-odlm` and `nss-managedby-odlm` will have the same `namespaceMember` value.
But the first one is used for extend permission on ODLM, the latter is for other individual operator's permission scope.
`odlm-scope-managedby-odlm` and `nss-managedby-odlm` should only be created when CS is deployed in Single instance case.
On SaaS or on-prem Multi Instances case, we will not have above two CRs and disable the NSS controller in ODLM to avoid the permission overlap in `control namespace`
=> Create a new NSS CR managed by ODLM

controllers/constant/odlm.go
We have two templates for SaaS and on-prem deployment respectively.
In the on-prem deployment,
1. the Single instance will deploy all resources in `masterNs`. and `ControlNs == masterNs`.
2. the multi instances case will deploy cluster scope resource like `cert-manager-operator` and `licensing-operator` in `ControlNs`.
=> deploy cluster-scope in ControlNs for on-prem multi instance case

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Not sure whether we need to update the version of replace image in 3.8 since there is a newer 3.7.2.
=> bump version for replace image

controllers/check/check_iam.go, controllers/common/util.go, main.go
Not 100 percent sure that I understand the design correctly.
Basically, I use `requested-from-namespace` (usually is cloud pak name) as the prefix of `-iamstatus`.
In this situation, one Common Service instance will have multiple namespaced cloud pak prefix `iamstatus` like `cp4i-iamstatus` and `cp4mcm-iamstatus` if the ConfigMap looks like this
```
apiVersion: v1
metadata:
name: common-service-maps
namespace: kube-public
data: 
- requested-from-namespace:
- cp4i
- cp4mcm
map-to-common-service-namespace: common-service
```
Also there is a overall status called `iamstatus` as our previous release, it is only `Ready` when all other namespaced cloud pak prefix `-iamstatus` are `Ready` to keep the …
=> add iamstatus with cloud pak prefix

controllers/bootstrap/init.go, controllers/common/util.go
Since MongoDB requires StorageClass and many other common services require MongoDB, so we add storageClass pre-check before installation.
logs with 2 StorageClass:
logs with No StorageClass (report error & stop deployment
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44307
=> Add pre-check of whether storageClass existing

controllers/commonservice_controller.go, controllers/operandconfig.go, controllers/render_template.go
Each `ibm-common-service-operator` still need to watch all CommonService CRs in the cluster, but we need to split the logic of hardware profile merging into two parts.
1. For namespaced scope operator, we will only combine their resource values from the CRs in namespaced scope like what we do before.
2. For cluster scope operator, each cs-operator will fetch their values from all CRs across the cluster, finding out the max value and applying it to `OperandConfig` of its own namespaced ODLM. On the other word, all the hardware profiles for cluster scope resources are the same in every `OperandConfig` of ODLMs.
=> reconcile cluster scope resource

config/rbac/service_account.yaml
we removed `ibm-common-service-operator/deploy/` in after v3.6.x. Thus, we need to relocate service_account.yaml under `config`.
=> Add service_account.yaml under config

controllers/bootstrap/init.go, controllers/common/util.go, controllers/constant/commonservice.go, controllers/constant/constant.go, controllers/constant/odlm.go, main.go
When cloudpak operator is installed in the approval mode, then the common service operator in master namespace will be deployed in the manual approval mode.
=> feat: bootstrap cs operator in the manual approval mode

controllers/operandconfig.go, controllers/render_template.go
We will always return the size template in function `applySizeTemplate()`.
Therefore, when it is out of scope, we should remove those namespace-scoped operator from template, and then return it as the `newConfigs`
=> filter the template size when the CR is out of scope

controllers/bootstrap/init.go, controllers/certmanager/certmanager.go, controllers/namespacescope/namespacescope.go, go.mod, go.sum, main.go
It creates an additional go routine to sync up the `common-service` and `nss-odlm-scope` NSS CR.
Currently, we use `common-service` NSS CR to control the namespace scope for individual common service operator and use `nss-odlm-scope` to control the namespace scope for ODLM.
When user manually extend their operator's permission to other namespaces, they will be instructed about adding namespace in `common-service` NSS CR.
Therefore, we need to sync up the namespace member in both `common-service` and `nss-odlm-scope` NSS CR, to ensure that ODLM's permission is be extended as well.
The code part is finished, need to do some test before merging it.
=> [WIP] sync up NSS CR for common service and ODLM

controllers/check/check_iam.go, controllers/common/util.go, controllers/constant/constant.go
Previously, we fetch the namespaces from CS Mapping, but it will contain some namespaces that have not been created.
Currently, we choose to fetch the namespaces from `namespace-scope` ConfigMap whose namespaces have been validated by namespace-scope operator.
Fyre cluster is down, so I haven't tested the functionality yet.
=> fetch the namespace from namespace-scope ConfigMap for iam status

controllers/certmanager/certmanager.go
Currently, after we deploy the cs-operator, it will start to wait for the CRD of cert manager ready, it will cause additional resource waste.
```
I0603 00:34:16.942019       1 init.go:898] waiting for resource ready with kind: Issuer, apiGroupVersion: certmanager.k8s.io/v1alpha1
I0603 00:34:24.988918       1 request.go:621] Throttling request took 1.044129631s, request: GET:https://172.30.0.1:443/apis/security.internal.openshift.io/v1?timeout=32s
I0603 00:34:25.988963       1 request.go:621] Throttling request took 2.044091708s, request: GET:https://172.30.0.1:443/apis/controlplane.operator.openshift.io/v1alpha1?timeout=32s
I0603 00:34:26.940671       1 init.go:898] waiting for resource ready with kind: Issuer, apiGroupVersion: certmanager.k8s.io/v1alpha1
I0603 00:34:34.988838       1 …
```
=> optimize the wait process  for deploying cert CR

controllers/check/check_iam.go, controllers/common/util.go
To adopt the all namespace mode, the NSS ConfigMap will always be in `MasterNs` instead of `OperatorNs`
=> find nssConfigMap in masterNs instead of operatorNs

controllers/operandconfig.go
`newConfigForOperator` and `opService` may be `nil`, not `map[string]interface{}`
=> handle interface {} is nil

README.md, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, common/scripts/multiarch_image.sh, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml, controllers/certmanager/cert_cr.go, controllers/constant/secretshare.go, controllers/constant/webhook.go, testdata/deploy/deploy.yaml, version/version.go
Master branch will be used for the future pipeline going forward.
We can put future dev code into these builds as long as your operator is set to a higher version than any of the versions in `eus`, `efix`, and `cd` branches.
=> bump master branch to 4.0.0 for future release

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/common/util.go, controllers/constant/constant.go, testdata/deploy/role.yaml
The dev build with `opencloud-operator` CatalogSource has the highest priority.
When there is no dev build in the cluster, it will follow the previous strategy that we will choose `ibm-operator-catalog` if it exists.
But there is a permission escalation happening, `cs-operator` requires the cluster permission for getting the CatalogSource from `openshift-marketplace` namespace in order to check the image used by `opencloud-operator`. The `packageManifest` of `cs-operator` in its own namespace is not really helpful.
=> prioritize the dev catalogsource

controllers/bootstrap/init.go
Avoid the situation that the user does not wanna upgrade when there is a newer version coming, but cs-operator continue waiting for others' upgrading because the currentCSV is larger than installedCSV.
=> remove checking installedcsv with currentcsv for manual approval strategy

controllers/bootstrap/init.go, controllers/constant/odlm.go
1. On-Prem Multi instances case:
```
- name: ibm-iam-operator
spec:
operandRequest: {}
secretwatcher: {}
policycontroller: {}
policydecision: {}
operandBindInfo:
bindings:
protected-zen-serviceid:
secret: zen-serviceid-apikey-secret
oidcclientwatcher: {}
authentication:
config:
onPremMultipleDeploy: true
```
2. On-Prem Single instance case:
```
- name: ibm-iam-operator
spec:
operandRequest: {}
secretwatcher: {}
policycontroller: {}
policydecision: {}
operandBindInfo:
bindings:
protected-zen-serviceid:
secret: zen-serviceid-apikey-secret
oidcclientwatcher: {}
authentication:
config:
onPremMultipleDeploy: false
```
3. SaaS case:
```
- name: ibm-iam-operator
spec:
operandRequest: {}
secretwatcher: {}
policycontroller: {}
policydecision: {}
operandBindInfo:
bindings:
protected-zen-serviceid: …
```
=> config IAM with OnPremMultiEnable

common/scripts/upgrade_to_continuous_delivery_airgap.sh
Currently when we upgrade from CS 3.6 or below to CS 3.8, the version 3.10 cert-manager-operator in CS 3.8 will use the version 3.9 cert-manager-operator in CS 3.7 as a bridge, it is not a direct upgrade.
In AirGap situation, it will cause the `ImagePullBackOff` error for version 3.9 cert-manager-operator, because we did not include the images about CS 3.7 for CS 3.8 bundle.
Therefore, we will delete the cert-manager-operator before the upgrade, and ODLM will re-install the version 3.10 cert-manager-operator directly after the upgrade.
=> uninstall cert-manager after channel switch

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manager/manager.yaml
CS operator expects its container can be ready within 1 second, but it can’t in the machine with bad performance.
We need to make to probe more loose to prevent this error
=> Make probe more loose

controllers/constant/odlm.go
When on SaaS, use Verbose log level for License Service.
=> Change Licensing logLevel in saas

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manager/manager.yaml, main.go
The default Readiness probe endpoint name is `readyz` and default Liveness probe endpoint name is "healthz"
https://github.com/kubernetes-sigs/controller-runtime/blob/release-0.6/pkg/manager/manager.go#L187
Also try to align it with the example in kubebuilder
```
// +kubebuilder:scaffold:builder
if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {
setupLog.Error(err, "unable to set up health check")
os.Exit(1)
}
if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {
setupLog.Error(err, "unable to set up ready check")
os.Exit(1)
}
```
https://book.kubebuilder.io/cronjob-tutorial/empty-main.html
=> use default path for two probes

Makefile
If you have operator-sdk v1 or yq version 3 installed, it will still download newer version of tools to make it running.
=> require the operator-sdk v1 and yq version 4

controllers/constant/odlm.go, controllers/rules/rules.go, controllers/size/large_amd64.go, controllers/size/large_ppc64le.go, controllers/size/large_s390x.go, controllers/size/medium_amd64.go, controllers/size/medium_ppc64le.go, controllers/size/medium_s390x.go, controllers/size/small_amd64.go, controllers/size/small_ppc64le.go, controllers/size/small_s390x.go, controllers/size/starterset_amd64.go, controllers/size/starterset_ppc64le.go, controllers/size/starterset_s390x.go
the cs-operator should be able to compare `small`, `medium` and `large` string in `api-catalog` profile
=> onboard and add size comparison for api-catalog

controllers/rules/resource_comparison.go
When there are slices defined in OperandConfig, we will simply compare those values to check whether they are equal, but we will **not apply any changes insides the slices** for now.
This is for api-catalog boarding task
=> add comparison for slices

controllers/constant/certmanager.go, controllers/goroutines/variables.go
can produce latest-validated build earlier. Will add back in once
cert-manager can handle mixing v1 and v1alpha1 certs
This reverts commit b032cf32b85af87a1d9472778b7ce640b5ca0f91.
=> Revert "update certmanager APIGroup version to v1 (#637)" so that CICD

controllers/constant/odlm.go
`beta.kubernetes.io/arch` -> `kubernetes.io/arch`
=> remove deprecated beta.kubernetes.io label for EDB Job

controllers/bootstrap/init.go, controllers/common/util.go
It is for solving the following problem.
If a developer is using opencloudio with dev image (artifactory) for common services, then other bedrock operators out of opencloudio, like postgresal, can't be installed from the ibm-operator-catalog caatalogsource.  
This PR moves the dev image checking logic into catalogsource comparison, then we can analyze the case individually without impact crossing different catalogsources
=> check dev image for individual operator package

controllers/size/large_amd64.go, controllers/size/medium_amd64.go, controllers/size/small_amd64.go
@horis233 
May I ask that
Should we increase the resources for **all the three profiles** to make all of them exactly same?
Should we only increase the CPU limit of the `cert-manager CA injector`? Or other resources should be changed as well.
=> increase cert manager resources for EUS

controllers/bootstrap/init.go, controllers/constant/crossplane.go, controllers/goroutines/operator_status.go
missing prefix `ibm` when deleting the subscription #725
=> align the subscription name on deleting Crossplane

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/bootstrap/init.go, controllers/commonservice_controller.go
Needed because of this error 
```
E0117 09:13:49.496830       1 commonservice_controller.go:142] Failed to install crossplane or cloud operator: 
providerconfigs.kubernetes.crossplane.io "kubernetes-provider" is forbidden: User "system:serviceaccount:ibm-common-services:ibm-common-service-operator" 
cannot get resource "providerconfigs" in API group "kubernetes.crossplane.io" at the cluster scope
```
Order of Crossplane installation has been changed - variable needs to be set earlier for update scenario
=> Extend clusterRole to install Crossplane providerConfig

controllers/constant/odlm.go
```
I0214 16:46:39.948639       1 init.go:652] Creating resource with name: operand-deployment-lifecycle-manager-app, namespace: ibm-common-services, kind: Subscription, apiversion: operators.coreos.com/v1alpha1
E0214 16:46:39.950754       1 commonservice_controller.go:126] Failed to initialize resources: could not Create resource: Subscription.operators.coreos.com "operand-deployment-lifecycle-manager-app" is invalid: spec.config.env.value: Invalid value: "boolean": spec.config.env.value in body must be of type string: "boolean"
E0214 16:46:39.955922       1 commonservice_controller.go:130] Fail to reconcile ibm-common-services/common-service: could not Create resource: Subscription.operators.coreos.com "operand-deployment-lifecycle-manager-app" is invalid: spec.config.env.value: Invalid …
```
=> use string in subscriptjion.spec.env

api/v3/commonservice_types.go, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, bundle/manifests/operator.ibm.com_commonservices.yaml, config/crd/bases/operator.ibm.com_commonservices.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml, controllers/common/util.go, controllers/commonservice_controller.go, controllers/constant/odlm.go, controllers/operandconfig.go, controllers/render_template.go, controllers/rules/resource_comparison.go, controllers/rules/rules.go
1. Add `profileController` as the overall management strategy
2. Add `managementStrategy` as the management controller for individual service
Options for `profileController` and `managementStrategy` are `default`, `commonservice`, `turbo`, `turbonomic` and `vpa`.
1. `default` and `commonservice` options will keep the original logic where the `OperandConfig` is totally managed by common service CR.
2. `turbo` is the short name of  `turbonomic`.
3. `turbo`, `turbonomic` and `vpa` share the same logic where the resource section including `limit` and `request` will be cleaned up in `OperandConfig`. But it will keep other configuration unchanged, for example, `storageclass` and `routehost`.
1. `profileController` will be co-existed with `size` parameter, but `profileController` could overwrite …
=> add turbo profile controller for common service

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/goroutines/namespacescope.go
`odlm-scope-managedby-odlm` does not exist in multi instances scenario, in order to reduce the requests sent to server, sleep the goroutine when it is not found
=> add cluster permission for issuer and certificate

upgrade_common_services.sh
```
./upgrade_common_services.sh -h                                                                   
Usage: upgrade_common_services_draft.sh [OPTION]...
Upgrade Common Services
Options:
Mandatory arguments to long options are mandatory for short options too.
-h, --help                    display this help and exit
-csNS                         specify the namespace where common service is installed. By default it is namespace ibm-common-services.
-cloudpaksNS                  specify the namespace where cloud paks is installed. By default it would be same as csNS.
-controlNS                    specify the namespace where singleton services are installed. By default it it would be same as csNS.
-c                            specify the subscription channel where common services switch. …
```
=> script for upgrading common service to 3.20

upgrade_common_services_airgap.sh
In airgap env, we would switch channel for all cs components due to the missing bundle images in latest `v3` version.
1. switch channel for cs-operator
2. scale down ibm-common-service-operator deployment to avoid ODLM re-installation
3. delete ODLM to avoid reverting the channel changes for other operators.
4. switch channel for remaining CS components
=> create new upgrade script for airgap env

convert_to_multi_instance.sh
If, for some reason, the operandregistry and operandconfig are not present in the environment during runtime, the script will exit in error with the cs operator and odlm operator pods scaled to 0. This is not a clear situation to users and could be difficult to debug in a live environment. Considering these objects are being deleted, if they are not there, they should not force the script to exit.
=> add ignore not found flag to deleting operandregistry and config

controllers/bootstrap/init.go, main.go
How to verify it:
1. install a mutli-instance mode cs-operator
2. add `installPlanApproval: Manual` to CommonService CR
3. check if the approval mode of crossplane operators and NSS are `manual` in Control NS
=> apply approval mode change in control namespace

controllers/constant/fipsEnable.go
fix for issue [ibm-ingress-nginx operator fips param should be consistent with previous name](https://github.ibm.com/ibmprivatecloud/roadmap/issues/55809)
=> fipsEnable should be consistent with previous name

convert_to_multi_instance.sh
For work item: 
> script should remove namespacescope CRs managed by ODLM (nss-managedby-odlm and odlm-scope-managedby-odlm), so that original instance does not have access to new instances
Open to conversation and feedback on implementation. I am not particularly familiar with how nss works or how these nss CRs get created/recreated (in my testing I manually created them after copying an existing one). I am mostly concerned with the placement of the `removeNSS` function. Right now it is called right after cs operator and odlm are scaled down.
Output looks like:
```
[INFO] patching and deleting namespace scope nss-managedby-odlm in namespace ibm-common-services
namespacescope.operator.ibm.com/nss-managedby-odlm patched …
```
=> remove existing odlm managed nss crs

convert_to_multi_instance.sh
Check that all of the namespaces referred to in common-service-maps configmap exist before running the rest of the script. Try to create all namespaces listed. It _does not_ create the cs-control namespace or check that field at all. The existence of that field is already checked earlier in the code and I think if that namespace does not exist yet we should encourage the user to review their topology before moving on.
Sample output from earlier testing:
```
creating ibm-common-services
Error from server (AlreadyExists): namespaces "ibm-common-services" already exists
ibm-common-services already exists, skipping...
creating ibm-common-services2
namespace/ibm-common-services2 created
creating cpns1
namespace/cpns1 created
creating …
```
=> check that ns in cm exist, create them if they don't

convert_to_multi_instance.sh
Previous implementation saw the script exit prematurely if an operator group already existed in one of the namespaces.
=> properly handle an op group already existing

convert_to_multi_instance.sh
include a check for the nss crs to exist. Previously, if they did not exist and the script was run, it would fail in an unclear way.
=> handle nss deletion error when nss not present

convert_to_multi_instance.sh, upgrade_common_services.sh
Cleanup zen instances before conversion process by patching out the csNamespace key in zenservice and deleting the iam config job and the zen client in cloud pak namespace. 
Open to feedback, related to https://github.com/IBM/ibm-common-service-operator/pull/905 and https://github.com/IBM/ibm-common-service-operator/pull/909. Will likely be merge conflicts
Sample output:
```
zenservice.zen.cpd.ibm.com/iaf-zen-cpdservice patched
job.batch "iam-config-job" deleted
client.oidc.security.ibm.com "zenclient-cpns1" deleted
zenservice.zen.cpd.ibm.com/iaf-zen-cpdservice patched
[INFO] CS Namespace not defined in iaf-zen-cpdservice in cpns2. Moving on...
No zen client in cpns2. Moving on...
```
=> cleanup zen instances before conversion

controllers/constant/crossplane.go
This reverts commit 13e8622110d1fdbb5e14d21d8cadbd942e3e3ef7.
=> Revert "revert crossplane channel to unblock canary (#947)"

networkpolicy/egress/zen-egress-diagnostics-job.yaml, networkpolicy/egress/zen-egress-dsx-influxdb-set-auth.yaml, networkpolicy/egress/zen-egress-iam-config-job.yaml, networkpolicy/egress/zen-egress-nginx-tester.yaml, networkpolicy/egress/zen-egress-nginx.yaml, networkpolicy/egress/zen-egress-usermgmt.yaml, networkpolicy/egress/zen-egress-volumes.yaml, networkpolicy/egress/zen-egress-watchdog-cronjob.yaml, networkpolicy/egress/zen-egress-zen-core-api.yaml, networkpolicy/egress/zen-egress-zen-core.yaml, networkpolicy/egress/zen-egress-zen-metastore-backup-cron-job.yaml, networkpolicy/egress/zen-egress-zen-metastoredb-init-job.yaml, networkpolicy/egress/zen-egress-zen-metastoredb.yaml, networkpolicy/egress/zen-egress-zen-pre-requisite-job.yaml, networkpolicy/egress/zen-egress-zen-watchdog.yaml, networkpolicy/egress/zen-egress-zen-watcher.yaml, networkpolicy/install_networkpolicy.sh, networkpolicy/zen-access-to-audit-svc.yaml, networkpolicy/zen-access-to-dsx-influxdb.yaml, networkpolicy/zen-access-to-nginx.yaml, networkpolicy/zen-access-to-usermgmt.yaml, networkpolicy/zen-access-to-zen-core-api.yaml, networkpolicy/zen-access-to-zen-core.yaml, networkpolicy/zen-access-to-zen-meta-api.yaml, networkpolicy/zen-access-to-zen-volumes.yaml, networkpolicy/zen-access-to-zen-watchdog.yaml, networkpolicy/zen-allow-iam-config-job.yaml
Updating networkpolicies for zen to make them more precise - instead of allowing all ingress, the resources will only allow ingress from required namespaces.
Fixing metadata for zen-meta-api as it resides in `csNamespace`, not `zenNamespace`
=> update zen networkpolicies

controllers/constant/odlm.go
Add historic entries with different suffix for playback purpose only
- `ibm-im-operator`
- `ibm-im-operator-v4.0`
- `ibm-iam-operator-v3.22`
- `ibm-iam-operator-v3.21`
- `ibm-commonui-operator-v3.22`
- `ibm-commonui-operator-v3.21`
- `ibm-zen-operator-v3.22`
- `ibm-zen-operator-v3.21`
=> Add faked multi entry for IAM/IM

controllers/bootstrap/init.go, controllers/constant/constant.go, controllers/goroutines/operator_status.go, controllers/webhook/operandrequest/mutatingwebhook.go
1. User installs the CS operator cluster scoped.
2. If the `ibm-common-services` namespace is not there, the operator waits.
3. If it's there, it creates the CR in the same namespace as operator(openshift-operators) with
```
servicesNamespace: ibm-common-services
operatorNamespace: openshift-operators
```
4. If the user never creates `ibm-common-services` namespace, choose to create it own CommonService CR in the same namespace as operator(openshift-operators), cs-operator accept that and move on.
=> update AllNamespaces Installations Mode

controllers/bootstrap/init.go, main.go
1. deploy `future` CatalogSource in cluster
2. install foundational service in `openshitf-operators` namespace
3. `ibm-common-service-operator` does not get ready and is continuously crash with logs
```
E0207 02:26:39.841424 1 main.go:133] Failed to verify cluster type unable to get: openshift-operators/ibm-cpp-config because of unknown namespace for the cache
E0207 02:26:42.855054 1 main.go:133] Failed to verify cluster type unable to get: openshift-operators/ibm-cpp-config because of unknown namespace for the cache
```
1. `export REGISTRY="<your registry here, e.g. quay.io/daniel_fan>"`
2. run `make build-dev-image` to build own image
3. patch CS CSV under `openshift-operators` with latest build image …
=> update cache for AllNamespace Installation mode

controllers/bootstrap/init.go, controllers/commonservice_controller.go
When any error happens on fetching OperandRegistry and OperandConfig, return `false` for `serviceDeployed` status.
It should not block any installation or namespace changing for `operatorNamespace` and `servicesNamespace`
=> Update status check on deployed services

controllers/bootstrap/init.go, controllers/common/util.go, controllers/constant/constant.go, main.go
When a new ibm-common-services-operator (v4) is installed, `common-service-maps` ConfigMap will be created automatically in the `kube-piblic` if it does not exist. In the default `common-service-maps` template, the `namesoaceMapping` requests from `OperatorNs` mapping to `ServicesNs`.
1. Remove the existing `common-service-maps` ConfigMap
2. Install new IBM Cloud Pak foundational services (v4.0) with image `quay.io/yuchen_shen/cs_operator:csmaps`
3. A new `common-service-maps` ConfigMap will be created in `kube-public`
```
apiVersion: v1
metadata:
name: common-service-maps
namespace: kube-public
data:
- requested-from-namespace:
- "{{ .OperatorNs }}"
map-to-common-service-namespace: "{{ .ServicesNs }}"
```
=> create common service maps with cp3.0 installation

controllers/bootstrap/init.go
Solve an error for resourceVersion is nil when updating a resource
```
metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```
=> set resourceVersion before updating an CR

controllers/constant/odlm.go
- mark tombstone for `ibm-zen-operator` and `ibm-iam-operator`
- revert channel for each of them back to `v3.23`
=> mark tombstone for zen, iam operators

controllers/common/util.go, main.go
When a new ibm-common-services-operator (v4) is installed, the existent `common-service-maps` ConfigMap will be updated in `namespaceMapping` with new `WATCH_NAMESPACE` to `ServicesNs` by checking `operatorNs`.
1. Install new IBM Cloud Pak foundational services (v4.0) by using the same namespace for `servicesNs` and `operatorNs`
2. Apply the image `quay.io/yuchen_shen/cs_operator:csmaps_update`
3. Update NSS CR to include several namespaces
```yaml
spec:
csvInjector:
enable: true
namespaceMembers:
- cloudpak-control
- cloudpak-data
- cloudpak-cp4i
- cloudpak-cp4ba
```
4. Change `ServiceNs` to different one
```yaml
metadata:
namespace: cloudpak-control
spec:
operatorNamespace: cloudpak-control
servicesNamespace: …
```
=> Update common-service-maps ConfigMap

controllers/webhooks/reconciler.go
In Own Namespace Installation Mode, our webhook will have a Namespace selector in webhook configuration to constrain the scope inside `WATCH_NAMESPACE` list.
```
namespaceSelector:
matchExpressions:
- key: kubernetes.io/metadata.name
operator: In
values:
- shared-services
```
In All Namespaces Installation Mode, our webhook should take effect for all namespaces across the cluster, so it has the NamespaceSelector empty
```
namespaceSelector: {}
```
- Deploy `future` CatalogSource in the cluster
- Deploy foundational service in AllNamespace Mode under `openshift-operators` namespace
- Create `ibm-common-services` namespace
- Wait for ODLM is installed successfully
- Create following OperandRequest with hilarious `registryNamespace`
```
kind: …
```
=> fix webhook ns selector for all namespaces mode

controllers/bootstrap/init.go, controllers/common/util.go
Enhance the creation of `common-service-maps` ConfigMap for multiple `RequestNs` case.
1. Install a new IBM Cloud Pak foundational services (v4.0) for for Topology B or C 
2. Apply the image `quay.io/yuchen_shen/cs_operator:csmaps_requestns`
3. A new `common-service-maps` ConfigMap will be created. Ex:
```yaml
data:
controlNamespace: ""
- map-to-common-service-namespace: cloudpak-data
requested-from-namespace:
- cloudpak-control
- cloudpak-data
```
=> enhance creation of csmaps for multiple RequestNs

convert_to_multi_instance.sh
I need to test this on an environment with zen installed but without zen clients created. The error from the issue seems to come from this code block. Hopefully adding the "fail" message to the check as it expects will resolve this.
=> add fail to check

controllers/goroutines/check_iam.go
ibm-common-serivce-operator needs to check the IAM deployments and jobs in `serivcesNamespace`.
However, ibm-common-serivce-operator is not restarted every time when `servicesNamespace` is changed.
As a result, cs-operator does not load correct `servicesNamespace` for IAM status after `serivcesNamespace` has been updated in CommonService CR.
As a workarounds, we need to refresh those namespaces values for each loop
=> refresh operatorNs and servicesNs for each loop

convert_to_multi_instance.sh
We need to migrate over LicenseService data. This data was specified in 57531 and consists of multiple configmaps that may or may not be on the cluster. 
- Iterate through the list check if present
- if present
- output cm to a temp yaml file
- edit the namespace to match the control from the common-service-maps
- apply the new configmap
- delete temp file
To test:
- Setup cluster with Licensing installed, check for configmaps specified in `POSSIBLE_CONFIGMAPS` list in cs namespace
- run this version of conversion script
- check output for cm related messages
- verify script converts cluster successfully
- check control namespace for any of the licensing configmaps in the `POSSIBLE_CONFIGMAPS` list
I have not tested these changes myself yet. Confirming with Licensing team that these steps …
=> Migrate License Service CMs during conversion process

backup_restore_mongo.sh
After investigating 57624, we decided we would need to restart the auth idp pod as a part of the backup restore script. I tested it on my environment and it is working.
To test:
- install cs and instantiate LDAP users (easiest way is through cs dev tools)
- convert cluster to multi instance
- run this version of backup restore script, ensure it completes successfully
- verify can login to new cs instance cp-console with restored LDAP user
=> restart auth idp pod after restore

controllers/constant/odlm.go
https://github.ibm.com/DB2/tracker/issues/32036
As of Cloud Pak 3.0, Db2U will no longer be included in the OperandRegistry for IBM Common Services.
* CP4D is already creating the subscription for Db2U operator instead of using Operand Requests
* CP4S (Guardium) will switch from using Operand Requests to explicitly creating a sub and using the standalone channels
=> feat: Remove Db2U from IBM common services

backup_restore_mongo.sh
Make it possible for the backup_restore_mongo.sh to run backup, restore, or cleanup independently or any combination of the three (though running cleanup after backup and before restore will remove the backup).
To test:
- create shared instance cluster
- create LDAP users for shared cs instance (can be done with cs-dev-tools)
- run this version of backup `./backup_restore_mongo.sh --bns <shared cs instance ns> -b`
- convert cluster to multi instance and install IAM in new cs instance
- wait for IAM pods to come ready
- run restore process `./backup_restore_mongo.sh --bns <shared cs instance ns> --rns <new cs instance ns> -r`
- login to new cp console instance with restored LDAP user
- cleanup resources with `./backup_restore_mongo.sh --bns <shared cs instance ns> --rns <new cs instance …
=> Separate backup, restore, and cleanup processes

convert_to_multi_instance.sh
Right now, we look for cs operator subscription based on the name of the sub. Cloud paks sometimes create the cs operator subscription under a different name (ie cp4i uses `ibm-common-service-operator-v3.23-ibm-operator-catalog-openshift-marketplace` as a sub name) which has caused the script to try to install a second instance of cs operator in a namespace that results in the second cs operator instance sitting in limbo. This has been updated in this pr.
Similarly, if the cs operator already exists in the cloud pak namespace, the version of common services installed will be determined by the subscription that is already present in the cloud pak namespace. This could cause some mix-ups in what catalog source is used and consequently what versions of services are available. This change …
=> change how cs op sub is found and updated

controllers/constant/odlm.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57882
CP3.0 ODLM will not manage cluster scope resources `auditLogging`
1. Install foundation service 4.0, remove `installMode: no-op` for `ibm-auditloggin-operator` in `OperandRegistry`
2. Request `ibm-auditlogging-operator`, will get error msg in `odlm` pod, and `common-service` OC failed
```
failed to get the custom resource cloudpak-all-in-one/example-auditlogging: auditloggings.operator.ibm.com "example-auditlogging" is forbidden: 
User "system:serviceaccount:cloudpak-all-in-one:operand-deployment-lifecycle-manager" cannot get resource "auditloggings" in API group "operator.ibm.com" at the cluster scope
```
3. Manually remove ` auditLogging: {}` in `OperandConfig`, `common-service` OC back to `running`.
=> remove Audit Logging from OperandConfig

controllers/common/util.go
issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/57891
In CP2.0, I have following `common-service-maps` ConfigMap like 
```
data:
- map-to-common-service-namespace: ibm-common-services
requested-from-namespace:
- cloudpak-ns
```
When there is a CS operator v4.0 deployed/upgraded in  `ibm-common-services` namespace, and specify operator namespace in CommonService CR:
```
spec:
operatorNamespace: ibm-common-services
servicesNamespace: ibm-common-services
```
will getting erros msg: 
```
Unsupported common-service-maps: invalid map-to-common-service-namespace: ibm-common-services
```
Add the condition check, if the operator namespace is the same as the existent common service namespace, …
=> update csmaps when operator ns is the same as cs ns

controllers/bootstrap/init.go, controllers/common/util.go, main.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57957
CP2 ODLM will automatically extend its permission to any namespace where OperandRequest exists if `controlNamespace:""` in csmaps
1. Install CP3.0 in `cloudpak-ns`, will see `controlNamespace` is empty `""` when `common-service-maps` is being created.
2. Install CP2.0 in default namespace `ibm-common-services`, and create a `OperandRequest` in `cloudpak-ns`, will see the CP2.0 ODLM  permission is extented to `cloudpak-ns`
- `ibm-common-services` namespace will be included in `namespace-scope` in `cloudpak-ns`
- those tombstone services will be installed in the CP3.0 ns
```
apiVersion: v1
metadata:
name: namespace-scope
namespace: cloudpak-ns
data:
namespaces: 'ibm-common-services,cloudpak-ns'
```
1. Apply …
=> set ControlNs to cs-control when csmaps creating

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/migrate_tenant.sh
1. If users are using NSS restricted version before upgrade, the script will uninstall NSS restricted and re-install NSS v4.
2. If the subscription is not found in a namespace, script will ignore this subscription.
- It is possible that cs-operator does not exist in some namespaces.
=> Enhance migrate_tenant script

cp3pt0-deployment/common/delegate_cp2_cert_manager.sh
In a old version of cert-manager, there is a finalizer blocking the deletion.
Update the script to remove this finalizer when it is stuck.
Test result
```
certmanager.operator.ibm.com "default" deleted
error: timed out waiting for the condition on certmanagers/default
Failed to delete Cert Manager CR, patching its finalizer to null...
certmanager.operator.ibm.com/default patched
```
=> remove certmanager finalizer when it is stuck

api/v3/commonservice_types.go, bundle/manifests/operator.ibm.com_commonservices.yaml, config/crd/bases/operator.ibm.com_commonservices.yaml, controllers/constant/defaultAdminUser.go, controllers/render_template.go, controllers/rules/rules.go
Provide to specify a default admin username when there is IM/IAM installing
ticket: https://github.ibm.com/ibmprivatecloud/roadmap/issues/57144
1. Install foudational service v4.0 with image `quay.io/yuchen_shen/cs_operator:admin_username` applied
2. In `CommonService` CRD add property entry for `defaultAdminUsername`
```
spec:
properties:
defaultAdminUsername:
type: string
```
3. In `CommonService` CR, try to set an admin username for `defaultAdminUsername` into Spec:
```
spec:
defaultAdminUsername: admin123
```
4. Check in OperandRegistry, new config will be set under ibm-im/iam-operator
```
- name: ibm-im-operator
spec:
authentication:
config:
defaultAdminUser: admin123
onPremMultipleDeploy: true
```
=> Specify a default admin username for IM/IAM

isolate.sh
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57938
- Get ODLM subscriptions based on given namespace after conversion
- Check and set ISOLATED_MODE value to true, support multiple runs
- Apply the updated subscription back to the cluster
Checked the ODLM `pod` and `deployment` yaml, they all have corresponding updates.
=> ensure isolated mode value is true in ODLM subscription

controllers/bootstrap/init.go, controllers/constant/constant.go, controllers/goroutines/cppConfig.go, controllers/goroutines/variables.go, main.go
`ibm-cpp-config` will be copied from `servicesNamespace` to all other namespace in the `WATCH_NAMESPACE` list.
1. Deploy `cd` CatalogSource
2. Install cert-manager cluster wide
3. Using `setup_tenant.sh` to install CS in advanced topology including different operator and service namespace, as well as other tethered(CloudPak) namespace
4. Replace CS operator image by `quay.io/daniel_fan/common-service-operator-amd64:dev`
5. We will observe the `ibm-cpp-config` showing up in all namespaces in the tenant.
6. If we manually change the content in `ibm-cpp-config` ConfigMap, it will propagate the changes to other namespaces in 10 min.
=> share ibm-cpp-config to all WATCH_NAMESPACE

cp3pt0-deployment/migrate_singleton.sh
fix for the issue: [57978](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57978#issuecomment-55822700)
When there is a value of `--cert-manager-source` passed in, but cert-manager subscription did not create with a expected source name.
=> Pass in a correct source name for cert manager argument

cp3pt0-deployment/migrate_singleton.sh
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58233
```
[INFO] Creating following Subscription:
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
name: ibm-cert-manager-operator
namespace: ibm-cert-manager
spec:
channel: v4.0
installPlanApproval: Automatic
name: ibm-cert-manager-operator
source: ibm-cert-manager-catalog
sourceNamespace: openshift-marketplace
subscription.operators.coreos.com/ibm-cert-manager-operator created
[INFO] Waiting for operator ibm-cert-manager-operator in namespace ibm-cert-manager to be made available
[INFO] RETRYING: Waiting for operator ibm-cert-manager-operator in namespace ibm-cert-manager to be made available (1 left)
[✘] Timeout after 0 minutes waiting for ibm-cert-manager-operator in namespace ibm-cert-manager to …
```
=> migrate_singleton.sh should exit script and return error

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/migrate_tenant.sh
for the issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57978#issuecomment-55770004
Given the same channel and catalogsource info as the existing one, upgrade will continue
log:
```
[INFO] v4.0 is equal to v4.0
[INFO] catalogsource opencloud-operators is the same as opencloud-operators
[INFO] ibm-common-service-operator has already updated channel v4.0 and catalogsource opencloud-operators in the subscription.
subscription.operators.coreos.com/ibm-common-service-operator configured
```
=> continue to run the in-place upgrade script even the sub was updated

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/setup_tenant.sh
enhancement base on: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57592#issuecomment-55240538
when we check deployment, both readyReplicas and replicas should be one
=> add replicas check

controllers/webhooks/operator_webhooks.go, main.go
- Exit code when webhook server is failed to stand up
- Extend wait time for CA cert secret to 3 minutes
- ~~Update annotation to inject CA from secret~~
=> throw out error when webhook server fail to set up

controllers/webhooks/operator_webhooks.go, main.go
We have a historic issue that it always returns error on webhook server setup.
```
E0420 17:28:39.632613 1 main.go:259] expected pointer, but got invalid kindError setting up webhook server
```
Check history here: https://github.com/IBM/ibm-common-service-operator/pull/1023#issuecomment-1432607872
=> remove exit code for webhook server

isolate.sh
Uninstall singletons could happen immediately after we pause the original instance, it removes broken webhook configuration and services, and unblock ConfigMap configuration.
=> uninstall singletons immediately after pause

cp3pt0-deployment/common/utils.sh
Kaihua mentioned seeing this error:
```
root@stc1:~/ibm-common-service-operator# ./cp3pt0-deployment/migrate_singleton.sh --operator-namespace cs-control --enable-private-catalog
Error: unknown shorthand flag: 'r' in -r
Usage:
yq [flags]
yq [command]
```
The oc lines are from the prereq function, then the yq failure with -r is from line 633 in utils.sh as the `get_control_namespace` function is more or less the next thing executed in the script. It looks like we try to create the `config_map_data` variable using a jsonpath and then try to read it with yq with `yq -r '.controlNamespace'`. I think as long as we use yq we should stay consist in outputting files in yaml and not mix and matching with json.
=> yq not able to read json input causing line 633 to fail

cp3pt0-deployment/common/utils.sh
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58227
In this ticket we found this error message `User does not have proper permission to get IBMLicensing` is kinda misleading, update this error message
=> update error message for licensing

backup_restore_mongo.sh, rollback-multi-instance.sh
Since the last time the rollback script was updated, a lot was updated in the conversion script. For the rollback to work, it has to pretty much undo all of that work and also reconcile zen. There were also some smaller changes made to backup restore to make it work properly.
basically, rollback allows you to go from something like this
```
apiVersion: v1
metadata:
name: common-service-maps
namespace: kube-public
data:
- requested-from-namespace:
- cpns1
map-to-common-service-namespace: ibm-common-services
- requested-from-namespace:
- cpns2
map-to-common-service-namespace: csns2
```
to something like this
```
apiVersion: v1
metadata:
name: common-service-maps
namespace: kube-public …
```
=> Update Rollback script to be the reverse of the conversion script

cp3pt0-deployment/common/migrate_singleton.sh, cp3pt0-deployment/migrate_singleton.sh, cp3pt0-deployment/setup_singleton.sh
For ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58360
How to test it:
run `./setup_singleton.sh --operator-namespace <operator_ns>` 
it will get the control namespace and do the migration for CP2 Instance,
=> Consolidate migrate_singleton.sh and setup_singleton.sh script

isolate.sh
- excluding namespaces made the assumption that the provided namespace(s) were already within the scope of the tenant
- bad assumption because if the provided exclude-ns namespace(s) were not within scope, then isolate would actually add in those namespaces to the scope
- fixed by intentionally duplicating EXCLUDED_NS to the scope variable before passing it though the duplicate removal pipe, so that excluded-ns will always be removed from scope, whether they exist in namespace-scope CM or not
=> fixed isolate.sh to properly exclude namespaces

controllers/webhooks/commonservice/validatingwebhook.go
action plan implement: https://github.ibm.com/ibmprivatecloud/roadmap/issues/57413#issuecomment-56051304
- Updates on the following four `Spec` parameters in non-master CommonService CRs in the scope is prohibited when the updated values are differed from the values in master/default CommonService CR.
- Validating Webhook will validate and deny updates when user are try to change those parameters in other CommonService CRs.
```
metadata:
namespace: cloudpak-control
spec:
operatorNamespace: cloudpak-control
servicesNamespace: cloudpak-data
catalogName: ibm-operator-catalog
catalogNamespace: openshift-marketplace
```
quay.io/yuchen_shen/cs_operator:config_status
1. Try to edit master/default CommonService CR, will be …
=> deny updating in non master CommonService CR

cp3pt0-deployment/migrate_tenant.sh
To avoid error
```
./cp3pt0-deployment/migrate_tenant.sh --operator-namespace ibm-common-services
[✘] Licensing Migration could only be done in controlNamespace, please set parameter '-licensingNs cs-control'
```
=> update licensing ns for migration

cp3pt0-deployment/migrate_tenant.sh
Missing `INSTALL_MODE` argument in `parse_arguments` function, and add it back to the migration script
=> parse install mode command-line argument

cp3pt0-deployment/setup_singleton.sh
enhancement for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58360#issuecomment-56394033
If `operator-namespace` is set: 
1. without `--enable-licensing` to only migrate cert-manager
2. with `--enable-licensing` , means we need to migrate licensing. So`--licensingNs` will be optional, but it have to be control-namespace
Test result:
```
root@axe1:~/projects/go/src/ibm-common-service-operator/cp3pt0-deployment# ./setup_singleton.sh --operator-namespace ibm-common-services --enable-licensing -licensingNs cs-control
check pass
root@axe1:~/projects/go/src/ibm-common-service-operator/cp3pt0-deployment# ./setup_singleton.sh --operator-namespace ibm-common-services --enable-licensing -licensingNs kube-public
[✔] oc …
```
=> licensing-enhancement

isolate.sh
Remove q in favor of yq since this was the only occurrence of jq in the script and we don't check to make sure it is installed. I tested the command manually and the output is the exact same.
=> tweaks based on CPD feedback

cp3pt0-deployment/common/migrate_singleton.sh
fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57978#issuecomment-56591582
1. install a cs 3.23 in `ibm-common-services` ns
2. running `./migrate_tenant.sh --enable-licensing     --operator-namespace ibm-common-services     --cert-manager-source ibm-cert-manager-operator-catalog     --licensing-source ibm-licensing-catalog     -c v4.0     -i Automatic
`
3. upgrade successfully without terminated
```
certmanager.operator.ibm.com "default" deleted
[INFO] Waiting for pod cert-manager-cainjector in namespace ibm-common-services to be deleting
[✔] Pod cert-manager-cainjector in namespace ibm-common-services is deleted
[INFO] Waiting for pod cert-manager-controller in namespace ibm-common-services to be deleting
[✔] Pod cert-manager-controller in namespace …
```
=> make sure three cert manger pods are deleted when deactivating cp2 cert manager

cp3pt0-deployment/setup_tenant.sh
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58489
If  CommonService CRD exists in the cluster, we patch CommonService CR before install CS operator
Otherwise, we patch CommonService CR after install CS operator
=> Patch CommonService CR before install CS operator

cp3pt0-deployment/common/utils.sh
If user execute the `migrate_tenant.sh` script after CS operator is upgraded, it will hit issue when updating CS CR because CS deployment is scaled down, but webhook configuration is looking for service endpoint.
In order to support run the script idempotent, delete CS CR validatingWebhookConfiguration when we scale down CS deployment.
=> remove WebhookConfiguration to unblock CR update

convert_to_multi_instance.sh
The conversion script waits for iam to come ready in order to reconcile zenservices with the new iam deployment. Ran into an issue during cp4d testing where a zen service did not enable iam so the script failed by timing out waiting for iam and consequently did not reconcile the zenservices that did request iam. This change makes it so we only wait for iam to come ready in the cs namespaces serving zenservices that enable iam.
Test pending
=> only check for iam when a zenservice has requested it

controllers/constant/certmanager.go
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58532
Update the cs-ca-certificate renewBefore time to 8 months
=> update renewBefore time to 8 months

convert_to_multi_instance.sh, isolate.sh, rollback-multi-instance.sh
It's possible if multiple cert managers are or have been installed on a cluster that simply searching for `certmanager` to find the cert manager CR will not work:
```
[root@api.alex3.cp.fyre.ibm.com ~]# oc get certmanager
No resources found
[root@api.alex3.cp.fyre.ibm.com ~]# oc get certmanagers.operator.ibm.com 
NAME      AGE
default   4h15m
```
Specifying the full name of the cr always works and should be a safer, more consistent option.
=> change cert manager cr to full name

preload_data.sh
Add back `--original-cs-ns` and `--services-ns` flags to denote parameters for the preload_data.sh script after discussion with cpd
=> add flags back to parameters

preload_data.sh
For https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58594. In the function `dumpmongo` a mongodb-backup job is created using an image from quay (found https://github.com/IBM/ibm-common-service-operator/blob/scripts/preload_data.sh#L262). This image looks to be the same image that is used in mongodb so I have replaced the quay image with whatever the existing mongo in the original cs ns is using. I have run a preliminary test and the script was able to complete successfully and the data seems to have been transferred smoothly.
Testing:
- install a shared common services cluster with at least one instance of zen with iam enabled
- run preload_data.sh to preload data into target ns for new cs instance (aka services ns)
- edit common-service-maps to move whichever ns zen was installed …
=> change backup image to existing mongo image

isolate.sh
Issue 9446 in CPD quality repo seems to be experiencing a problem with the webhooks not being present stopping the creation of common-service-maps configmap. We ran into this problem previously w/ https://github.com/IBM/ibm-common-service-operator/pull/1167 but moved the uninstall_singletons again in https://github.com/IBM/ibm-common-service-operator/pull/1188 to prevent deleting anything before creating csmaps. This pr would change it so only the webhooks are cleaned up right after the pause, everything else will be uninstalled/deleted right before the restart.
I have run the script several times on my own environment and have not seen any issues with the webhook not being there to create or edit the common-service-maps cm. However, I did not see the issue using the previous version …
=> move webhook cleanup to immediately after pause

controllers/constant/odlm.go
Creating EDB license key in operator namespace, including its corresponding resources job, service account and rbac.
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58579
=> creating EDB license key in operator namespace

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/setup_singleton.sh
SERT team has consistently had trouble with the `--license-accept` option when running the `setup_singleton.sh` script. From the log output, it appears that the `ibmlicensing` instance is not created by the time the `accept_license` function attempts to edit it resulting in a warning and the license not being accepted. Logs look like the following:
```
[INFO] Waiting for operator ibm-licensing-operator in namespace cs-control-ns to be made available
[INFO] RETRYING: Waiting for operator ibm-licensing-operator in namespace cs-control-ns to be made available (50 left)
[INFO] RETRYING: Waiting for operator ibm-licensing-operator in namespace cs-control-ns to be made available (49 left)
[INFO] RETRYING: Waiting for operator ibm-licensing-operator in namespace cs-control-ns to be made …
```
=> wait for licensing instance to be created before accepting license

backup_restore_mongo.sh, preload_data.sh
Replacing https://github.com/IBM/ibm-common-service-operator/pull/1197
When running either of the scripts for backing up and restoring mongo data into a new namespace, the ldaps secret can be created without the certificate filled in. This would disable the ability to log in using LDAP so we need to make sure this secret is there and matches the original.
Testing preload:
- install shared cluster with LDAP enabled and users created
- run preload script
- verify secret is copied over into new namespace and equals original
- convert cluster with new cs in target namespace from preload
- make sure LDAP login works with new cs instance
Testing backup_restore:
- install shared cluster with LDAP enabled and users created
- run conversion
- run backup restore script
- verify secret is present in …
=> ensure ldaps secret exists in target namespace after restore

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/uninstall_tenant.sh
For ticket: https://github.ibm.com/ibmprivatecloud/roadmap/issues/58490
Base on https://github.ibm.com/IBMPrivateCloud/cs-dev-tools/blob/master/install/cp3pt0-install/uninstall_tenant.sh
```
Options:
--oc string                    File path to oc CLI. Default uses oc in your PATH
--operator-namespace string    Required. Namespace to install Foundational services operator
-f                             Enable force delete
-h, --help                     Print usage information
```
install CP3 and run `./uninstall_tenant.sh --operator-namespace ibm-common-services -f`
After running this script, all the resources in/and the target namespaces should be removed. 
It should clean all the namespaces in the namespace-scope configmap.
It will keep control namespace/ cert-manager namespace/ …
=> uninstall and force uninstall script

cp3pt0-deployment/migrate_tenant.sh
The issue is that `arguments` variable is assigned twice, and `arguments="--enable-licensing"` is overwritten.
```
[INFO] Waiting for pod cert-manager-cainjector in namespace cs-control to be deleting
[✔] Pod cert-manager-cainjector in namespace cs-control is deleted
[INFO] Waiting for pod cert-manager-controller in namespace cs-control to be deleting
[✔] Pod cert-manager-controller in namespace cs-control is deleted
[INFO] Waiting for pod cert-manager-webhook in namespace cs-control to be deleting
[✔] Pod cert-manager-webhook in namespace cs-control is deleted
[INFO] Waiting for pod ibm-cert-manager-operator in namespace cs-control to be running
[✔] Pod ibm-cert-manager-operator in namespace cs-control is running
[✔] Migration is completed for Cloud Pak 3.0 Foundational singleton …
```
=> Enable Licensing Service Migration

cp3pt0-deployment/common/delegate_cp2_cert_manager.sh
There is a case that cert-manager is not installed in control namespace. So we will skip waiting for cert-manager-operator running the control namespace.
- Scale down CP2 ODLM if there is CP2 OperandRequest asking for cert-manager
- Delete IBM cert-manager operator v3 from control namespace
- execute script `./common/delegate_cp2_cert_manager.sh --control-namespace cs-control`
```
./common/delegate_cp2_cert_manager.sh --control-namespace cs-control
[INFO] Configuring Common Services Cert Manager..
configmap/ibm-cpp-config configured
[INFO] Deleting existing Cert Manager CR...
[✗] IBM Cloud Pak 2.0 Cert Manager does not exist in namespace cs-control, skip restarting cert manager pod...
[INFO] Waiting for pod …
```
=> skip restarting cert-manager if it not installed

isolate.sh
This pr is predicated on change made to how isolate waits on cert manager in https://github.com/IBM/ibm-common-service-operator/pull/1227 and contains some of the same changes. Copying over some of the relevant comments from that pr here:
It is debatable whether we need to create a new opreq for cert manager in a situation where every cp2 requesting namespace is excluded. That being said, the zen team has asked us before to check for cert manager to be ready in the isolate script so I believe they expect it to be there too. Adding the cert manager opreq is a fix that ensures our script completes and that cert manager is on the cluster but maybe more conversation can be had between zen and bedrock about expectations for cert manager, who installs it, and what the isolate script should do …
=> Check if cert manager is deployed in the instance that it is not requested (excluded-ns edge case)

preload_data.sh
The preload script was not roks compatible due to specifying the storageclass name in the PVC creation during the `swapmongopvc` function. I have not seen this issue myself but it was brought up by Mike Kaczmarski and this was ostensibly the only change required.
Testing:
- setup shared common services installed on a roks cluster, setup ldap users
- run the preload_data.sh script
- ensure script completes successfully, verify the  mongodbdir-icp-mongodb-0 pvc is bound in the target namespace
- run conversion using the target namespace of the preload script as the new cs instance, verify ldap can login to new cs namespace
=> make preload data roks compatible

isolate.sh
Licensing noticed if cs-control was not already created before running script, isolate would fail if it needed to move over licensing configmaps because the check for cs-control to exist was after the call to move licensing configmaps.
Test:
- setup environment for isolation with at least one licensing configmap (can be dummy, see list of possible cms in script)
- do not create control namespace before running script
- run isolate script
- ensure control namespace is created before licensing configmaps are moved over
- ensure script completes successfully
=> move ns existence check earlier in script

cp3-networkpolicy/ingress/services/zen-access-to-audit-svc.yaml, cp3-networkpolicy/ingress/services/zen-access-to-nginx.yaml, cp3-networkpolicy/ingress/services/zen-access-to-usermgmt.yaml, cp3-networkpolicy/ingress/services/zen-access-to-zen-core-api.yaml, cp3-networkpolicy/ingress/services/zen-access-to-zen-core.yaml, cp3-networkpolicy/ingress/services/zen-access-to-zen-minio.yaml, cp3-networkpolicy/ingress/services/zen-access-to-zen-volumes.yaml, cp3-networkpolicy/ingress/services/zen-access-to-zen-watchdog.yaml, cp3-networkpolicy/ingress/services/zen-allow-iam-config-job.yaml, cp3-networkpolicy/install_networkpolicy.sh
Adding zen network policy for cp3. 
Note that `opNamespace` is added in services policies as another placeholder for string replacement(`sed`).
Installation testing:
```
$ ./install_networkpolicy.sh -n cpd-instance -o cpd-operator
-----------------------------------------------------------------------
[✔] IBM Common Services found in namespace cpd-operator
-----------------------------------------------------------------------
[INFO] Using IBM Common Services namespace: cpd-instance
[INFO] Using operators namespace: cpd-operator
...
...
-----------------------------------------------------------------------
[✔] IBM Common Services NetworkPolicies installation or removal completed at Thu May 18 07:24:47 PDT 2023 .
```
```
$ oc …
```
=> Networkpolicies cp3 zen

controllers/bootstrap/init.go, controllers/constant/odlm.go, controllers/rules/rules.go, controllers/size/large_amd64.go, controllers/size/large_ppc64le.go, controllers/size/large_s390x.go, controllers/size/medium_amd64.go, controllers/size/medium_ppc64le.go, controllers/size/medium_s390x.go, controllers/size/small_amd64.go, controllers/size/small_ppc64le.go, controllers/size/small_s390x.go, controllers/size/starterset_amd64.go, controllers/size/starterset_ppc64le.go, controllers/size/starterset_s390x.go
Introduced a new function `ConcatenateRegistries` essentially combines the `Operators` from two OperandRegistry objects and returns the concatenated YAML representation of the modified OperandRegistry.
for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/58224
- It creates two OperandRegistry objects: `baseRegistry` and `insertedRegistry` by unmarshaling the YAML templates using the applyTemplate function.
- It appends the `Operators` from `insertedRegistry` to the existing `Operators` in `baseRegistry`.
- It marshals the modified base object back to YAML format using json.Marshal.
- It returns the resulting YAML string and any error that occurred during the process.
test image: quay.io/yuchen_shen/cs_operator:split_opreg
delete origin OprandRegistry and it will create a new …
=> Implement Concatenating OperandRegistry YAMLs

cp3pt0-deployment/setup_tenant.sh
Zen has asked to make it so users of the setup_tenant.sh script did not need to enter the entire list of tenant namespaces every time the script is run. This pr makes it so you only need to add the new namespaces with the --tenant-namespaces parameter. This parameter still works with entering the entire list of namespaces though. Explanation:
- script checks for existing common-service NSS (what is being updated or created)
- if it does not exist, create based on namespaces used in --tenant-namespaces
- if it does exist, remove any duplicate entries between the existing list and the new list entered with --tenant-namespaces. The net change is additive only unless namespaces were specified with optional --excluded-namespaces parameter.
The new --excluded-namespaces parameter removes a …
=> setup_tenant.sh: change --tenant-namespaces to not require entire tenant list, add --excluded-namespaces parameter

preload_data.sh
update image used for restore job to the existing mongo image on the cluster for airgap purposes
=> preload: change restore image to existing mongo

preload_data.sh
CPD quality issue brought up an issue where they are trying to preload mongo into a namespace with an existing cpd deployment. Part of this existing deployment is a resource quota that is enforcing pods have values for their resource limits and requests:
>  Warning  FailedCreate  2s    job-controller  Error creating: pods "mongodb-restore-l7sp5" is forbidden: failed quota: cpd-quota: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
This is preventing the preload script from completing and is a blocker for zen. Adding the resource values should be sufficient for resolving this issue.
Testing:
- run preload script as normal, bonus if a resource quota is created in the target namespace
- ensure script completes
- view the restore pod in the target namespace and verify …
=> add resource limits and requests to backup restore jobs

cp3pt0-deployment/setup_tenant.sh
Cover the concern case for fresh installation when CommonService CRD does not exist.
When it is a fresh installation, `RETRY_CONFIG_CSCR` will never set to 1. And `configure_cs_kind` function will not raise error if `RETRY_CONFIG_CSCR` is not `1`.
We need to set `RETRY_CONFIG_CSCR` to 1 when `configure_cs_kind` is called AFTER installing cs-operator, it will abort the scripts when number of remaining retires is 0.
=> Cover corner case for fresh install without CRD

preload_data.sh
Currently, the admin user/pass is hardcoded so any mongo that gets it's data after the preload process is using the exact same admin user/pass combo regardless of cluster or which mongo its data originated from. Change this to use the existing admin user/pass combo from the mongo the data originates from instead.
test:
- run preload
- verify script completes
- check icp-mongodb-admin secret and verify it matches in original and new cs ns
=> match admin pass to original

controllers/bootstrap/init.go, controllers/commonservice_controller.go, controllers/constant/certmanager.go
For issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57401
Testing image: quay.io/yuchen_shen/cs_operator:clean_resources
When the first time to deploy CP3 in the cluster, by default `servicesNamespace` is the same as `operatorNamespace`, the following resources will be generated in that tmp `serivcesNamespace`.
After servicesNamespace is changed, the resources should be cleaned up properly and create under the new `serivcesNamespace`
- CertManager CRs including certificates and issuers
- default OperandRegistry and OperandConfig `common-service`
1. Using setup_tenant script to deploy a CP3 (could choose Topology B with 2 different tethered ns, and same ns for services ns and operator ns)
2. apply the testing image
3. add label `operator.ibm.com/managedByCsOperator: 'true'` …
=> clean up the resources when services ns is changed

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/migrate_tenant.sh, cp3pt0-deployment/setup_singleton.sh, cp3pt0-deployment/setup_tenant.sh, cp3pt0-deployment/uninstall_tenant.sh, isolate.sh, preload_data.sh
for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/57620#issuecomment-57362560
- Check if the passed in value of DEBUG is 1 or 0, otherwise return error
- Redirect stdout and stderr to the log file, overwriting it each time
- Remove ANSI escape sequences from log file
```
[✔] Profile size is valid.
[INFO] Namespace test-ns already exists. Skip creating
[INFO] Namespace test-ns already exists. Skip creating
[INFO] Namespace tenant1-a already exists. Skip creating
[INFO] Namespace tenant1-b already exists. Skip creating
[INFO] Checking existing OperatorGroup in test-ns:
[INFO] OperatorGroup already exists in test-ns. Skip creating
```
=> redirect output to a log file

cp3pt0-deployment/common/utils.sh
for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58843
In this updating, the if condition checks the value of the `OSTYPE` environment variable to determine the operating system.
If it's `macOS`, and the `sed` command uses `''` as the backup file extension
=> make sed command compatible with both macOS and Linux

convert_to_multi_instance.sh, isolate.sh, rollback-multi-instance.sh
To avoid applying the changed subscription on top of the existing and possibly running into an error due to resourceVersion mismatches, we need to update the value in place in the `isolate_odlm` function. This function is called in the isolate, conversion, and rollback script so needs to be updated in all three locations.
To do this, I have added a patch statement to edit the existing subscription. Unfortunately, patches to an array completely overwrite the array. This means I cannot just update the `ISOLATE_MODE` value without wiping the values of the other `spec.config.env` variables. To get around this, I loop through the output of `spec.config.env[]` and add the name and value back to the subscription in the order they were read in. If the variable name is `ISOLATE_MODE`, the script …
=> edit odlm sub in place

cp3-networkpolicy/README.md, cp3-networkpolicy/ingress/cert-manager/allow-webhook-access-from-apiserver.yaml, cp3-networkpolicy/ingress/cert-manager/bedrock-access-to-cert-manager-webhook.yaml, cp3-networkpolicy/ingress/license-service/bedrock-access-to-license-service-reporter.yaml, cp3-networkpolicy/ingress/license-service/bedrock-access-to-license-service.yaml, cp3-networkpolicy/ingress/operators/access-to-edb-postgres-webhooks.yaml, cp3-networkpolicy/ingress/operators/access-to-ibm-common-service-operator.yaml, cp3-networkpolicy/ingress/operators/access-to-zen-meta-api.yaml, cp3-networkpolicy/ingress/operators/allow-webhook-access-from-apiserver.yaml, cp3-networkpolicy/ingress/services/access-to-common-web-ui.yaml, cp3-networkpolicy/ingress/services/access-to-edb-postgres.yaml, cp3-networkpolicy/ingress/services/access-to-icp-mongodb.yaml, cp3-networkpolicy/ingress/services/access-to-platform-auth-service.yaml, cp3-networkpolicy/ingress/services/access-to-platform-identity-management.yaml, cp3-networkpolicy/ingress/services/access-to-platform-identity-provider.yaml, cp3-networkpolicy/ingress/services/access-to-zen-stopgap.yaml, cp3-networkpolicy/ingress/services/zen-access-to-audit-svc.yaml, cp3-networkpolicy/ingress/services/zen-access-to-nginx.yaml, cp3-networkpolicy/ingress/services/zen-access-to-usermgmt.yaml, cp3-networkpolicy/ingress/services/zen-access-to-zen-core-api.yaml, cp3-networkpolicy/ingress/services/zen-access-to-zen-core.yaml, cp3-networkpolicy/ingress/services/zen-access-to-zen-minio.yaml, cp3-networkpolicy/ingress/services/zen-access-to-zen-volumes.yaml, cp3-networkpolicy/ingress/services/zen-access-to-zen-watchdog.yaml, cp3-networkpolicy/ingress/services/zen-allow-iam-config-job.yaml, cp3-networkpolicy/install_networkpolicy.sh
Contributes to https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58737 .
Added network policies for IM, Mongo, CS-operator and EDB. Added a stop-gap network policy for Zen, before the fine-grained one is provided.
cc @bitscuit @ujjwalchk-it
=> Initial upload of CP3 network policies

controllers/bootstrap/init.go
Uninstall ODLM in other namespace other than operator namespace.
This is used to handle the All Namespace Upgrade Scenario when CS operator will move ODLM from `ibm-common-services` namespace to `openshift-operators` namespace.
=> Uninstall ODLM from servicesNs in all SoD scenario

cp3pt0-deployment/common/migrate_cp2_licensing.sh, cp3pt0-deployment/common/migrate_singleton.sh, isolate.sh
fixes: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58774
moved restore of IBMLicensing CR just after the LicSvc operator is removed, to avoid the situation where such operator is redeployed later, while the CR restore was conditional based on the namespaces/topology configuration
=> Bug/58774: re-fix of license service migration with customisation preserved

isolate.sh
If there is no ibmlicensing resource on a cluster, the isolate script will fail with `error: the server doesn't have a resource type "IBMLicensing"`. This pr adds a check for  the resource to exist before continuing to prevent an unnecessary script exit.
Testing
- setup cluster with common services but without licensing deployed
- run the isolate script
- verify script completes and this info line is output: "No ibmlicensing resources on cluster, skipping backup."
=> check for ibmlicensing resource to exist before backup

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58865
`:4.0.0` tag is added back to the common service operator image
=> add 4.0.0 tag back to related images

isolate.sh
CPD has asked us to wait on the namespace-scope cm in the original namespace to be updated before exiting from the script. This pr adds that wait as well as cleans up a few other issues.
Testing:
- setup cs environment
- run isolation script, make sure the original tenant changes in some way (either via excluded ns or insert ns)
- verify script completes
=> wait for namespace-scope cm to match expected value after isolation

cp3pt0-deployment/common/utils.sh
CP4BA is using Bourne shell to execute the script, and it does not support process substitution for command `>(tee "$LOG_FILE")` to record the logs.
Update the scripts to use a named pipe  to tee the output to both the log file and the terminal
```
> cp3pt0-deployment git:(scripts-dev) ./setup_singleton.sh --enable-licensing --license-accept -v 1
```
```
> cp3pt0-deployment git:(scripts-dev) ✗ sh setup_singleton.sh --enable-licensing --license-accept -v 1
/Users/daniel/Downloads/IBM/ibm-common-service-operator/cp3pt0-deployment/common/utils.sh: line 1031: syntax error near unexpected token `>'
/Users/daniel/Downloads/IBM/ibm-common-service-operator/cp3pt0-deployment/common/utils.sh: line 1031: ` …
```
=> support both bash and Bourne shell

controllers/constant/odlm.go, controllers/rules/rules.go, controllers/size/large_amd64.go, controllers/size/large_ppc64le.go, controllers/size/large_s390x.go, controllers/size/medium_amd64.go, controllers/size/medium_ppc64le.go, controllers/size/medium_s390x.go, controllers/size/small_amd64.go, controllers/size/small_ppc64le.go, controllers/size/small_s390x.go, controllers/size/starterset_amd64.go, controllers/size/starterset_ppc64le.go, controllers/size/starterset_s390x.go, docs/cloudpak-integration.md, testdata/actual.yaml, testdata/expected.yaml
for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58223#issuecomment-57732331
testing image: quay.io/yuchen_shen/cs_operator:split_opreg
- The `ibm-mongodb-operator` will be renamed to `ibm-im-mongodb-operator` for CP3 mongo.
- The `ibm-im-operator` without version suffix would request the internal component `ibm-im-mongodb-operator`
- The `ibm-im-operator-v4.0` with version suffix would request the internal component with version suffix `ibm-im-mongodb-operator-v4.0`
=> align name of cp3 mongodb operator with im operator

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
modified related image name to `CPFS_UTILS_IMAGE` for Airgap mirroring
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58865#issuecomment-57825125
=> rename related images

preload_data.sh
We need to make sure all of the possible customization options an end user may have are carried over from CP2 into the new cs namespace to make the transition as seamless as possible. So far the resources included in preload_data.sh consist of:
- backup of original mongo
- platform-auth-idp-credentials secret
- platform-auth-ldaps-ca-cert secret
- ibm-cpp-config configmap
- common-web-ui-config configmap
- common-service commonservice (CR)
Ongoing investigation as to what else needs to be included in this process
Testing:
- setup cp2 cluster with these customization resources created and values assigned (to verify they carry over)
- for configmaps, can set a `data.test: "test"` value
- verified common-web-ui-config customization carried over with @sgrube yesterday
- for commonservice, …
=> Generalize copy function, add more customization resources to copy over

preload_data.sh
Copy over the oidc secret with the other custom resources copied over. This should be the last resource we need to copy over using preload_data.sh.
=> copy oidc secret

isolate.sh
Issue was opened against isolate.sh script running on mac os denoting: `./isolate.sh: line 285: -1: substring expression < 0`. I moved where the comma is set so we do not need the complicated substring logic anymore. I also updated it so we do not add the map to cs ns namespace more than once to the list and added some debug statements.
Testing:
- setup cp2 env
- run isolate script with debug enabled
- verify script completes, look for the added debug messages to output expected namespaces
=> change where comma is set to sidestep issue

cp3pt0-deployment/common/utils.sh, isolate.sh
In the scenario where the isolate script fails and is then run again, it is possible given current implementation that the cert manager is deleted and marked for migration on the first failed run. Then, if the script failed before cert manager was redeployed, it would not be marked for migration on the second run. Combine this situation with the possibility that operand requests requesting cert manager are now all out of scope (due to the excluded parameter) and it creates a scenario where cert manager is not installed at all.
The code change in this pr would always call the `wait_for_certmanager` function. This function calls `check_if_certmanager_deployed` which checks the scope for operand requests calling for cert manager. If none exist in scope, it will create one in the original cs …
=> always call wait for certmanager function

isolate.sh
fix for: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58945
Add cs operator version check in all namespaces
- cs operator in all cloudpak namespaces should be no less than 3.19.9
- cs operator in original common service namespace should be either 3.20+ or 3.19.9+
=> check cs operator version in all namespaces in isolate.sh

isolate.sh
1. Update the placement for `-A` with following error
```
[INFO] Cert manager not requested in scope, deploying...
operandrequest.operator.ibm.com/ibm-cert-manager-operator created
[INFO] Waiting for deployment cert-manager-operator to be running ...
flags cannot be placed before plugin name: -A
flags cannot be placed before plugin name: -A
[INFO] RETRYING: Waiting for deployment cert-manager-operator to be running ... (20 left)
```
2. Remove regular expression on `grep ^"cert-manager-operator"`
If we are using `grep ^${name}`, it will explicitly look for deployment named `cert-manager-operator`.
```
➜  ✗ name=cert-manager-operator                                                    
➜  ✗ oc get deploy -A --no-headers --ignore-not-found | egrep '1/1' | grep ${name}
cs-control …
```
=> update the placement for -A and remove regular exp

isolate.sh, preload_data.sh
- check cs operator version in all namespaces in `isolate.sh`
- cs operator in all cloudpak namespaces should be no less than 3.19.9
- cs operator in original common service namespace should be either 3.20+ or 3.19.9+
- Copy `secret/platform-oidc-credentials` and `configmap/platform-auth-idp` from original namespace to new services namespace
- Support Mac OS system for `isolated.sh`
- Also have cert manager operator pod existing in CS control namespace at the end of `isolated.sh` script
=> Scripts and Script-dev branch sync up for review

isolate.sh
If IBMLicensing CRD does not exist or IBMLicensing CR does not exists, skip the backup.
The value of `$licensing_exists` is `not found`
```
➜  ✗ ./isolate.sh --original-cs-ns cloudpak2-cs3-only --control-ns cs-control
...
[INFO] No licensing configmaps to migrate
error: the server doesn't have a resource type "IBMLicensing"
[INFO] licensing_exists: not found
[INFO] No ibmlicensing resources on cluster, skipping backup.
...
```
The value of `$licensing_exists` is `''`
```
➜  ✗ ./isolate.sh --original-cs-ns cloudpak2-cs3-only --control-ns cs-control
...
[INFO] No licensing configmaps to migrate
No resources found
[INFO] licensing_exists: 
[INFO] No ibmlicensing resources on cluster, skipping backup.
...
```
The value of `$licensing_exists` is not `""` or `not found`
```
➜  ✗ ./isolate.sh …
```
=> Check if IBMLicensing CRD exists or not

isolate.sh
Always check to see if the common service operator and odlm pods have been scaled back up after a failed isolate attempt. 
Scenario:
On first attempt, the isolate script successfully scales down the cs operator and odlm deployments to 0 and uninstalls cert manager. However, the script fails before it can rescale cs operator and odlm deployments so cert manager is not deployed again either. The subsequent attempt at running the isolate script will then fail immediately because no cert manager is deployed. This failure is also very obtuse as the error handling of this function is not strong enough.
What this pr does:
1. makes the early failure due to a lack of cert manager more clear
2. ensures cs operator and odlm are scaled to 1 before proceeding with the script. Wait for CS CR after …
=> check for cs op and odlm to be scaled after failure

preload_data.sh
Implementing the workaround for cpd quality repo issue 9990. 
Workaround is as follows:
- Scale down mongo operator in ibm-common-services to 0
-  edit icp-mongodb cm in ibm-common-services . Change the net.ssl.mode value to preferSSL from requireSSL
-  restart mongo pods in ibm-common-services one by one starting with icp-mongo-0. Delete the pod, let it come all the way ready, then move on to the next pod
-  clone the github repo for scripts branch, edit the preload_data.sh to remove the ssl parameters from the backup job definition [here](https://github.com/IBM/ibm-common-service-operator/blob/scripts/preload_data.sh#L317) and the restore job definition [here](https://github.com/IBM/ibm-common-service-operator/blob/scripts/preload_data.sh#L490)
-  remove the metrics container from the …
=> z specific changes to preload process

controllers/constant/odlm.go
For ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58807
Use k8s resources to create licensing operandBindInfo instead of alm-example, which allows us to create multiple opbi in different namespace
=> [LTSR] allow multiple opbi

controllers/constant/odlm.go
For ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58807
Use k8s resources to create licensing operandBindInfo instead of alm-example, which allows us to create multiple opbi in different namespace
=> [323] allow multiple opbi

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/setup_tenant.sh
Since we do the cert manager check in `pre-req` function, we need to create all namespaces before `check_cert_manager` for those which are first time passed into the script, otherwise, there will be `No resources found in operator_namespace` and failed in `[✘] Missing a cert-manager`
fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59207
test result：
```
[✔] Profile size is valid.
namespace/cloudpak-control-test created
[INFO] Waiting for project cloudpak-control-test to be created
[✔] Project cloudpak-control-test is created
namespace/cloudpak-data-testcreated
[INFO] Waiting for project cloudpak-data-test to be created
[✔] Project cloudpak-data-test is created
```
=> creating namespaces in pre-req

Dockerfile
golang:1.20.5 switched to a new base os debian `bookworm`, use `1.20.5-bullseye` to keep compatibility
=> Update golang image to bullseye base

controllers/cert-manager/podrefresh_controller.go
cherry pick from:https://github.com/IBM/ibm-cert-manager-operator/pull/340
If two certificates are mounted by one pod, and those two certificates are refreshed in the same minute, The second certificate restart will not trigger a pod restart because the time labels are the same.
=> [4.1] Make podrestart label more accurate

cp3pt0-deployment/uninstall_tenant.sh
Aim to fix the lint error
```
==> Linting results for ibmcase-bundle ibm-cp-common-services-bundle
[ERROR] case/ibm-cp-common-services/inventory/ibmCommonServiceOperatorSetup/installer_scripts/cp3pt0-deployment/uninstall_tenant.sh: internal URL "github.ibm.com" not allowed (NoInternalURLs)
```
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59196
=> remove internal URL for lint error

controllers/bootstrap/init.go, controllers/constant/odlm.go
Introduced a new function `ConcatenateConfigs` essentially combines the `Services` from two OperandConfig objects and returns the concatenated YAML representation of the modified OperandConfig.
for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57539
- It creates two OperandConfig objects: `baseConfig` and `insertedConfig` by unmarshaling the YAML templates using the applyTemplate function.
- It appends the `Services` from `insertedConfig` to the existing `Services` in `baseConfig`.
- It marshals the modified base object back to YAML format using json.Marshal.
- It returns the resulting YAML string and any error that occurred during the process.
test image: quay.io/yuchen_shen/cs_operator:split_opcon
delete origin OprandConfig and it will create a new one with the entries of …
=> [Bedrock 4.1] Implement Concatenating OperandConfig YAMLs

convert_to_multi_instance.sh, rollback-multi-instance.sh
Similar to the changes made for the conversion script here https://github.com/IBM/ibm-common-service-operator/pull/1171
Low priority given current use case for rollback and the scenario required for this to be a blocker but I ran into it in my testing of https://github.com/IBM/ibm-common-service-operator/pull/1227 so opened a pr before forgetting. 
Basically, we are looking if any of the cp namespaces have a zenservice that requested iam. If they do, we wait for iam to come ready in master ns and if they do not, we skip the wait.
Testing:
- setup a converted cluster with zen requested, create zenservice that sets `iamIntegration: false`
- ensure no other zenservices enable iam
- rollback the cluster
- verify the script completes and does not wait on iam to come ready
example cs maps for …
=> only wait for iam if it's requested during rollback

cp3pt0-deployment/common/utils.sh
Fix the issue that the `retries` goes to negative number
```
[INFO] Waiting for cs-operator CSV to be patched with NSS configmap
[INFO] RETRYING: Waiting for cs-operator CSV to be patched with NSS configmap (10 left)
[INFO] RETRYING: Waiting for cs-operator CSV to be patched with NSS configmap (9 left)
[INFO] RETRYING: Waiting for cs-operator CSV to be patched with NSS configmap (8 left)
[INFO] RETRYING: Waiting for cs-operator CSV to be patched with NSS configmap (7 left)
[INFO] RETRYING: Waiting for cs-operator CSV to be patched with NSS configmap (6 left)
[INFO] RETRYING: Waiting for cs-operator CSV to be patched with NSS configmap (5 left)
[INFO] RETRYING: Waiting for cs-operator CSV to be patched with NSS configmap (4 left)
[INFO] RETRYING: Waiting for cs-operator CSV to be patched …
```
=> Fix NSS Patch waiting condition

.github/workflows/approve_for_sync_up.yml, .github/workflows/open_pr_for_review.yml, .github/workflows/shell_linter.yml
Create several Github Actions
- Action will open a PR from `scripts-dev` branch to `scripts-adopter` branch when there is no PR already opened and there is a change in `scripts-dev` branch
- Action will make a push from `scripts-dev` branch to `scripts-adopter` branch when the PR from `scripts-dev` branch to `scripts-adopter` branch contains label `ok-to-sync` and does not contain any labels with `do-not-merge`.
- When the push is made by Action, the PR opened will show merged status, and two branches are totally synced.
- Action will run Lint check for scripts when PR is marked as `ok-to-test`
- This is the draft, and not functional right now. Will need more investigation on how to use it.
=> Update Github Actions for scripts

controllers/constant/odlm.go
fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58416#issuecomment-59591625
test image: quay.io/yuchen_shen/cs_operator:opreg_version
test result:
```
- channel: v4.0
installPlanApproval: Automatic
name: ibm-im-mongodb-operator-v4.0
namespace: simple-cloudpak2
packageName: ibm-mongodb-operator-app
sourceName: opencloud-operators
sourceNamespace: openshift-marketplace
- channel: v4.0
installPlanApproval: Automatic
name: ibm-im-operator-v4.0
namespace: simple-cloudpak2
packageName: ibm-iam-operator
scope: public
sourceName: opencloud-operators
sourceNamespace: openshift-marketplace
- channel: v4.0
installPlanApproval: Automatic
name: ibm-idp-config-ui-operator-v4.0
namespace: simple-cloudpak2
packageName: ibm-commonui-operator-app
scope: public
sourceName: …
```
=> update channels for all operators with suffix v4.0 pointing to v4.1 in OperandRegistry

cp3pt0-deployment/common/migrate_singleton.sh, cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/setup_singleton.sh
cases include: migrate, install, and upgrade
How to test migrate (isolated migration):
1. Set up cluster with installer operators and singletons at LTSR level
2. run `isolate.sh --original-cs-ns ibm-common-services --control-ns cs-control`
3. run `setup_singleton.sh --operator-namespace ibm-common-services --enable-licensing --license-accept`
4. Verify results:
- cert-manager v4 running in ibm-cert-manager, including operands
- cert-manager LTSR running in cs-control (only operator)
- licensing v4 running in cs-control
How to test migrate (in place migration):
1. Set up cluster with installer operators and singletons at LTSR level
2. run `setup_singleton.sh  --operator-namespace ibm-common-services --enable-licensing --license-accept`
3. Verify results:
- no control namespace exists
- …
=> enhance singleton script to handle all cases

cp3pt0-deployment/common/delegate_cp2_cert_manager.sh, cp3pt0-deployment/common/migrate_cp2_licensing.sh, cp3pt0-deployment/common/migrate_singleton.sh, cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/migrate_tenant.sh, cp3pt0-deployment/setup_singleton.sh, cp3pt0-deployment/setup_tenant.sh, cp3pt0-deployment/uninstall_tenant.sh, isolate.sh
- Add YQ variable for binary path
- Turn off Preview Mode by default
- Remove quotation mark for `arguments` when passing it into `${BASE_DIR}/setup_singleton.sh "--operator-namespace" "$OPERATOR_NS" "-c" "$CHANNEL" "--cert-manager-source" "$CERT_MANAGER_SOURCE" "--licensing-source" "$LICENSING_SOURCE" "--license-accept" $arguments`.
- Otherwise, `"$arguments"` will be phased as a long parameter `--enable-licensing -licensingNs cs-control` as `wildcard` instead of three dedicated and valid parameters.
- Only enable Licensing Migration when it is specified in `migrate_tenant.sh` parameter
- Add wait message for licensing instance to be present
- empty directory `/tmp/preview` for scripts other than `setup_tenant.sh`
=> migrate tenant adoption on singleton enhancement

isolate.sh
During the isolation for Bedrock v3.x - converting cluster single shared instance into dedicated instance, we will
- move `secretshare` deployment into control namespace as well.
- reset(delete and re-generated by cs operator) `Secretshare` CR, so it does not include the namespaces which has been excluded
Here is an example to reset `ibm-cpp-config` SecretShare CR, excluding namespaces which will be used for Bedrock v4.x.
```
apiVersion: ibmcpcs.ibm.com/v1
kind: SecretShare
metadata:
name: ibm-cpp-config
namespace: ibm-common-services
spec:
configmapshares:
- configmapname: ibm-cpp-config
sharewith:
- namespace: cp4d-1
- namespace: cp4d-2
- namespace: ibm-common-services
```
```
> ./isolate.sh --original-cs-ns ibm-common-services --control-ns cs-control
...
[INFO] Deleting secretshares in …
```
=> Remove SecretShare for ibm-cpp-config in isolation

controllers/bootstrap/init.go, controllers/constant/odlm.go, controllers/rules/rules.go, controllers/size/large_amd64.go, controllers/size/large_ppc64le.go, controllers/size/large_s390x.go, controllers/size/medium_amd64.go, controllers/size/medium_ppc64le.go, controllers/size/medium_s390x.go, controllers/size/small_amd64.go, controllers/size/small_ppc64le.go, controllers/size/small_s390x.go, controllers/size/starterset_amd64.go, controllers/size/starterset_ppc64le.go, controllers/size/starterset_s390x.go, docs/cloudpak-integration.md, testdata/actual.yaml, testdata/expected.yaml
for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57539
Add new entries of operators and services (im, im-mongodb, idp-config-ui and platformui ) with suffix `-v4.1` and channel `v4.1` into OperandRegistry and OperandConfig.
test image: quay.io/yuchen_shen/cs_operator:split_opcon
=> new entries of operators and services with suffix -v4.1

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/uninstall_tenant.sh
1. Allow user to input multiple namespaces
2. update common-service-maps after a tenant is uninstalled
3. when there is no `map-to-common-service-namespace` in the common-service-maps , cleanup control ns
=> Cleanup scritp enhancement

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml
How to test:
1. `export QUAY_REGISTRY=quay.io/<your username>`
2. `export REGISTRY=quay.io/<your username>`
3. edit manager.yaml with image `quay.io/<your username>/common-service-operator-amd64:dev`
4. `make bundle-manifests && make build-bundle-image && make run-bundle`
5. Verify cs-operator pod starts up, no errors in logs about forbidden permissions, and `ibm-odlm` sub is created (CSV not created because of temporary catalogsource)
=> removed all wildcard permissions

cp3pt0-deployment/common/utils.sh
This label should be patched together with `WATCH_NAMESPACE` ENV variable in common service operator deployment
=> Add NSS restart label when patching the deployment

preload_data.sh
A couple issues involving data migration with the secret copied over. This is the leading option to resolve them but there is still some discussion so will mark with a hold for now
=> don't copy oidc credential

cp3pt0-deployment/common/utils.sh
Currently, we are only checking if CSV exists in the namespace or not by doing following command, it does guarantee that a CSV is generated in the namespace. But it does not guarantee that this CSV is recorded in subscription status.
```
condition="${OC} -n ${namespace} get csv --no-headers --ignore-not-found | grep ^${operator_name}"
```
If the CSV is not recorded in subscription status, it will impact next function on `wait_for_nss_patch`.
This function gets CSV name from subscription status
```
sub_name=$(${OC} get subscription.operators.coreos.com -n ${namespace} -l operators.coreos.com/${package_name}.${namespace}='' --no-headers | awk '{print $1}')
csv_name=$(${OC} get subscription.operators.coreos.com ${sub_name} -n ${namespace} --ignore-not-found -o …
```
=> Wait for CSV shown up in subscription status

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/migrate_tenant.sh, cp3pt0-deployment/setup_singleton.sh, cp3pt0-deployment/setup_tenant.sh
For issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58967
Add some functions provide a set of operations for checking and correcting CatalogSource and their namespaces based on PackageManifest and channel information.
- The `check_singleton_catalogsource`ensures that the CatalogSource and namespaces for `CERT_MANAGER_SOURCE` and `LICENSING_SOURCE` are correct. It iterates over the predefined sources, checks and corrects the CatalogSource, and updates the variables accordingly. 
- The `check_cs_catalogsource` calls the `catalogsource_correction` function to check and correct the CatalogSource and namespace for the `ibm-common-service-operator` PackageManifest in the specified operator namespace.
- The `check_catalogsource` is used to check if a given CatalogSource is available …
=> support CatalogSource correction in setup_singleton and setup_tenant script

cp3pt0-deployment/setup_tenant.sh
We will try to delete CSV `ibm-common-service-operator-4.0.0` or `ibm-common-service-operator-v4.0.1` when those CSVs are not in Subscription's `installedCSV`
This is used to solve following issue:
- User would like to do following upgrade patch: v4.0.0 -> v4.0.1 -> v4.1.0
- Common Service operator is stuck at upgrading v4.0.0 -> v4.0.1, see following screenshot for details
- As a result, NamespaceScope operator could not be upgraded v4.0.0 -> v4.1.0 due to this error
```
constraints not satisfiable: @existing/test-mitigation//ibm-common-service-operator.v4.0.0 and @existing/test-mitigation//ibm-common-service-operator.v4.0.1 originate from package ibm-common-service-operator, subscription ibm-common-service-operator requires @existing/test-mitigation//ibm-common-service-operator.v4.0.1, …
```
=> mitigate intra-channel upgrade

convert_to_multi_instance.sh
Ran into an opportunity for enhancement while testing conversion script where an operand request was not updated to point to the new cs instance namespace for registryNamespace. This prevented ODLM in the new instance from reconciling the operandrequest as it tried to access the operandregistry in a namespace it did not have access to. Manually changing the registryNamespace value resolved the issue but I think this can be included in the conversion script. I have tested this on two different environments now (both amd64) successfully following this methodology:
- setup shared instance cluster with multiple cloudpak namespaces with operand requests
- convert cluster using this version of conversion script
- verify that operandrequests are updated correctly during script runtime
- verify …
=> Update operand requests' registryNamespace value to reflect new cs instance namespace

convert_to_multi_instance.sh, cp3pt0-deployment/common/utils.sh, force-uninstall.sh, health-check.sh, operator_checker_patch.sh, rollback-multi-instance.sh, rollback_to_eus.sh, uninstall-dedicated-cs-instance.sh, upgrade_to_continuous_delivery.sh, upgrade_to_continuous_delivery_airgap.sh
for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59727
Fix subscription listing in case of failure by using fully qualified sub-resource name `subscription.operators.coreos.com` for accuracy when `Open Cluster Management` is deployed in the same OCP cluster.
=> [4.2] using fully qualified sub resource name

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/bootstrap/init.go
for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/57188
- Determine whether the cluster is OCP by verifying the existence of an Infrastructure Custom Resource  named `cluster`.
- Give the cluster permission to API `config.openshift.io`
- Test image: quay.io/yuchen_shen/cs_operator:cluster_type
=> [4.2] detection of OCP cluster type

.github/workflows/open_pr_for_review.yml
- Add a `do-not-merge/hold` label when the PR for sync-up is created.
- Add a comment about the instructions on how to merge the PR.
=> Add label and comment for sync PR

velero/backup/licensing/label-licensing-configmaps.sh, velero/restore/restore-configmap.yaml, velero/schedule/schedule-common-services.yaml
This change is required for a doc update for 4.0 and includes changes to:
- update licensing script to take in namespace based on parameter
- backup and restore configmaps (specifically for cs maps)
=> Changes required for BR on 4.x

controllers/constant/storageclass.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59744
When we [specify `.spec.storageClass: <storage-class>` in CommonService CR](https://ibm.com/docs/en/cloud-paks/foundational-services/4.0?topic=options-configuring-foundational-services#storage-class), this configuration should be propagated to `common-service` OperandConfig
1. Install Common Service operator and ODLM in one namespace, DO NOT deploy OperandRequest
1. Update CommonService CR to specify the storageClass
```
metadata:
namespace: cloudpak-simple
spec:
license:
accept: true
operatorNamespace: cloudpak-simple
servicesNamespace: cloudpak-simple
storageClass: rook-cephfs
```
2. Wait for CommonService in `Succeeded` phase
3. …
=> Configure IM MongoDB storageClass via CS CR

api/v3/commonservice_types.go, bundle/manifests/operator.ibm.com_commonservices.yaml, config/crd/bases/operator.ibm.com_commonservices.yaml
ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59960
add marker `x-kubernetes-preserve-unknown-fields` to CommonService CR `.spec` and `.status` fields
=> [CD] Apply PreserveUnknownFields to CS CR status

api/v3/commonservice_types.go, bundle/manifests/operator.ibm.com_commonservices.yaml, config/crd/bases/operator.ibm.com_commonservices.yaml
ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59959
add marker `x-kubernetes-preserve-unknown-fields` to CommonService CR spec and status fields
=> [LTSR] Apply PreserveUnknownFields to CS CR status

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/migrate_tenant.sh, cp3pt0-deployment/setup_singleton.sh, cp3pt0-deployment/setup_tenant.sh
It is used to cover a scenario when user want to install operators from its default channel `.status.defaultChannel` set in operator packagemanifest.
And it is possible that different operator has different default channel. For example,
- User would like to install `ibm-common-service-operator` from its default `v4.3` channel.
- User would like to install `ibm-namespace-scope-operator` from its default `v4.2` channel.
Script will support to set operator subscription channel to null. e.g., `.spec.channel: null`.
When channel is set to `null` in subscription, OLM will automatically pick up the default channel in operator PackageManifest.
1. Deploy CatalogSource for Singleton Service(Cert-Manager and Licensing) and CS Services
2. Execute the script with channel specified to `null`
- …
=> Support picking default channel from bundle

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/setup_tenant.sh
This is to support CP4BA isolate upgrade scenario.
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59867#issuecomment-61557413
The original deployment is multiple CP4BA namespaces share the same CS instance in `ibm-common-services` namespace.
The original `common-service-maps` ConfigMap looks like following example
```
data:
- requested-from-namespace:
- cp1-ns
- cp2-ns
map-to-common-service-namespace: ibm-common-services
```
After isolation, the expected ConfigMap looks like following example. Each isolated tenant is a simple topology deployment.
```
data:
- requested-from-namespace:
- cp1-ns
map-to-common-service-namespace: …
```
=> Support simple topology upgrade from v3.x to v4.x

cp3pt0-deployment/setup_tenant.sh
ibm-common-service-webhook service will be removed in 4.2, so we remove the wait function
=> remove wait for ibm-common-service-webhook service

convert_to_multi_instance.sh
Accidentally made the key changes directly to scripts-dev here https://github.com/IBM/ibm-common-service-operator/commit/8f063eec349eb9c0948aad61ad9dfaebaecb9199. Made some additional changes to the info statements in this pr.
I can revert these changes and reopen this pr if that works better.
Testing:
- setup LTSR cluster ready for conversion to multi instance
- change installplanapproval value to manual in cs operator sub
- run conversion script, verify completion, look for info statement output from this pr
- verify cs sub in new cs instance has matching installplanapproval value (manual)
=> Update info statements

Makefile, api/v3/commonservice_types.go, bundle.Dockerfile, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/crd/bases/operator.ibm.com_commonservices.yaml, config/webhook/manifests.yaml
Can run `make manifests` and `make bundle-manifests` from now on to properly generate manifests/bundle (except need to revert the preserve-unknown-fields` change that happens)
=> updated descriptions in CRD fields

controllers/constant/odlm.go, controllers/rules/rules.go, testdata/actual.yaml, testdata/expected.yaml
issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/56920
- Introduced new entry `initMongoDB` into `Authentication` CR and update the corresponding size profile
- Removed `policydecision` CR from IM OperandConfig
=> introduce initMongoDB into Authentication CR

api/v3/commonservice_types.go, controllers/bootstrap/init.go, controllers/commonservice_controller.go, main.go
For issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/58293
Moving cluster type check into reconcile master CS CR
This PR partially fix for the scenario that NSS CR accidentally remove namespace from scope which will cause the cs-operator stuck in this initialization stage (0/1 pod not ready), and error msg ` Failed to verify cluster type unable to get: xxx/ibm-cpp-config because of unknown namespace for the cache`. This is because cs operator does not have permissions copy the ibm-cpp-config configmap to the namespace as it has been removed from NSS CR.
=> CS operator handles scoping changes

cp3pt0-deployment/setup_singleton.sh
Skip Licensing Service CatalogSource check when `--enable-licensing` is not passed into the script.
```
./cp3pt0-deployment/setup_singleton.sh --license-accept -c v4.2
[✔] CatalogSource ibm-cert-manager-catalog from openshift-marketplace CatalogSourceNamespace is available for ibm-cert-manager-operator in ibm-cert-manager namespace
[✗] There is a cert-manager Subscription already
```
=> Skip LS CatalogSource check when it's not enabled

convert_to_multi_instance.sh
Set and verify minimum *yq* version at 4.18.1 as this is the earliest version that supports the *yq* syntax in the script.
Prior to yq 4.18.1, example usage is as follows: 
`echo "yamlData: value" | yq e .yamlData`
From *yq* 4.18.1 and onwards "e" (short for eval) became the default command. This matches the usage in the script where "e" (eval) has been assumed to be the default command.
*yq* 4.18.1 release notes: https://github.com/mikefarah/yq/releases/tag/v4.18.1
Fixes #1445
=> Verify yq version in "convert_to_multi_instance.sh" script

cp3pt0-deployment/setup_tenant.sh
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59007
In the upgrade, if CommonService CRD does not contain  `x-kubernetes-preserve-unknown-fields: true`, operatorNS and serviceNS will be removed by k8s, so we need to double check it.
=> [4.1] check operatorNS and servicesNS in cs cr

Makefile, main.go
make run currently does not work because there is no webhook certificate in the tmp dir. This stops the webhook server from starting when using make run, because when testing the operator locally the k8s api server won't be configured to point to your local server anyway.
=> Fix make run by disabling webhook server

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/setup_tenant.sh
- Reduce the number of `oc get` command to relief workload on k8s apiServer
- Update log information to convey more accurate info
Test result
```
> ./cp3pt0-deployment/setup_tenant.sh --operator-namespace cp4ba-operator-3 --services-namespace cp4ba-service-3 --license-accept -c v4.2
...
commonservice.operator.ibm.com/common-service unchanged
[✔] Successfully patched CommonService CR in cp4ba-operator-3
...
[INFO] Waiting for CommonService CR common-service in cp4ba-operator-3 to be ready
[✔] CommonService CR in cp4ba-operator-3 is in Succeeded Phase
```
=> Enhancement for performance and user readiness

cp3pt0-deployment/setup_tenant.sh
Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/59687
This is the enhancement on `setup_tenant.sh` for all namespaces upgrade. When it is All Namespaces Upgrade, users are NOT allowed to configure either `--tethered-namespaces` or `--excluded-namespaces`
1. Install a old version of CS v4.0 or v4.1 in `openshift-operators` namespace
2. Execute `setup_tenant.sh` to trigger an upgrade to `v4.2`.
- Error path with `--tethered-namespaces` specified
```
> ./cp3pt0-deployment/setup_tenant.sh --operator-namespace openshift-operators --license-accept -c v4.2 --tethered-namespaces cp4i
[✔] Channel v4.2 is valid
[INFO] ibm-common-service-operator subscription exists, it is upgrade scenario
[✗] It is …
```
=> Not allow setting tethered and excluded ns for all namespace mode upgrade

controllers/constant/odlm.go
https://github.com/kubernetes/kubectl/issues/1411
The kubectl binary was updated the `edb-postgres-license-provider` image; this new version of kubectl lists and watches resources after deletion; before it just listed them. So we need additional rbac for the role.
=> Adding watch verb to edb-license-role

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manager/manager.yaml
fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60199
1. connection refused: https://stackoverflow.com/questions/48540929/kubernetes-readiness-probe-failed-error
2. context deadline exceeded (Client.Timeout exceeded while awaiting headers): https://stackoverflow.com/questions/70602906/kubernetes-pods-probe-failed-client-timeout-exceeded-while-awaiting-headers
field definition: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
=> changing readiness probe config to solve the failures on cs pod

cp3pt0-deployment/setup_singleton.sh
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60328
When run `setup_singleton.sh` script with `--yq`, `--yq` dose not work and still find default yq in $PATH.
How to test
- Execute the script wth `--yq` parameter specified
```
./cp3pt0-deployment/setup_singleton.sh --license-accept -c v4.2 --enable-licensing --yq ./bin/yq
[✔] ./bin/yq command available
./bin/yq
yq (https://github.com/mikefarah/yq/) version v4.35.1
[✔] Channel v4.2 is valid
```
=> enable --yq option in setup_singleton.sh

controllers/constant/odlm.go
issue requested: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60159
test image: quay.io/yuchen_shen/cs_operator:keycloak_config
could be check in `cs-keycloak-0` and `keycloak-edb-cluster-1` pods
- Unsupported field introduction of `KeyCloak` configuration: https://github.com/vmuzikar/keycloak/blob/f19b00bd7204f33e6bc3fc8b3775f2accee1777d/docs/guides/operator/advanced-configuration.adoc#unsupported-features
- `Cluster` resource configuration is the same as the example shows in: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes
=> config keycloak resources

Dockerfile, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/webhook/manifests.yaml, controllers/webhooks/commonservice/validatingwebhook.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60354
How to test
We could verify the fix on existing daily build
1. Deploy CS 4.2 from daily build
2. Find the validating webhook configuration deployed by OLM
```
> oc get validatingwebhookconfiguration -l olm.owner=ibm-common-service-operator.v4.2.0,olm.owner.namespace=<operator-namespace>
NAME                         WEBHOOKS   AGE
vcommonservice.kb.io-qzhs7   1          4d22h
```
3. Edit this webhook configuration
```
oc edit validatingwebhookconfiguration vcommonservice.kb.io-qzhs7
rules:
- operations:
- CREATE
- UPDATE
apiGroups:
- operator.ibm.com
apiVersions:
- v3
resources:
- commonservice --------> commonservices
scope: '*'
matchPolicy: Equivalent
```
4. Create a new CS CR in tenant scope
5. Verify the common service …
=> add plural for CS CR in webhook configuration

controllers/constant/fipsEnable.go, controllers/render_template.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60244
When Common Service Operator composes the OperandConfig template, it merges different configurations from all CommonService CRs in the tenant scope
```
> oc get commonservice
NAME                    AGE
common-service          6d9h
example-commonservice   5d14h
```
For the FIPS enablement, the Common Service CR has a parameters to turn on or turn off FIPS enablement.
```
- apiVersion: operator.ibm.com/v3
metadata:
name: example-commonservice
namespace: configure-test
spec:
fipsEnabled: false(or true)
```
For each Common Service CR, it has FIPS enablement turned off by default, meaning following three configurations are equivalent in CommonService CR
- `fipsEnabled: false`
- …
=> Fix FIPS enablement in 4.x release

velero/schedule/zen5-br-scripts-cm.yaml
- This is a fix for lint error `NoInternalURLs ` failed on travis: https://v3.travis.ibm.com/github/IBMPrivateCloud/charts/jobs/6194220#L568
- Introduction in Playbook: https://playbook.cloudpaklab.ibm.com/code-standards-linting/code-standards-libary/standards-index/nointernalurls/
- We have the same issue fixed before: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59196
- need to remove internal URLs: `github.ibm.com` in our scripts
=> remove internal URLs in zen5 br ConfigMap

cp3pt0-deployment/migrate_tenant.sh
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60328#issuecomment-63332984
`migrate_tenant.sh` does not pass `yq` path into `setup_singleton.sh` script
Execute the script wth `--yq` parameter specified
```
./cp3pt0-deployment/migrate_tenant.sh --operator-namespace ibm-common-services --enable-licensing --license-accept -c v4.2 --yq ./bin/yq
...
[✔] ./bin/yq command available
[✔] Channel v4.2 is valid
...
```
=> fix yq path configuration in migrate_tenant.sh

backup_restore_mongo/backup_restore_mongo.sh
noticed while testing https://github.com/IBM/ibm-common-service-operator/pull/1503. These changes make it possible to run just the backup by itself without specifying a restore namespace
=> make sure script can run when restore namespace not specified

cp3pt0-deployment/setup_singleton.sh, preload_data.sh
For issue 59713, added a wait for cert manager operand webhook to come ready to setup singleton and then a smoke test where it tries to create a test issuer and certificate. This was added to the end of the script. Added just the smoke test to preload data's prereqs section so the script will error out if these items cannot be created
Testing setup singleton:
- run setup singleton to fresh install cert manager
- verify script completes and the success message "Cert manager is ready." appears at the end of the script
testing preload:
- before installing cert manager, run the script
- verify the script errors out during prereqs with the message: "Failed to create test issuer. Verify cert manager is installed and ready on the cluster then re-run the preload script."
- Install cert manager
- …
=> add cert manager smoke test to setup singleton and preload data

cp3pt0-deployment/setup_tenant.sh
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60615
- If the user provides `v4.2` or a higher channel version when running the script, it will choose the NSS operator from the `v4.2` channel and select the CS operator from the `v4.2` channel or any version higher.
- Conversely, if the user specifies the parameter -c with `v4.1` or a lower version when executing the script, it will select the NSS operator from the same channel as the CS operator channel.
=> mapping between CS operator and Namespace Scope operator channel

controllers/bootstrap/init.go, controllers/constant/odlm.go
This task is used to address issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60688
1. It enables leaf certificate with dns name `cs-keycloak-service` for keycloak to secure the connection
2. This leaf certificate will be used to create a re-encrypted Route as well
3. It also refreshes KeyCloak CR with annotation because KeyCloak CR will not recover by itself when tls secret is missing.
1. Deploy dev build CPFS as usual by creating common service operator subscription, wait for Common Service Operator and ODLM to be installed.
2. Delete existing OperandConfig `common-service` in this tenant
3. Replace the image in Common Service operator CSV to `quay.io/daniel_fan/common-service-operator-amd64:dev`, and set ImagePullPolicy to `Always`
4. Create OperandRequest to request …
=> enable leaf certificate for Keycloak

controllers/constant/odlm.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60682
Always install KeyCloak Operator in Own namespace mode because KyeCloak operator does not support All namespace mode, and does not separation of operator and operand.
- When CPFS is installed in Own namespace mode, KeyCloak operator is installed in the same namespace as CPFS operator
- When CPFS is installed in All Namespaces mode, KeyCloak operator is installed as Own Namespace Mode in `servicesNamespace` which is typically `ibm-common-services` namespace.
=> Install keycloak in serviceNs for All Ns mode

velero/backup/mongoDB/mongo-backup.sh, velero/restore/mongoDB/mongo-restore.sh, velero/schedule/mongodb-backup-deployment-z.yaml, velero/schedule/prep-mongo-br-z.sh
Mongodump and mongorestore commands cannot run on s390x without tweaks so this PR makes those necessary tweaks. We will not be able to run the velero br procedure completely automatically at the moment due to the need to scale down mongo operator and change `requiressl` connection setting to `preferssl` since the dump and restore commands do not support ssl on z.
Tested as part of https://github.com/IBM/ibm-common-service-operator/pull/1520. This pr also replaces #1520, more info can be found there.
=> add necessary files for velero br on z

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/webhook/manifests.yaml, controllers/webhooks/operandrequest/mutatingwebhook.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60357
When `FailurePolicy: Fail` is set, the error will immediately show up if common service operator pod is unavailable and there is a update on OperandRequest.
```
error when patching "./sec_operandrequest.yaml": Internal error occurred: failed calling webhook "moperandrequest.kb.io": failed to call webhook: Post "https://ibm-common-service-operator-service.cs2.svc:443/mutate-operator-ibm-com-v1alpha1-operandrequest?timeout=10s": no endpoints available for service "ibm-common-service-operator-service"
```
When `FailurePolicy: Ignore` is set, there is no error on updating OperandRequest even if common service operator pod is unavailable
```
> oc apply -f operandrequest.yaml
operandrequest.operator.ibm.com/example-service …
```
=> Update FailurePolicy for MutatingWebhook

controllers/constant/odlm.go
This is to address issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60804
We move KeyCloak BindInfo deployment and setup Job into operator namespace so it has the required SA and permission to generate ConfigMap.
1. Create `ibm-common-services` and `cp4i` namespace.
2. Deploy dev build CPFS as usual by creating common service operator subscription in `openshift-operators` namespace, wait for Common Service Operator and ODLM to be installed.
3. Delete existing OperandConfig and OperandRegistry `common-service` in this tenant
4. Replace the image in Common Service operator CSV to `quay.io/daniel_fan/common-service-operator-amd64:dev`, and set ImagePullPolicy to `Always`
5. Create OperandRequest to request keycloak-operator in `cp4i` namespace, waiting for KeyCloak to be …
=> Move KeyCloak BindInfo and Setup job to OperatorNs

velero/schedule/zen5-br-scripts-cm.yaml, velero/schedule/zen5-clusterrole.yaml, velero/schedule/zen5-clusterrolebinding.yaml, velero/schedule/zen5-sa.yaml
Add labels to the permissions files so they can be carried over to the new cluster, add errexit and errtrace to the scripts so if they fail for one reason or another, they fail both the script and the velero process. Otherwise the velero output may still incorrectly be "completed".
=> add labels to zen5 permissions, add errexit to zen5 scripts

velero/backup/cert-manager/label-cert-manager.sh
Add logic to specifically label secrets, certificates, and issuers using cert-manager.io version of the CRD to make sure no secrets fall through the cracks. Also included: labeling the custom secrets for the custom routes created for iam and zen.
=> label cert-manager.io specific resources and custom route secrets

cp3pt0-deployment/setup_tenant.sh
for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60519
1. After remove wildcard * permissions in NSS CSV PR: https://github.com/IBM/ibm-namespace-scope-operator/pull/285
2. Creating a Role named `nss-managed-role-from-<operator-namespace>` and RoleBinding with granted permissions for NSS operator instead in the operator namespace
3. Introducing a new flag `--with_minimal_rbac` that allows users to enter available `path` or `skip` to choose whether they want to provide a role template or skip the role created by the script
=> add reduced rbac for nss in operator namespace

velero/schedule/zen5-br-scripts-cm.yaml
Possible that the subsequent command is run before the deployments are fully scaled down so we need to wait for them to be gone.
=> wait for deployments to fully scale down

velero/backup/cert-manager/label-cert-manager.sh, velero/schedule/zen5-backup-deployment.yaml
Zen restore can take a long time depending on a couple factors, better to give a timeout it won't hit prematurely. We need to label the secrets used for either the iam custom route or the zen custom route since they may or may not be labeled correctly. We also need to make sure the script can gracefully handle when these secrets/configmaps do not exist.
=> bump up zen restore timeout, add error handling for custom secrets

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
related odlm basic permission changes : https://github.com/IBM/operand-deployment-lifecycle-manager/pull/989
grant nss operator to list packagemanifest resource
=> grant packagemanifest permission to namespace scope operator

controllers/constant/odlm.go
Please merge this PR ONLY AFTER ODLM's PR is merged: https://github.com/IBM/operand-deployment-lifecycle-manager/pull/990
1. KeyCloak Route is created by ODLM directly, and support value reference on following fields.
- `spec.host`: Optional, user could specify custom hostname by updating `.data.keycloak_route_name` in `ibm-cpp-config` ConfigMap
- `spec.tls.caCertificate`, `spec.tls.certificate`, `spec.tls.key`: Optional, user could specify custom certificate by creating secret `keycloak-custom-tls-secret`
- `spec.tls.destinationCACertificate`: Required, it is referencing the CA cert from `cs-keycloak-tls-secret`
2. KeyCloak CR is created by ODLM, and support value reference on following fields.
- `spec.hostname.hostname`: Required, it is reference the `.spec.host` from `keycloak` Route
- …
=> Update OperandConfig with value reference

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
New resources `volumesnapshots` permission was added in `cloud-native-postgresql.v1.18.7`,  need to grant this permission to NSS in order to create EDB role in service namespace
=> new volumesnapshots resources permission from cloud-native-postgresql

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/setup_singleton.sh
1. As the channel of singleton services are different from CPFS, when printing out the error message with given channel version that could better to indicate whether the wrong channel caused the correct CatalogSource to not be found. 
e.g. 
`[✘] No CatalogSource is available for ibm-cert-manager-operator in ibm-cert-manager namespace in the given channel v4.3`
2. Cert-Manager smoke test, the test-issuer should be created in a existent namespace. When user install a community Cert Manager, they do not need to create `CERT_MANAGER_NAMESPACE`, so using the cert-manager-webhook namespace instead of cert manager ns to create a test-issuer
To avoid error:
```
Smoke test for Cert Manager existence...[0m
[INFO] Creating following issuer:
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
name: …
```
=> script enahcements (catalogsource correction error msg + cert-manager smoke test namespace)

controllers/bootstrap/init.go, controllers/constant/cloudNativePostgresql.go, controllers/constant/odlm.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59255#issuecomment-66165971
- Common Service Operator will create a ConfigMap as postgresql Image list for EDB CASE bundle 4.18.0.
- This is used to simulate https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60147 that the ConfigMap will be part of EDB operator installation in the future release.
- The detailed ConfigMap is following - might change some digests based on EDB CASE bundle changes
```yaml
apiVersion: v1
metadata:
name: cloud-native-postgresql-image-list
namespace: <CPFS operator namespace>
data:
ibm-postgresql-15-operand-image: icr.io/cpopen/edb/postgresql:15.4@sha256:7ae65a0e9f172a6882b29a629d2f727aa9b6114c82eb116df5a934bf2797c17c
ibm-postgresql-14-operand-image: …
```
=> Expose postgresql Image list via ConfigMap

controllers/constant/storageclass.go
Extending https://github.com/IBM/ibm-common-service-operator/pull/1385 with the storage class configuration of the EDB-Keycloak.
One thing I am not 100% sure whether the proposed change does not entirely override the `Cluster`'s `.spec.storage` , incl. `.spec.storage.size`, or just patches / adds the `.spec.storage.storageClass` .
EDB Cluster CR storageClass configuration reference https://www.enterprisedb.com/docs/postgres_for_kubernetes/latest/storage/#configuration-via-a-storage-class
=> Add storage class configuration for EDB-Keycloak

controllers/bootstrap/init.go, controllers/constant/odlm.go
Based on @Jamstah 's [solution]( https://github.com/IBM/ibm-common-service-operator/compare/master...Jamstah:remove-bindinfo-deployment?expand=1), leveraging templating system to compose the ConfigMap of KeyCloak Route and Service, and share the ConfigMap via OperandBindInfo.
The final ConfigMap for Keycloak Route and Service generated by OperandBindinfo are
```yaml
apiVersion: v1
metadata:
name: keycloak-bindinfo-cs-keycloak-route
data:
BACKEND_SERVICE: cs-keycloak-service
HOSTNAME: 'https://keycloak-yesy-jsonpath.apps.installer-cp3pt0.cp.fyre.ibm.com'
TERMINATION: reencrypt
---
apiVersion: v1
metadata:
name: keycloak-bindinfo-cs-keycloak-service
data:
CLUSTER_IP: 172.30.217.111
PORT: '8443'
SERVICE_ENDPOINT: …
```
=> implement Keycloak BindInfo via template reference

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/migrate_tenant.sh
When cs-operator is down, the webhook configuration block the update of CS CR, need to be deleted before updaing
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61091#issuecomment-66388356
=> delete webhook configuration when cs pod down

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Zen parallel job permission is newly added into [Zen (5.1.0-125), Operator (5.1.0) ](https://ibm-cloudplatform.slack.com/archives/G01KTNY2ZCL/p1699296823695459) build, we woule need to add it into nss-managed-role yaml file.
According to zen permission PR: https://github.ibm.com/PrivateCloud/zen-operator/pull/274/files#diff-4c1776e6be6e452efc221ae18247856221bd4ff348d8d1bff8d2ffa92035ad2cR388
issue: https://console-openshift-console.apps.lundong-isolate-upgrade.cp.fyre.ibm.com/dashboards
=> grant zen parallel job permission to Namespace Scope

controllers/constant/odlm.go
Missing . means this comes out as a string instead of reading from the route as expected.
=> Missing . in objectRef path

velero/schedule/zen5-br-scripts-cm.yaml
Update the logic for grabbing extension names to be more consistent based on feedback from CP4BA, exact same as https://github.com/IBM/ibm-common-service-operator/pull/1598
=> update zen extension logic based on feedback

controllers/constant/odlm.go
The default Keycloak Realm name should follow the standard name of IBM Cloud Paks, i.e. with the white space characters
See the logon screen after the change:
Resolves https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61144
=> Update default Keycloak realm name to follow the Cloud Pak naming convention

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/migrate_tenant.sh
In all namespace migration, as all nss CR will be cleared after running the migrate_tenant script, which causes fail to delete ingress operator and operand due to no `namespace-scope` ConfigMap found. We will create a new nss configmap back in `ibm-common-services` namespace only for `ingress` operator deletion.
=> create nss configmap in cs namespace for all ns upgrade

controllers/bootstrap/init.go, controllers/commonservice_controller.go, controllers/operandconfig.go, controllers/webhooks/commonservice/validatingwebhook.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61097
**Currently** the CS operator will pause and NOT create CS CR until user creates `ibm-common-services` namespace.
**The expectation** is to have CS operator creating the CS CR, pause the further installation until user creates `ibm-common-services` namespace.
The main purpose of this change is to provide a interface(CS CR) for CP4I to read the `servicesNamespace` aka `ibm-common-services`, to ask the user to create `ibm-common-services` namespace.
1. Deploy CS daily CD CatalogSource
2. Install Cert-Manager as dependency
3. Install CS operator in `openshift-operators` namespace as All Namespace Mode
4. We will observe the warning message in CS operator pod log, and no CS CR is created in `openshift-operators` namespace
``` …
```
=> Create default CR even services Ns does not exist for all namespace mode, move services Ns check into reconciliation logic

controllers/constant/odlm.go
When Keycloak is GAed, it will be included in `redhat-operators` CatalogSource.
Removing `redhat-operators` from excluded CatalogSource list, so that ODLM could discover and reference Keycloak from `redhat-operators` CatalogSource.
After building new image and deploy in the cluster, CS operator renders a OperandRegistry whose excluded list does not contain `redhat-operators`.
```yaml
kind: OperandRegistry
metadata:
annotations:
excluded-catalogsource: >-
certified-operators,community-operators,redhat-marketplace,ibm-cp-automation-foundation-catalog,operatorhubio-catalog
version: 4.3.0
resourceVersion: '232789769'
```
Also, I manually edit OperandRegistry to include one operator available in `redhat-operators` CatalogSource., in …
=> remove redhat-operators from excluded list

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/setup_singleton.sh
- the graceful upgrade method by saving subscription yaml first caused a regression because the opreq-control label still existed, which causes ODLM v3 to still manage it even after v4 migration
=> fixed licensing upgrade regression caused by opreq

cp3pt0-deployment/common/utils.sh
because yq was not modifying in place
=> fixed opreq-control label not being deleted

isolate.sh
Issue: https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/14099
CPD has a migration scenario that the previous CPD does not have IAM installed. As a result, during the isolation process, there is no ManagementIngress CRD exists in the cluster. We will skip checking for ManagementIngress CR if it does not exist in the cluster.
```
✗ ./isolate.sh --original-cs-ns ibm-common-services --control-ns cs-control --excluded-ns wkc
[✔] Commonservice common-service created in ibm-common-services.
[INFO] ibm-management-ingress-operator already exists in CS CR .spec.services, updating it ...
[✔] Commonservice common-service updated in ibm-common-services for management ingress CR.
[INFO] Waiting for operandconfig common-service in namespace ibm-common-services to be created ...
[INFO] …
```
=> skip mgmt_ingress CR check when it does not exist

velero/schedule/zen5-role.yaml, velero/schedule/zen5-rolebinding.yaml
Same as https://github.com/IBM/ibm-common-service-operator/pull/1639
reduces overall permissions for zen 5 backup
=> update cluster role to role and remove some permissions

velero/schedule/mongodb-backup-deployment.yaml, velero/schedule/zen-backup-deployment.yaml, velero/schedule/zen5-backup-deployment.yaml
move the clean up of backups to the beginning of the next backup instead of immediately after. This way, the backup is accessible between runs and out of the way when attempting another backup.
=> change when housekeeping command is run

velero/schedule/zen5-br-scripts-cm.yaml
--ignore-not-found cannot be used on the scale command as it will cause an error
=> remove invalid option in script

velero/schedule/zen5-br-scripts-cm.yaml
Needed to add a space before `--ignore-not-found` as the string was being included in the replica value for zen core api
Changed the check from directly grabbing zen-watchdog to grepping for it to prevent an error from being output.
=> resolve syntax error, change check command

controllers/constant/odlm.go
Corrected wrong default size value of EDB KeyCloak resrouce 
Fix for two issue:
- https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60915#issuecomment-67033251
- https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61204
=> align default EDB keycloak size profiles with starterset

velero/schedule/zen5-br-scripts-cm.yaml
This message being an error will prevent the script from cleaning up the cluster after running. A warning is better suited for this situation as it denotes that the zen extensions were still not found (which may or may not be an issue) while still allowing the script to clean up after itself.
=> change message from error to warning for more consistent results

controllers/constant/odlm.go
Set sensible defaults for the realm security.
Addresses https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61319
These can be overridden by users because the KeycloakRealmImport CR only adds the realm once and then doesn't reconcile except on delete.
=> Add default realm security settings

controllers/commonservice_controller.go, controllers/recocile_pause.go
Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/59018
New maintenance mode is introduced for the CS operator that is able to pause the reconciliation of CommonService CRs, allow user/operator to perform additional maintenance, and resume the reconciliation after such maintenance mode is released.
To pause reconciliation of the CS custom resources, an annotation can be added to the CommonService instance. 
```yaml
metadata:
annotations:
commonservices.operator.ibm.com/pause: 'true'
commonservices.operator.ibm.com/self-pause: 'true'
```
- The value of the annotation `<api>/pause` and `<api>/self-pause` can be `true` and `false`.
- If the value is `true`, the reconciliation of the CR will be paused.
- If …
=> introduce basic maintenance mode into CS operator

controllers/common/util.go, controllers/commonservice_controller.go, controllers/scopewatcher_controller.go
Create a new dedicate controller to perform the self-isolation process, the reconciliation will only be triggered by `common-service-maps` ConfigMap in `kube-public` namespace.
=> Create a dedicate controller for self-isolation

controllers/common/util.go, controllers/scopewatcher_controller.go
Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61346
- Enable maintenance mode for CS CR at the beginning of self-isolation process
- Disable maintenance mode at the end of self-isolation
=> Enable and Disable CS CR reconciliation in self-isolation

controllers/constant/secretshare.go
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58117
change `service` namespace to `kube-public` in secretshare cr yaml.
=> remove `service` namespace in secretshare default cr yaml

controllers/bootstrap/init.go, controllers/common/util.go, controllers/commonservice_controller.go, controllers/scopewatcher_controller.go
Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61347
- Patch CommonService CR with `multiInstanceEnabled: false` to disable mgmt-ingress for Route changes.
```bash
oc get commonservice common-service -n <operator-namespace> -o json |
jq '.spec.services |= (if type == "array" then map(if .name == "ibm-management-ingress-operator" then .spec.managementIngress.multipleInstancesEnabled = false else . end) else . end // []) |
if (.spec.services | map(.name == "ibm-management-ingress-operator") | any == false) then .spec.services += [{"name": "ibm-management-ingress-operator", "spec": {"managementIngress": {"multipleInstancesEnabled": false}}}] else . end' |
oc apply -f -
```
- Delete the existing OperandConfig and OperandRegistry CRs in `ibm-common-services` namespace.
```bash
oc …
```
=> Re-construct CP2 tenant scope in self-isolation

controllers/commonservice_controller.go
issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61446
CS operator v3 will [skip the reconciliation for the CS CR which is not in the current scope.](https://github.com/IBM/ibm-common-service-operator/blob/91e0f67dfccbed9f64438d9c48d260e8962e4dd1/controllers/commonservice_controller.go#L108), avoid any changes or update to that CR.
=> Skip reconciliation if CR is not in tenant scope

Makefile, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/bootstrap/init.go, controllers/common/util.go, controllers/commonservice_controller.go, controllers/scopewatcher_controller.go
- Update isolation condition:
- Continue reconciliation when CS CR has paused annotation
- Scale Down ODLM at the beginning to avoid it from reconciliation v4 tenant
- Migrate Licensing and Cert manager component from master namespace to control namespace
=> Update isolation condition

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/bootstrap/init.go, controllers/commonservice_controller.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61543
- Add delete verb for `ConfigMaps` resources
- set/overwrite UID and resourceVersion when restoring LS CRs
=> update UID and resourceVersion when restoring LS CRs

controllers/operandconfig.go
To fix issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61204
Update the code to not skip loop when ONLY `spec` field is `nil`.
Otherwise, it will not able to reconcile `resources` field when `spec` field is `nil`
```
for _, opService := range opconServices {
// Skip loop if spec is nil
if opService.(map[string]interface{})["spec"] == nil {
continue
}
update_spec_field
// update resources when resources is NOT nil
if opService.(map[string]interface{})["resources"] != nil {
update_resources_field
}
}
```
```
for _, opService := range opconServices {
// update spec when spec is NOT nil
if opService.(map[string]interface{})["spec"] != nil {
update_spec_field
}
// update resources when resources is NOT nil
if opService.(map[string]interface{})["resources"] != nil { …
```
=> fix: get extreme value on resources field when spec field does not exist

controllers/bootstrap/init.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61558
When `common-service-maps` ConfigMap does not contain label `operator.ibm.com/managedByCsOperator: true`, any creation, deletion, update and other generic event on the ConfigMap will not trigger the reconciliation of v3 LTSR self-isolation.
We need to make sure v4 operator add this label into the ConfigMap when v4 operator updates or creates `common-service-maps` ConfigMap.
=> Add managedByCsOperator label for ConfigMap

velero/schedule/zen5-br-scripts-cm.yaml
Change Delete API call for zen extensions from `DELETE /v1/extensions/<id>` to  `DELETE /v1/internal/extensions/{source_id}` based on feedback from the zen team
=> change delete api call based on feedback from zen

velero/schedule/zen5-br-scripts-cm.yaml
Mirror #1700 in scripts-dev
Change Delete API call for zen extensions from DELETE /v1/extensions/<id> to DELETE /v1/internal/extensions/{source_id} based on feedback from the zen team
=> change delete api based on feedback from zen

controllers/constant/odlm.go
zen 5.1.1 is now pushed to channel 4.4 so we need to change the value for zen from 4.3 to 4.4 so we are using the latest
=> update zen channel to 4.4

cp3pt0-deployment/common/migrate_singleton.sh, isolate.sh
Ref: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61539
Updates for the licensing case: 
- If `spec.sender ` is configured in LS instance, set a template for sender configuration with url pointing to the IBM LSR docs
- And create an empty secret `ibm-license-service-reporter-token` in `LS_new_namespace` to ensure that LS instance pod will start
=> Licensing - covering LSR sender scenario 61539

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60327
To prevent installation blocks in the absence of cert-manager, removed OLM dependency on cert-manager APIs from cs-operator.
=> Remove cert-manager API dependency

preload_data.sh
In late October, working alongside the mongo, Power, and Z teams, the mongo image was updated to include mongodump and mongorestore binaries capable of connecting to mongo via ssl connection on Power and Z clusters (which was previously not supported). This represented a significant security improvement. However, this requires specific versions of the mongo image that may not be guaranteed to exist on a cluster. There are further complications when dealing with airgap clusters (SERT raised a SEV1 in December because the script stopped functioning when it could no longer pull the mongo image on an airgap cluster). We did not see this problem previously because we did not specify the mongo image used; we just used the existing image on the cluster.
Leaving the script as is (ie not merging …
=> revert changes to account for z and power binaries

convert_to_multi_instance.sh, isolate.sh
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61627
1. Patching OperandConfig and CommonService is sufficient to ensure that mgmtIngress CR will be updated with `multipleInstancesEnabled: false` by ODLM when mgmtIngress CR exists.
2. Conditional patching resources with `multipleInstancesEnabled: false`.
- It only happens when we are converting Bedrock instance from a cluster shared instance to a dedicated instance.
- It would not enable `multipleInstancesEnabled: false` when Bedrock instance was already in dedicated mode before running `isolate.sh`
- Test on a Bedrock 3.x which is in cluster shared mode, and running `isolate.sh` to convert it to a dedicated mode.
```bash
./isolate.sh --original-cs-ns ibm-common-services --control-ns cs-control
... …
```
=> Patching mgmtIngress CR only when converting from shared to dedicated mode

preload_data.sh
A couple changes needed to be made to resolve the problem found in SERT issue 60021
- The previous variable used in the check was not set prior to being used, changed to use the existing `stgclass` variable instead
- There was no check on the restore side, only the backup. Copy and pasted the check on the backup side to also be on the restore side
- noticed an unrelated problem with claim ref repopulating before deleting the old pvc. Changed the claimref clearance to after the old pvc was deleted
Tested the script beginning to end by creating a new storageclass `rook-cephfs-test` which was a copy pasted `rook-cephfs` but changed the `volumeBindingMode` to `WaitForFirstConsumer` which should be representative of the problem experienced in the issue.
Waiting to see if SERT can produce an …
=> Resolve issue with WaitForFirstConsumer volumeBindingMode

controllers/constant/odlm.go
For Bedrock 4.4 January release, Zen 5.1.x will use the same `v4.3` channel as Zen `5.1.0` uses.
- Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61522
- Slack discussion: https://ibm-cloudplatform.slack.com/archives/G01KTNY2ZCL/p1704749857268399?thread_ts=1702932338.968739&cid=G01KTNY2ZCL
=> downgrade zen channel back to v4.3

controllers/bootstrap/init.go, main.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60327
1. Delete Cert-Manager Operator in the cluster if it is present in cluster
2. Check if Kind Certificate is present in cluster
```
oc get crd | grep certificates.cert-manager.io
```
3. Delete the Kind Certificate if it is present in cluster
```
oc delete crd certificates.cert-manager.io
```
4. Installing cs operator v4
5. Check cs CSV status, and it will be not showing
```
group: cert-manager/v1.io
kind: Certificate
message: Native API does not exist 
```
6. Observe the error msg during the cs operator reconciling
```
2024-01-08T21:45:34.643Z	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "Certificate.cert-manager.io", "error": "no matches for kind \"Certificate\" in …
```
=> disable cert-manager related functions

hack/keycloak-themes/theme/cloudpak/account/theme.properties, hack/keycloak-themes/theme/cloudpak/admin/theme.properties
Bugs from importing from my repo - I was using cloud-pak as the name and the right name is cloudpak.
This enables the theme to show up for admin/account consoles.
=> Fix bug in theme - switch from cloud-pak to cloudpak name

cp3pt0-deployment/migrate_tenant.sh, cp3pt0-deployment/setup_singleton.sh, cp3pt0-deployment/setup_tenant.sh, isolate.sh
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61784
Each execution of script will re-direct the preview file into different directory. So it will support different non-root users to run the same script under on same Linux based client.
After executing `setup_singleton.sh` multiple times, this is the files and directories under `/tmp` folder
```
> ls -r /tmp/*-preview
/tmp/setup-singleton-20240110105758-preview:
operatorgroup.yaml
/tmp/setup-singleton-20240110105549-preview:
operatorgroup.yaml issuer.yaml        certificate.yaml
/tmp/isolate-20240110100317-preview:
```
=> Update preview dir path to support multi non-root user

controllers/constant/odlm.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61807
When CommonService is deployed in All Namespace mode or separation of control and data, `postgresql-operator-controller-manager-config` secret will be in operator namespace. And EDB CR is in a different namespace which is services namespace.
=> Reference EDB License Secret from OperatorNamespace

controllers/constant/odlm.go
Fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61198
test image: quay.io/yuchen_shen/cs_operator:keycloak_lint
- Add ephemeral storage limit and request in `Keycloak` CR
- Add nodeAffinity for Keycloak pod.
=> fix lint error for KeyCloak CR

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/constant/odlm.go
Updated default OperandConfig so that Keycloak uses OCP service serving cert instead of generating Certificate from cert-manager
- prefixed intermediary resources like the Service and service cert secret name with `cpfs-opcon-`, open for feedback to change name
- Route and Secret containing certs both still have the same name as what was GA-ed, so backwards compatibility maintained
Also updated role.yaml to properly generate CSV
How to test:
Pre-reqs:
1. pull secret for EDB and EDB catalogsource
Steps:
1. Install cs-operator from GA
2. Edit the image in CSV to `quay.io/henry_h_li/common-service-operator-amd64:dev` or build your own image from this PR
3. Delete the default OperandConfig and wait for it to be re-created
4. Create OperandRequest for keycloak
```
apiVersion: …
```
=> updated opcon so Keycloak uses OCP certs

controllers/constant/odlm.go
When CS upgrade from 4.3 to 4.4, the owner of `cs-keycloak-tls-secret` was changed.
The owner of secret was `cs-keycloak-tls-certificate` in CS 4.3, and it changed to ODLM managing the secret in 4.4.
But ODLM will only manage/update a resource with label `operator.ibm.com/opreq-control: 'true'`.
As a result, `cs-keycloak-tls-secret` was not updated by ODLM to correctly reflect OCP serving cert in upgrade scenario, because it is missing such label in CS 4.3.
In order to solve this issue, two changes are made.
- Explicitly specify the label `operator.ibm.com/opreq-control: 'true'` in OperandConfig template for `cs-keycloak-tls-secret`, so ODLM will claim the owner of secret.
- Update ODLM logic, once label `operator.ibm.com/opreq-control: 'true'` is specified for certain resource in …
=> Handle Keycloak upgrade to refresh cs-keycloak-tls-secret

isolate.sh
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60889
When Bedrock v3 was originally installed in cluster shared mode, LSR will create an [OperandBindinfo named `ibm-license-service-reporter-bindinfo`](https://github.com/IBM/ibm-licensing-operator/blob/release-ltsr/controllers/resources/reporter/helper.go#L211C33-L211C33) to share [ConfigMap `ibm-license-service-reporter-zen`](https://github.com/IBM/ibm-licensing-operator/blob/release-ltsr/controllers/resources/reporter/secrets.go#L93C4-L93C4) from `ibm-common-services` to other Cloud Pak namespaces.
During the isolation, although Cloud Pak namespace was excluded from original Bedrock v3 instance, the copied ConfigMap `ibm-license-service-reporter-bindinfo-ibm-license-service-reporter-zen` was left in the Cloud Pak namespace, …
=> delete LSR ConfigMap from Pak ns during isolation

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
fix permission issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61841
error msg in nss operator pod:
```
E0111 20:09:00.408154       1 namespacescope_controller.go:619] Failed to create role cp1-ns/ibm-zen-operator-4a84785ac0b629: roles.rbac.authorization.k8s.io "ibm-zen-operator-4a84785ac0b629" is forbidden: user "system:serviceaccount:cs-operators:ibm-namespace-scope-operator" (groups=["system:serviceaccounts" "system:serviceaccounts:cs-operators" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:["tekton.dev"], Resources:["taskrun"], Verbs:["get" "list"]}
{APIGroups:["tekton.dev"], Resources:["taskrun/status"], Verbs:["get" "list"]}
{APIGroups:["tekton.dev"], Resources:["taskruns"], Verbs:["get" "list"]} …
```
=> grant new zen operator permission to nss operator

isolate.sh
Fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61794
- Redirect both standard output and standard error to `/dev/null`. The error msg: 
`error: timed out waiting for the condition on operandbindinfos/ibm-licensing-bindinfo` will not display If failed to delete OperandBindinfo 
- Add `Ignore-not-found` for oc get cm failed
=> Suppress error messages

controllers/operandconfig.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61204
There are two fields for resources' configuration in OperandConfig
- `.spec` section has certain rule to determine whether or not allow overwriting the data.
- `.resources` section does not have such rule, it should always allow overwriting the data.
This PR is to enable overwriting the data under `.resources` section when there are only default rules or no rules specified.
=> Overwrite the resource field when default rule is not specified

controllers/constant/odlm.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61840
Update ConfigMap `cs-keycloak-service` to reference latest service with name `cpfs-opcon-cs-keycloak-service`
=> Update Keycloak Service name in BindInfo ConfigMap

main.go
crd check had typo when passing the kind to check, was certificates instead of Certificate, which caused the check to always think that there was no cert-manager CRD on the cluster
=> fixed cert-manager crd check

controllers/constant/odlm.go
in order to leverage pod restart logic in cs-operator, the label is necessary
=> added cert label to keycloak cert secret

hack/keycloak-themes/theme/cloudpak/login/resources/css/styles.css
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61887
=> theme updates for keycloak errors, etc

hack/keycloak-themes/META-INF/keycloak-themes.json
Follow on from #1739 which didn't work if the theme was in a jar file.
=> Add common to the list of theme types so it works in jar format

velero/restore/restore-lsr-data.yaml, velero/restore/restore-lsr.yaml, velero/schedule/license_service_reporter/lsr-backup-deployment.yaml, velero/schedule/license_service_reporter/lsr-backup-pvc.yaml, velero/schedule/license_service_reporter/lsr-br-scripts-cm.yaml, velero/schedule/license_service_reporter/lsr-role.yaml, velero/schedule/license_service_reporter/lsr-rolebinding.yaml, velero/schedule/license_service_reporter/lsr-sa.yaml, velero/schedule/schedule-common-services.yaml
The License Service Reporter has a couple things to include in their backup/restore process and this pr (along with an update to the documentation) should cover them all. This PR was also used to test the use of pg_dump and pg_restore for postgres databases. After some tinkering with the two commands, I have stabilized the process.
As of opening this pr, here are the steps required to BR LSR:
- Add labels to secrets:
* ibm-license-service-reporter-token
* Ibm-license-service-reporter-credentials
* Ibm-license-service-reporter-credentials-htpasswd
* Possible secrets for oidc client secret and oidc provider if configured
* Secret names found in LSR CR under following fields
* --client-secret-name=
* --provider-ca-secret-name=
- Add labels to CRD, CR, subscription, and operatorgroup …
=> Create Backup and Restore process for license service reporter

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/bootstrap/init.go, controllers/commonservice_controller.go, controllers/scopewatcher_controller.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61587
Upgrade scenarios:
- LS + LSR in the same cluster
Updates for the licensing case during self-isolation:
- If spec.sender  is configured in LS instance, set a template for sender configuration with url pointing to the IBM LSR docs
- And create an empty secret ibm-license-service-reporter-token in LS_new_namespace to ensure that LS instance pod will start
1. install v3 operator in ibm-common-services ns and shared with two cloudpaks: cp4i, cp4ba
2. request `ibm-licensing-operator` in cp4i namespace and enable LSR according to[Deploying License Service Reporter]( https://www.ibm.com/docs/en/cloud-paks/foundational-services/3.23?topic=reporter-deploying-license-service)
3. in spec.sender in `IBMLicensing` instance
```
spec: …
```
=> update for licesning case with spec.sender set during self-isolation

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/bootstrap/init.go, controllers/common/util.go, controllers/commonservice_controller.go, controllers/scopewatcher_controller.go, main.go
- automatically update cs maps with operator ns for v3 operator deployment [1763](https://github.com/IBM/ibm-common-service-operator/pull/1763)
- update for licensing case during self-isolation [1761](https://github.com/IBM/ibm-common-service-operator/pull/1761)
=> [323] Cherry pick two PRs from release-ltsr

controllers/common/util.go, controllers/scopewatcher_controller.go
issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61620
If the IBM Licensing v4 operator is already installed in `cs-control` namespace before self-isolation, the CS operator should overwrite/update the ConfigMaps in the `cs-control` namespace with the ConfigMap data from `ibm-common-services` for those Licensing ConfigMaps that exist in `ibm-common-services`.
1. Install v3 operator in `ibm-common-services` ns and shared with two cloudpaks: cp4i, aiops, and check there is `ibm-licensing-config` ConfigMaps in the same namespace
2. Create a control namespace called `cs-control`
3. Install a IBM licensing v4 in `cs-control`, and create an example licensing ConfigMaps `ibm-licensing-config` with different data 
4. Switch cs oeprator channel to v4.4 in `aiops` namespace to trigger …
=> migrate licensing configmaps in self-isolation

hack/keycloak-themes/Makefile
```
Building the keycloak jar theme...
rm /home/prow/go/src/github.com/IBM/ibm-common-service-operator/hack/keycloak-themes/cloudpak-theme.jar
rm: cannot remove '/home/prow/go/src/github.com/IBM/ibm-common-service-operator/hack/keycloak-themes/cloudpak-theme.jar': No such file or directory
hack/keycloak-themes/Makefile:8: recipe for target 'cloudpak-theme.jar' failed
make: *** [cloudpak-theme.jar] Error 1
```
=> Always return true for rm command

controllers/bootstrap/init.go, controllers/constant/odlm.go
- ODLM create `common-service-postgres` operator and EDB cluster CR
ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62064
- ODLM creates certificate CR for the EDB sever and client authentication
ticket: https://github.ibm.com/ibmprivatecloud/roadmap/issues/62065
1. Deploy Cert-Manager 
2. As release 4.5 build is not ready, we could deploy 4.4 operator instead and update the OperandRegistry and OperandConfig with new entries.
3. Create an OperandRequest to request `common-service-postgres`
```
Kind: OperandRequest
metadata:
name: <ibm-service-request>
spec:
requests:
- operands:
- name: common-service-postgres
registry: common-service
registryNamespace: <foundational service operand namespace>
```
1. Subscription …
=> [4.5] Deploy CNPG operator, config EDB server and create tls certificate CR

controllers/constant/storageclass.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62016
Support storageClass configuration `.spec.walStorage.storageClass` for EDB Cluster CR named `keycloak-edb-cluster`
```yaml
...
walStorage:
resizeInUseVolumes: true
size: 1Gi
storageClass: rook-ceph-block
maxSyncReplicas: 0
switchoverDelay: 3600
storage:
resizeInUseVolumes: true
size: 1Gi
storageClass: rook-ceph-block
description: EDB Database with IBM License Key
```
=> Enable storageClass configuration for EDB wal

controllers/constant/odlm.go
EDB service does not provide port with name `https`
```
psql: error: could not translate host name "https" to address: Name or service not known
```
The endpoint works without `https`
```
psql (16.1 (Debian 16.1-1.pgdg120+1), server 15.4)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
Type "help" for help.
im=> 
```
=> Update service endpoint for EDB

cs-onprem-tenant-config.sh
Changes went in:
1. Script to support **multiple topology**.
2. Fixed the hardcoded secret name `custom-tls-secret` issue while deleting the secret.
Replaced command 
-> oc delete secret custom-tls-secret -n $map_to_common_service_namespace --ignore-not-found 
to
-> oc delete secret $(oc get configmap -n $map_to_common_service_namespace cs-onprem-tenant-config -o 
jsonpath='{.data.custom_host_certificate_secret}') --ignore-not-found
3. Removed the part of code where we are setting the labels of the pods and also the part where the pods are being restarted, since no need to restart the pods.
4. Fixed issue of running custom hostname job. 
5. Job completion function `check_job_completion()` changed to 
->  oc wait job iam-custom-hostname --for condition=complete --timeout=120s 
Addressing …
=> Updating cs-onprem-tenant-config.sh

api/v3/finalizer.go, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/bootstrap/init.go, controllers/common/util.go, controllers/commonservice_controller.go, controllers/constant/constant.go, controllers/recocile_pause.go
ticket: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61040
After upgrading from CS v3 to CS v4, the v3 Namespace Scope operator and CRs will be expected to be cleaned up by the common service operator automatically in Simple Topology or AllNamespace mode as they are no longer needed.
1. CS operator upgrades to v4.
2. Check if all Bedrock v3 core services are no longer requested by CloudPak by inspecting the v4 OperandRegistry.
3. Check the deployment topology, whether it is a Simple Topology or in All Namespace Mode.
4. Delete v3 NSS operator in the servicesNamespace firstly if they still remain to prevent adding the ownerReferences back to `namespace-scope` configMap
5. Remove the ownerReferences in `namespace-scope` configMap in case it is deleted with `common-service` …
=> Automatically clean up NSS CRs and operator in Simple TP or All ns mode

controllers/constant/odlm.go
issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/62275
After bedrock core service is separated into their own catalog, they are not always installed from the same catalog as CS/ODLM.
Remove hardcoded `sourceName` and `sourceNamespace` in OperandRegistry for core service.
Here is the future Catalog structures
```
Top-Level CASE:
|- Installer SubCASE:
|- ibm-installer-catalog (single-channel cs-operator, odlm, nss catalog)
|- CommonUI SubCASE:
|- ibm-commonui-operator-catalog (single-channel UI catalog)
|- Events SubCASE:
|- ibm-events-operator-catalog (single-channel events catalog)
|- IAM SubCASE:
|- ibm-iam-operator-catalog (single-channel iam catalog)
|- MongoDB SubCASE:
|- ibm-mongodb-operator-catalog (single-channel mongo catalog)
|- Zen SubCASE:
|- …
```
=> Remove hard requirement to install core service from the same Catalog as CS/ODLM, as the preparation for catalog separation

controllers/rules/rules.go, controllers/size/large_amd64.go, controllers/size/large_ppc64le.go, controllers/size/large_s390x.go, controllers/size/medium_amd64.go, controllers/size/medium_ppc64le.go, controllers/size/medium_s390x.go, controllers/size/small_amd64.go, controllers/size/small_ppc64le.go, controllers/size/small_s390x.go, controllers/size/starterset_amd64.go, controllers/size/starterset_ppc64le.go, controllers/size/starterset_s390x.go
issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/62292
- Include size setting into the rules template
- Incorporate resource instance values to the T-shirt size
- Add CPU, memory limitation
=> Enable customization for common-service-db Cluster CR

controllers/bootstrap/init.go, controllers/commonservice_controller.go, controllers/constant/constant.go
Found an issue when doing a fresh install CPFS in simple topology.
CS operator is trying to check if OperandRegistry has any no-op operator requested before cleaning any NSS resources. However, OperandRegistry is not present yet in fresh installation.
```
E0221 03:26:42.996735       1 init.go:1191] Failed to get common-service OperandRegistry: no matches for kind "OperandRegistry" in version "operator.ibm.com/v1alpha1"
E0221 03:26:42.996810       1 init.go:164] Failed to clean NamespaceScope resources: no matches for kind "OperandRegistry" in version "operator.ibm.com/v1alpha1"
E0221 03:26:42.996836       1 commonservice_controller.go:229] Failed to initialize resources: no matches for kind "OperandRegistry" in version "operator.ibm.com/v1alpha1"
E0221 03:26:43.005957       1 …
```
=> Check OperandRegistry when checking no-op operators

controllers/constant/storageclass.go
Issue:https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62395
Added a storageClass template for `common-service-db`, so that when the user configures the storageClass in the CommonService CR, the custom storageClass will be added to the `common-service-db` resource in OperandConfig and synchronized in the Cluster CR.
test image: quay.io/yuchen_shen/cs_operator:csdb_sc
1. Request `common-service-postgresql` without configure storageClass in CommonService CR, there will be no storageClass section for `common-service-db` in Cluster CR
2. Apply the test image, configure a storageClass in CS CR
3. Delete `common-service` OpCon and `common-service-db` Cluster CR and restart ODLM pod
4. Observe the custom sc will be added in OperandConfig and existing `common-service-db` Cluster CR
example: …
=> Enable StorageClass configuration for common-service-db

controllers/bootstrap/init.go, controllers/common/util.go, controllers/webhooks/commonservice/validatingwebhook.go
Fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62427
If the Namespace Scope operator does not immediately patch `WATCH_NAMESPACE` in the cs-operator CSV, we will then check the number of scoped namespaces from the `namespace-scope` ConfigMap before proceeding to clean up the NSS operator and CRs.
=> Check scoped namespaces from nss ConfigMap instead of watch_namespace

cp3pt0-deployment/migrate_tenant.sh
CS version `4.4.1` will become `4.5.0`, and `4.5.0` will then progress to `4.6.0`,so pin the channel of ODLM at version 4.3 for CS 4.6+
- The ODLM channel will be the same as the version of Common Service for 4.0 and 4.1 release
- The ODLM channel will be at `v4.2` for CPFS 4.2-4.5 release
- The ODLM channel will be pinned at version `v4.3` for each release starting from 4.6
=> Pin the ODLM channel at v4.3 for CS 4.6+

controllers/constant/odlm.go
Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/62328
In CS 4.6+, the [IM operator has taken control of the OperandRequest `ibm-iam-request`](https://github.com/IBM/ibm-iam-operator/blob/master/controllers/operator/operandrequest.go#L63). We will remove this request from OpCon, and ODLM will not create/update the im-request to manage the IM internal dependency.
=> Removed im request in OperandConfig

controllers/commonservice_controller.go, controllers/constant/odlm.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62236
Enable feature `token-exchange` in KeyCloak CR by default
=> Enable keycloak token-exchange

controllers/rules/rules.go, controllers/size/large_amd64.go, controllers/size/large_ppc64le.go, controllers/size/large_s390x.go, controllers/size/medium_amd64.go, controllers/size/medium_ppc64le.go, controllers/size/medium_s390x.go, controllers/size/small_amd64.go, controllers/size/small_ppc64le.go, controllers/size/small_s390x.go, controllers/size/starterset_amd64.go, controllers/size/starterset_ppc64le.go, controllers/size/starterset_s390x.go
ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62447
Updated size profile of `common-service-db` based on [comment](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62293#issuecomment-73947101)
=> Update size for common-service-db

cp3pt0-deployment/common/utils.sh
issue: https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/17638#issuecomment-74020451
Increase the wait time from 1 min to 5 min for certificate smoke test
```
[root@api.sre-upg-3m15w-ocs-480-airc-01.cp.fyre.ibm.com work]# tail -f setup-instance-topology-March1-t5.log
[INFO] RETRYING: Waiting for Certificate test-certificate in namespace operator-ns to be Ready (5 left)
[INFO] RETRYING: Waiting for Certificate test-certificate in namespace operator-ns to be Ready (4 left)
[INFO] RETRYING: Waiting for Certificate test-certificate in namespace operator-ns to be Ready (3 left)
[INFO] RETRYING: Waiting for Certificate test-certificate in namespace operator-ns to be Ready (2 left)
[INFO] RETRYING: Waiting for Certificate test-certificate in namespace operator-ns to be Ready (1 …
```
=> increase wait time for cert and issuer

cp3pt0-deployment/migrate_tenant.sh
fix for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61531
The fix is used to recreate/update the `common-service` NamespaceScope CR promptly after cleaning NSS resources to prevent obtaining an incorrect number of namespace members caused by the failure of the NSS operator upgrade the next time the script runs.
=> create/update NSS CR before updating NSS operator

cp3pt0-deployment/common/utils.sh
Fix for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/62501
In this release, we have temporarily extended the CS CR waiting time to address the issue. Additionally, we are planning to refactor the code and create new controllers to concurrently reconcile the CS CR, aiming to reduce waiting times in future releases.
=> Extend the time to wait for CS CR readiness

preload_data.sh
As we introduce `error trapping in the $FUNCNAME`, we need to remove the problematic code to reduce errors that could lead to script termination
=> Remove problematic code to reduce error

controllers/constant/odlm.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61733
=> [323] Upgrade db2u operator channel to v5

preload_data.sh
Previously the `dumplog` function only supports to record the logs for one pod.
Update the function to support recording logs for multiple pods.
=> Enhance dumplog to support multiple pods

controllers/constant/cloudNativePostgresql.go, controllers/constant/odlm.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62285#issuecomment-74522237
1. Pick images for EDB 1.18.10
2. Removing hardcoded image string from OperandConfig, image is always referenced from `cloud-native-postgresql-image-list` ConfigMap.
=> [4.5] Pick up EDB 1.18.10

velero/schedule/keycloak/keycloak-backup-deployment.yaml, velero/schedule/schedule-common-services.yaml
remove database and secrets separately, otherwise it might cause permission issue because of `readonlyrootfilesystem`
=> update velero post hook annotation

common/scripts/lint-csv.sh, controllers/bootstrap/init.go, controllers/constant/odlm.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61103#issuecomment-74347408
Add CRs back to OperandConfig
- Cert Manager CR `certManager`
- AuditLogging CR `auditLogging`
=> Add cert-manger and AudiLogging CRs back to OperandConfig

preload_data.sh
The `platform-oidc-credentials` and `oauth-client-secret` Secrets both contain client registrations that are expected to persist through an isolated upgrade and migration from MongoDB to EDB. Not having these secrets established before the IAM Operator starts leads to split-brain problems between the Operator and the platform-auth-service Operand.
=> Preload IM client credentials for admin

controllers/constant/odlm.go, controllers/constant/storageclass.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62563
A new PVC is created for WAL storage, and the size for two PVCs are both 10Gi
=> separate wal storage and increase storage volume

controllers/constant/odlm.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62327
MongoDB operator and services are not longer requested by IM to install since release 4.6, we have marked it as `no-op` operator.
=> Disable the installation of MongoDB starting from 4.6.

controllers/constant/odlm.go, controllers/size/large_amd64.go, controllers/size/large_ppc64le.go, controllers/size/large_s390x.go, controllers/size/medium_amd64.go, controllers/size/medium_ppc64le.go, controllers/size/medium_s390x.go, controllers/size/small_amd64.go, controllers/size/small_ppc64le.go, controllers/size/small_s390x.go, controllers/size/starterset_amd64.go, controllers/size/starterset_ppc64le.go, controllers/size/starterset_s390x.go
Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61284
After [implementing](https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1019) the ODLM's capability to deep merge Kubernetes resources logic, we could remove the default size profile and instance in OperandConfig template. Therefore, we should observe a consistent change in the number of instances during common-service reconciliation, rather than fluctuating between 3, 1, and 3.
Before removing the hardcoded size and instance:
1. When deploying KeyCloak for the first time, the instance created in KeyCloak CR would be `1`.
2. Then if the user configures a large size in CS CR, the instance will change to `3`.
3. If it is upgraded to a new version, we will observe the instance changing back to `1`, as CS applies …
=> Remove default size profile and instance from OperandConfig template

controllers/constant/odlm.go
To unblock the error on rendering OperandConfig, json could not unmarshal array `["velero"]` into annotation value `string`, need to quote the array `'["velero"]'`
```
E0329 04:25:33.828268 1 init.go:710] failed to concatenate OperandConfig: failed to fetch data of OprandConfig hugepages/common-service: error unmarshaling JSON: json: cannot unmarshal array into Go struct field ConfigResource.spec.services.resources.annotations of type string
E0329 04:25:33.835020 1 commonservice_controller.go:227] Fail to reconcile hugepages/common-service: failed to fetch data of OprandConfig hugepages/common-service: error unmarshaling JSON: json: cannot unmarshal array into Go struct field ConfigResource.spec.services.resources.annotations of type string
2024-03-29T04:25:33.835Z ERROR …
```
=> quote array value for annotations

api/v3/commonservice_types.go, api/v3/zz_generated.deepcopy.go, bundle.Dockerfile, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, bundle/manifests/operator.ibm.com_commonservices.yaml, bundle/metadata/annotations.yaml, config/crd/bases/operator.ibm.com_commonservices.yaml, go.mod, go.sum
Add preserve unknown field for CS CR field .`spec.services[*]`
```yaml
metadata:
spec:
license:
accept: false
operatorNamespace: cs-condition
servicesNamespace: cs-condition
services:
- name: ibm-im-operator
resources:
- xxxx
spec:
xxxx
...  # Any arbitrary field
```
=> Update CRD to be forward compatible

controllers/constant/odlm.go
Add following CPFS annotations for EDB Cluster CR created by CPFS. One Cluster CR for IM, and the other one for Keycloak.
```
productID: 068a62892a1e4db39641342e592daa25
productMetric: FREE
productName: IBM Cloud Platform Common Services
```
The pod managed by EDB Cluster CR contains the annotations as well
=> add cpfs annotation info for EDB Cluster CR

controllers/constant/odlm.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62819
Keycloak CR's pod will have a reference on `annotations.version` from `cs-keycloak-theme` ConfigMap.
When the `cs-keycloak-theme` ConfigMa is updated in a new release(new theme update), Keycloak pod will be patched with a new annotation `cpfsVersion: 4.6.0`. As a result, the pod will be restarted to pick up the new theme styling.
- Keycloak CR will be updated with latest pod template
- Keycloak pod will be updated with new annotation
=> reference cpfs version in Keycloak pod template

controllers/bootstrap/init.go
fix for issues:
https://github.ibm.com/ibmprivatecloud/roadmap/issues/61040
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61273
Ensure that the version of OperandRegistry is greater than or equal `4.0.0` before proceeding to clean up NSS resources.
=> condition check for OperandRegistry version comparison

Makefile, api/v3/commonservice_types.go, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml, controllers/bootstrap/init.go, controllers/constant/keycloakThemes.go, controllers/constant/odlm.go, hack/keycloak-themes/Makefile, testdata/deploy/deploy.yaml
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62819#issuecomment-76863148
We annotate the Keycloak pod with the theme version. As long as the theme does not change, keycloak pod does not need to be restarted. It would be independent from CPFS upgrade.
- CS operator CSV will contain the theme version annotation
- `cs-keycloak-theme` ConfigMap will contain the theme version annotation.
- Keycloak server pod will contain the theme version annotation.
=> annotate Keycloak pod with theme version instead of CPFS version

controllers/bootstrap/init.go
Ticket: 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61273
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61040
In the AllNamespace/SingleNamespace migration path, NSS `NamespaceScope` resources failed to be deleted automatically during the initial run. However, upon restarting the CS pod, they will eventually be removed
- Adding a check to get the DeletionTimestamp in the `PollImmediate` function to address the timing issue where the deletion timestamp might not be available immediately after deletion
- List all NSS resources again to ensure that the DeletionTimestamp exists in all the resources before patching the finalizers
**Test image**: quay.io/yuchen_shen/cs_operator:nss_cleanup
1. Deploy v4 CS instance in AllNamespace Mode
2. Manually create some `NamespaceScope` …
=> Ensure that DeletionTimestamp exists before patching the finalizers

controllers/cert-manager/podrefresh_controller.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63035
Follow up on PR: #1417 
Handle format of restart time label from the upgrade scenario, to support the pod refreshment for certificate renew.
=> keep restart labels backward compatible with CPFS v3

cp3pt0-deployment/setup_singleton.sh
issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61575
We introduce a flag `--check-cert-manager` to run the cert-manager deployment check before user applying the CatalogSource and returning the indicator value:
- return 0: there is no cert-manger installed in the whole cluster
- return 1: there is IBM v3 or v4 cert-manger installed
- return2: third-party cert-manger is deployed
=> [4.6.1] Check if third party cert-manger deployed before applying catalogsource

velero/backup/zen/zen5_backup_job.yaml, velero/restore/common-service-db/cs-db-restore-job.yaml, velero/restore/keycloak/keycloak-restore-job.yaml, velero/restore/zen/zen-restore-job.yaml, velero/restore/zen/zen5-restore-job.yaml, velero/schedule/common-service-db/cs-db-backup-deployment.yaml, velero/schedule/keycloak/keycloak-backup-deployment.yaml
the cpfs utils repo is still using 4.5 for the new image so need to revert the image values in the scripts repo
=> revert cpfs utils image to 4.5 to match repo

velero/schedule/schedule-common-services.yaml
The velero plugin based BR is currently setup to use the labels `keycloak` and `cs-db` for velero to notice and process the keycloak and IM EDB clusters for backup. This is to differentiate between the velero plugin approach (facilitated and officially supported by the EDB operator) and the pgdump approach we implemented outside of the operator. The pgdump approach uses `keycloak-data` and `cs-db-data` for comparison. I have added comments to these four values as well as the similarly structured License Service Reporter and Zen values to provide clarity on their usage.
=> add velero plugin based labels, clarify labels

velero/schedule/schedule-common-services.yaml
We use a different label for the pgdump (keycloak-data) and cluster annotation (keycloak) BR approaches. We need to make sure both are covered in the schedule yaml file.
=> add keycloak label to schedule

velero/schedule/common-service-db/cs-db-br-script-cm.yaml
Need to rerun the oidc client registration job after restoring cs db data. Better to include it as part of the script than to add another step to the documentation. I also matched the scripts-dev script to what is currently in the scripts branch as I did a little cleanup when merging in https://github.com/IBM/ibm-common-service-operator/pull/1924
=> match dev to scripts, add oidc rerun command

velero/schedule/common-service-db/cs-db-br-script-cm.yaml
Mostly same changes as https://github.com/IBM/ibm-common-service-operator/pull/1946. Need to rerun oidc registration job after restore is completed and it is much better to add this step to the script than to add to documentation.
=> add rerun oidc job command

controllers/constant/odlm.go
By default, we want to enable the velero backup addon for IM EDB cluster. This way, in all use cases except CP4D, IM EDB will follow the officially supported BR process for EDB. In the CP4D case where IM EDB will be sharing cluster config with zen, CP4D will overwrite the annotation with their own via the CommonService CR. This will remove the ability to backup IM via velero plugin so we will have a fork in the instructions to specify using the pgdump approach instead. I stuck with calling the velero label cs-db instead of cs-db-data as we already have in scripts to facilitate this use case based fork.
Discussion welcome.
=> add velero plugin to im edb cluster config by default

velero/restore/mongoDB/mongo-restore.sh, velero/restore/mongoDB/mongodbrestore.yaml, velero/schedule/mongodb-backup-deployment.yaml
the previous host parameter would pick one of the three possible endpoints and would fail on restore if the endpoint selected was not the primary. Adding all possible hosts guarantees the primary is selected for write operations (mongorestore). This change is not required for backup (mongodump) because it is a read only operation.
=> update mongorestore command for multiple hosts

controllers/constant/odlm.go
- for cloud-native-postgresql, which reduced performance
added back EDB licensing job for edb-keycloak because internal OperandRequest is removed
=> removed internal OperandRequest from edb-keycloak

controllers/constant/odlm.go, controllers/operandconfig.go, controllers/rules/rules.go, controllers/size/large_amd64.go, controllers/size/large_ppc64le.go, controllers/size/large_s390x.go, controllers/size/medium_amd64.go, controllers/size/medium_ppc64le.go, controllers/size/medium_s390x.go, controllers/size/small_amd64.go, controllers/size/small_ppc64le.go, controllers/size/small_s390x.go, controllers/size/starterset_amd64.go, controllers/size/starterset_ppc64le.go, controllers/size/starterset_s390x.go
Ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63175
Set default value for max connections of `common-service-db` cluster CR for different size profile
=> EDB max connection configuration

velero/schedule/zen5-backup-deployment.yaml, velero/schedule/zen5-br-scripts-cm.yaml
For issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62738.
Increase the zen timeout to reduce the likelihood of timing out during a zen data restore.
Change the extension delete api request to be in line with what zen core api expects by replacing `/` with `%2F` after consulting with zen team.
=> Fix zen extension cleanup logic

controllers/constant/odlm.go
Pending results from this issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63296.
Linked issue is to verify that our defaults are overwritten by CPD's commonservice CR since we have conflicting backup annotations. So far, it looks like it does properly overwrite but waiting on final verification after running a CPD BR.
=> add velero annotation and cpfs lbr labels by default to cs db cluster cr

controllers/bootstrap/init.go, controllers/bootstrap/init_test.go, controllers/constant/odlm.go, controllers/recocile_pause.go, go.mod, go.sum
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61732
CS operator will wait for ODLM minor version upgrade before proceeding to next step. e.g., ODLM `v4.2.3` -> `v4.3.0` with a channel switch `v4.2` to `v4.3`.
Also when CS operator detects an ODLM minor version upgrade, meaning there are potential CRD changes, CS operator will force ODLM CRs(OperandConfig and OperandRegistry) update, to ensure that CRs are applied to the cluster with latest ODLM CRD changes.
The file `controllers/bootstrap/init_test.go` includes the unit test for two new added functions.
The end to end test was done as well on the cluster with image build.
=> Update ODLM CRs after ODLM has a minor version upgrade

velero/schedule/common-service-db/cs-db-br-script-cm.yaml, velero/schedule/keycloak/keycloak-br-script-cm.yaml
Previous implementation techincally worked but always output the following error:
> Error from server (Forbidden): jobs.batch "oidc-client-registration" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
This updated implementation does not output any errors and now also includes actual wait logic to verify the job completes. Wait logic borrowed from keycloak script where a bug was found and updated.
=> update oidc rerun logic, correct bug

cp3-networkpolicy/egress/operators/bedrock-egress-egress-create-postgres-license-config.yaml, cp3-networkpolicy/egress/operators/bedrock-egress-ibm-mongodb-operator.yaml, cp3-networkpolicy/egress/operators/zen-egress-ibm-zen-setup-job.yaml, cp3-networkpolicy/egress/zen/zen-egress-edb-postgres.yaml, cp3-networkpolicy/ingress/zen/zen-access-to-zen-core.yaml
- EDB operator will have outbound traffic to EDB service for healthiness check
- IAM operator will have outbound traffic to platform-identity-provider service for client registration
- EDB operator will reach out to both EDB service in service and zen namespace
- Enable outbound traffic to apiServer for Job `create-postgres-license-config`
- Enable outbound traffic to apiServer for Job `ibm-zen-setup-job`
- Enable outbound traffic to apiServer for pod `ibm-mongodb-operator` for backward compatibility
=> Add egress network policy for operator ns

api/v3/commonservice_types.go, controllers/bootstrap/init.go, controllers/cert-manager/certificaterefresh_controller.go, controllers/cert-manager/podrefresh_controller.go, controllers/cert-manager/v1_add_label_controller.go, controllers/commonservice_controller.go, controllers/constant/constant.go, controllers/goroutines/waitToCreateCsCR.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63012
As CommonService CRD have been updated containing `.status.conditions[*]`, I would like to implement some functions to update to CS CR status at each reconciliation loop, and provide detailed reporting of the status of a CommonService CR
Using `status.conditions` to provide information about the status of an instance.
- Contents of a Condition
- Creating CommonService CR.
- Initializing/Updating ODLM CRs.
- Configuring CommonService CR (size profile and storageClass)
- CommonService CR is ready
- StatusError occurred
- Warning msg shown
- Condition Type introduced
- ConditionTypeBlocked 
- ConditionTypeReady
- ConditionTypeWarning 
- …
=> Introduce Condition object into CommonService CR status

cp3pt0-deployment/setup_tenant.sh
Replace `xargs` with `tr` and `sed` command due to License issue on including `xargs` binary in `cpfs-utils` image and shipped as IBM software.
The following command has the identical functionality
```bash
new_ns_list=$(echo ${existing_ns} ${TETHERED_NS//,/ } ${SERVICES_NS} | xargs -n1 | sort -u | xargs)
new_ns_list=$(echo ${existing_ns} ${TETHERED_NS//,/ } ${SERVICES_NS} | tr ' ' '\n' | sort -u | tr '\n' ' ' | sed 's/ $//')
```
```console
./cp3pt0-deployment/setup_tenant.sh \
--operator-namespace networkpolicy-control \
--services-namespace networkpolicy-data \
--tethered-namespaces networkpolicy-cpd-add,networkpolicy-cpd-add-2 \
--excluded-namespaces networkpolicy-cpd,networkpolicy-not-there  \
--license-accept \
-c v4.7
```
The final version of NSS CR is expected
```yaml
apiVersion: …
```
=> replace xargs with tr and sed

controllers/constant/odlm.go
related to https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63296 and https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/21623
=> remove velero offline backup annotation

preload_data.sh
Copy and paste from the issue:
problem comes from this line in the preload script https://github.com/IBM/ibm-common-service-operator/blob/scripts-adopter/preload_data.sh#L159. It looks like the script finding the mongo node is pointing to the wrong column and then passes that value into the next line which is why we see `Error from server (NotFound): nodes "4d4h" not found`. I don't have mongo deployed but I tried the command with common-service-db:
>  $ oc get pods -o wide | grep common-service-db-1 | awk '{print $7}'
worker0.luztest2.cp.fyre.ibm.com
But when I run the same command on the cluster from the issue it gives a different value:
>  $ oc get pods -o wide | grep mongodb-0 | awk '{print $7}'
7d2h
New command:
> $ oc get pods icp-mongodb-0 -o=jsonpath='{.spec.nodeName}' …
=> change mongo node grabbing to be more consistent

cp3pt0-deployment/setup_tenant.sh
Enhance the issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63437
Adding waiting condition for the `ibm-common-service` pod to contain the status condition of type "Ready" before applying the configured CommonService CR.
=> Wait for cs pod ready before configuring CS CR

cp3pt0-deployment/setup_singleton.sh
Skip the IBM Cert Manager CatalogSource validation if there is no IBM Cert Manager installed, and only validate it before proceeding with the installation or upgrade
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61575
=> skip CatalogSource validating if there is no IBM Cert Manager installed

api/v3/commonservice_types.go, controllers/bootstrap/init.go, controllers/constant/odlm.go
After refactoring the ODLM service status check, ODLM will get a list of services whose status is reported from OperandRegistry annotations.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63673
New OperandRegistry is created with following annotations
```yaml
kind: OperandRegistry
metadata:
annotations:
excluded-catalogsource: 'certified-operators,community-operators,redhat-marketplace,ibm-cp-automation-foundation-catalog,operatorhubio-catalog'
status-monitored-services: 'ibm-idp-config-ui-operator,ibm-mongodb-operator,ibm-im-operator'
version: 4.6.3
```
=> Add StatusMonitoredServices annotations to OperandRegistry

cp3-networkpolicy/egress/cert-manager/bedrock-egress-ibm-cert-manager-operator.yaml, cp3-networkpolicy/egress/license-service-reporter/bedrock-egress-ibm-license-service-reporter-operator.yaml, cp3-networkpolicy/egress/license-service/bedrock-egress-ibm-licensing-operator.yaml, cp3-networkpolicy/egress/operators/bedrock-egress-cloud-native-postgresql.yaml, cp3-networkpolicy/egress/operators/bedrock-egress-egress-create-postgres-license-config.yaml, cp3-networkpolicy/egress/operators/bedrock-egress-ibm-bts-operator.yaml, cp3-networkpolicy/egress/operators/bedrock-egress-ibm-common-service-operator.yaml, cp3-networkpolicy/egress/operators/bedrock-egress-ibm-commonui-operator.yaml, cp3-networkpolicy/egress/operators/bedrock-egress-ibm-events-operator.yaml, cp3-networkpolicy/egress/operators/bedrock-egress-ibm-iam-operator.yaml, cp3-networkpolicy/egress/operators/bedrock-egress-ibm-mongodb-operator.yaml, cp3-networkpolicy/egress/operators/bedrock-egress-ibm-namespace-scope-operator.yaml, cp3-networkpolicy/egress/operators/bedrock-egress-operand-deployment-lifecycle-manager.yaml, cp3-networkpolicy/egress/operators/zen-egress-ibm-zen-operator.yaml, cp3-networkpolicy/egress/operators/zen-egress-ibm-zen-setup-job.yaml, cp3-networkpolicy/egress/services/bedrock-egress-rhbk-operator.yaml
This is used to establish DNS connection for CPFS pod only
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63853
=> Allow cpfs pods to establish DNS connection

preload_data.sh
CP4BA ran into issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63644 where they were seeing a failure with the mongodb-backup job created by the preload_data.sh script:
```
2024-05-28T19:05:09.097+0000	Failed: error dumping metadata: error creating directory for metadata file /dump/dump/platform-db: mkdir /dump/dump: permission denied
```
This failure was preventing successful upgrade. I went onto the cluster and added an emptyDir volume to each instance of a mongo restore or backup job and mounted it to the location where we try to write the mongodump out to "/dump/dump". After making this change on the cluster where the problem was seen, I saw the job and the preload_data.sh script complete successfully.
=> specify dump location with emptyDir volume

velero/backup/common-service/label-common-service.sh
Automate the lsr resources labelling for Backup and Restore, following the document: https://github.ibm.com/IBMPrivateCloud/common-services-docs/blob/master-4.x.x/installer/backup_restore_license_service_reporter.md#backup-license-service-reporter-instance-1
Part of issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63682
**Resources include**:
- License Service Reporter CatalogSource
- Namespaces and OperatorGroups of the LSR
- Necessary secrets ([some optional secrets when OIDC configured](https://www.ibm.com/docs/en/cloud-paks/foundational-services/4.7?topic=authentication-license-service-reporter-oauthoidc-provider#configuration)) 
- Subscription
- LSR instance CR and CRD
=> Add label to the license service reporter resources

api/v3/commonservice_types.go, bundle/manifests/operator.ibm.com_commonservices.yaml, config/crd/bases/operator.ibm.com_commonservices.yaml
To backup common services with velero we ask the user to add a label to the backup the CommonService CRD. This user added label will be reset after every operator upgrade, so lets add a label to the CRD ourselves that the user can select.
See doc here: https://www.ibm.com/docs/en/cloud-paks/foundational-services/4.4?topic=fsbr-cloud-pak-foundational-services-backup-restore-clusters-single-instance-foundational-services
Fixes #
3. If this PR is already …
=> Label the CommonService CRD so it can be selected for backup

controllers/constant/constant.go
To backup common services with velero we ask the user to add a label to the backup the CommonService CR. This PR adds a default label to new CRs that the user can select more easily.
See doc here: https://www.ibm.com/docs/en/cloud-paks/foundational-services/4.4?topic=fsbr-cloud-pak-foundational-services-backup-restore-clusters-single-instance-foundational-services
Fixes #
3. If this PR is already merged, you can still add the label with the target branch …
=> Label the CommonService CR so it can be selected for backup

api/v3/commonservice_types.go, bundle/manifests/operator.ibm.com_commonservices.yaml, config/crd/bases/operator.ibm.com_commonservices.yaml
Port this change https://github.com/IBM/ibm-common-service-operator/pull/2036 to SC2 release stream
=> add br label to crd by default

cp3pt0-deployment/common/utils.sh
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64017
```
[INFO] RETRYING: Waiting for operator ibm-cert-manager-operator CSV in namespace ibm-cert-manager to be bound to Subscription (3 left)
[INFO] RETRYING: Waiting for operator ibm-cert-manager-operator CSV in namespace ibm-cert-manager to be bound to Subscription (2 left)
[INFO] RETRYING: Waiting for operator ibm-cert-manager-operator CSV in namespace ibm-cert-manager to be bound to Subscription (1 left)
[✘] Error in /home/cert-kubernetes/scripts/cpfs/installer_scripts/cp3pt0-deployment/common/utils.sh at line 126 in function wait_for_condition: Timeout after 10 minutes waiting for ibm-cert-manager-operator CSV in namespace ibm-cert-manager to be bound to Subscription
```
```
[INFO] RETRYING: Waiting for operator …
```
=> increase waiting time for operator upgrade and installation

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/setup_singleton.sh
When running the `setup_singleton.sh` with `-- enable-private-catalog` flag set, the error message of CatalogSource validation has been updated 
Improvement：
- When the `--enable-private-catalog` flag is set, there is a warning message that prompts the namespaces of singleton operators should be in the same namespace as the singleton CatalogSource.
- If the specific CatalogSource in its namespace is not found in the cluster, then the script will try to get an available global CatalogSource and will error out if there is more than one CatalogSource available in the entire cluster.
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63998#issuecomment-83385625
=> Improve the error msg for private catalogsource validating

controllers/constant/odlm.go
Only create EDB Cluster CR after License Secret is injected for operator, to avoid operator pod restart during the CR reconciliation, see more details in https://github.com/IBM/ibm-common-service-operator/pull/1728
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64053
=> [4.8] Add EDB License secret into Cluster CR description

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Copy the events-related permissions collected from the 4.4 release into the 4.6 NSS managed role YAML to fix the permission issue hit in the upgrade path.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64035#issuecomment-84268980
`nss-maanged-bedrock-core-role.yaml` is the template role that needs to be applied after each upgrade done by the script.
=> Update events permission in nss managed role

velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml, velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
Updated the Spectrum Fusion recipe to include groups and condition check (hook) to backup and restore LSR operator and resources
Issue [63682](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63682)
1. Backup test done
2. Testing on Restore
=> Create Spectrum Fusion recipe for License Service Reporter

convert_to_multi_instance.sh
While running the conversion script for the cp4ba conversion test, ran into an issue with the control namespace variable not being set in the `migrate_lic_cms` function. I have changed the function to mirror what is in the isolate.sh script. 
I have not tested this script change yet.
Testing:
- setup shared environment
- run conversion script
- verify script completes successfully, look specifically for the success message: `"Licensing configmaps copied from $namespace to $CONTROL_NS"` or info message: `"No licensing configmaps to migrate"`
=> match migrate lic function to what is in isolate script

preload_data.sh
In older environments where metering data still exists, it is possible for the restore job to fail trying to restore metering data when it is not covered by the preload script. This failure happens because of how the preload data script works. This script creates a dummy mongo in the target namespace. By default, this mongo is stood up with the oauth db and the platform db. the ouath data is copied over via secrets and configmaps that are copied over from the original namespace to the target namespace so those values don't need to be restored. This leaves the plaftform db data. When mongo starts up, it automatically creates this db inside mongo. This does not happen by default for metering so there is no metering db.
What does this mean?
This means when we run the mongorestore command, …
=> specify data copied over in preload data script

preload_data.sh
set storageclass name on ROKS for mongo-pv 
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62238
=> annotate Mongo PV on ROKS

controllers/constant/odlm.go
Adding version suffix for bts operator in operandregistry
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63816
=> BTS version suffix

controllers/constant/odlm.go
Adding version suffix for bts operator in operandregistry
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63816
=> BTS version suffix in CD

controllers/constant/odlm.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63488
Enable the ability for ODLM to install EDB operator v1.22 from `stable-v1.22` channel
=> [CD] add version suffix entry for EDB 1.22

cp3pt0-deployment/setup_singleton.sh
enhancement for https://github.com/IBM/ibm-common-service-operator/pull/2115, missing migration scenario in that pr
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64368
=> update licensing and cert-manager catalogsource namespace in migrate

preload_data.sh
Use `jsonpath` to get the status of mongodb pod
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64387
Execute script with a successful run
```console
./preload_data.sh --original-cs-ns ibm-common-services --services-ns services
All arguments passed into the script: --original-cs-ns ibm-common-services --services-ns services
[INFO] Checking cert manager readiness.
issuer.cert-manager.io/test-issuer created
certificate.cert-manager.io/test-certificate created
certificate.cert-manager.io "test-certificate" deleted
issuer.cert-manager.io "test-issuer" deleted
[✔] Cert manager is ready, preload can proceed.
[INFO] Copying …
```
=> Use jsonpath to check the status for mongodb pod

preload_data.sh
Add cleanup option for more script flexibility as well as update error message to reflect --rerun and --cleanup options
Testing:
```
[root@api.o1-772676.cp.fyre.ibm.com ibm-common-service-operator]# ./preload_data.sh --original-cs-ns ibm-common-services --services-ns combank1
All arguments passed into the script: --original-cs-ns ibm-common-services --services-ns combank1
[INFO] Checking cert manager readiness.
issuer.cert-manager.io/test-issuer created
certificate.cert-manager.io/test-certificate created
certificate.cert-manager.io "test-certificate" deleted
issuer.cert-manager.io "test-issuer" deleted
[✔] Cert manager is ready, preload can proceed.
[INFO] Copying mongodb from namespace …
```
=> Cleanup preload

controllers/bootstrap/init.go, controllers/constant/odlm.go
I have added the necessary bindinfo for user management operator in a way mirroring keycloak. I am still trying to get the operand config to populate the operandbindinfo into the operandconfig as well as automatically create the operandbindinfo when ibm-user-management-operator is requested.
Currently, the secret `mcsp-im-integration-details` is called `mcsp-im-integration-api-key` but it's my understanding that IM is changing the name of the secret to be more generic so this may need to be updated if they do not end up calling it `mcsp-im-integration-details`.
=> Add user management bindinfo

controllers/bootstrap/init.go, controllers/constant/odlm.go
Add `AccountIAM` CR into operandConfig, and created by ODLM, then trigger operator reconciliation and deploy user management services
=> Add user management CR

controllers/constant/odlm.go
bump up user-mgmt operator channel to v1.0 in operandregistry
=> update user-mgmt operator channel in opreg

controllers/constant/odlm.go
add HA configuration for commonservice-db
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64367 and https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64375
=> [CD] add HA configuration for csdb

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manager/manager.yaml
add securityContext .ceccompProfile field to pod container
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64465
=> add securityContext .seccompProfile field

cp3pt0-deployment/common/utils.sh
check if opreq-control label exist in the subscription, 
if it is, remove it, if not, skip it
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64319
=> chech operq-control label

cp3pt0-deployment/common/utils.sh
hide error message in retry patch subscription
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64558
=> hide error message in retry

api/v3/commonservice_types.go, controllers/bootstrap/init.go, controllers/cert-manager/certificaterefresh_controller.go, controllers/cert-manager/v1_add_label_controller.go, controllers/common/util.go, controllers/commonservice_controller.go, controllers/commonservice_controller_test.go, controllers/configurationcollector/collector.go, controllers/deploy/manager.go, controllers/goroutines/cleanup_resources.go, controllers/goroutines/operator_status.go, controllers/goroutines/waitToCreateCsCR.go, controllers/operandconfig.go, controllers/operatorconfig.go, controllers/recocile_pause.go, controllers/render_template.go, controllers/render_template_test.go, controllers/suite_test.go, controllers/webhooks/commonservice/validatingwebhook.go, controllers/webhooks/operandrequest/mutatingwebhook.go, go.mod, main.go
To facilitate changes required for https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64551, we need to update the module version for the cs operator to v4 so we can specify v4 tags and releases when importing in go.mod. Should be similar to this ODLM pr that did the same https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1039/files
=> update cs module version to v4

README.md, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
update ibm common service operator description, remove `ibm-common-services` namespace in description
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64615
=> update cs-operator description

preload_data.sh
remove whole storageClassName field in cs-mongodump pvc if it is running on ROKs cluster
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64674
<details>
<summary> test logs </summary>
```
ibm-common-service-operator % ./preload_data.sh --original-cs-ns ibm-common-services --services-ns sysqa --rerun
All arguments passed into the script: --original-cs-ns ibm-common-services --services-ns sysqa --rerun
[✔] oc command logged in as IAM#pgondhalekar@in.ibm.com
[INFO] Checking cert manager readiness.
issuer.cert-manager.io/test-issuer created
certificate.cert-manager.io/test-certificate created
certificate.cert-manager.io "test-certificate" deleted …
```
=> remove whole storageClassName field in pvc on ROKs env

common/scripts/lint_go.sh, controllers/constant/odlm.go
=> [CD] bump keycloak to 24 and add fallback channel 22

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
The resource name is `zenextension/finalizers`, not `zenextension/finalizer`
=> fix typo in finalizers

controllers/constant/odlm.go
Add fallback channels for `common-service-postgresql`, `edb-keycloak` and `cloud-native-postgresql-v1.22`, so they could tolerate both `stable` and `stable-v1.22` channels.
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64744
=> add fallback channels for EDB operator

cp3-networkpolicy/egress/zen/zen-egress-zen-remote-svc-inst-status-cron-job.yaml, cp3-networkpolicy/egress/zen/zen-egress-zen-svc-inst-status-cron-job.yaml, cp3-networkpolicy/egress/zen/zen-egress-zen-watchdog-create-tables-job.yaml, cp3-networkpolicy/egress/zen/zen-egress-zen-watchdog-post-requisite-job.yaml, cp3-networkpolicy/egress/zen/zen-egress-zen-watchdog-pre-requisite-job.yaml
Zen installation failed because some of the NetworkPolicy YAML definitions were missing from the script. I manually deployed the missing YAML definitions and then successfully completed the Zen installation. Below, I have listed the YAML definitions of NetworkPolicies that I deployed on the cluster.
1. zen-egress-zen-remote-svc-inst-status-cron-job.yaml
2. zen-egress-zen-svc-inst-status-cron-job.yaml
3. zen-egress-zen-watchdog-create-tables-job.yaml
4. zen-egress-zen-watchdog-post-requisite-job.yaml
5. zen-egress-zen-watchdog-pre-requisite-job.yaml
=>  Addon egress network policy

api/v3/commonservice_types.go, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, bundle/manifests/operator.ibm.com_commonservices.yaml, config/crd/bases/operator.ibm.com_commonservices.yaml, controllers/common/util.go, controllers/operatorconfig.go
How to test
1. Deploy common-service-operator from catalogs with 4.6.6+
2. Build this PR `make build-dev-image`
3. Change image in CSV on cluster to use built image
4. Update CommonService CR with following example
5. Verify OperandRegistry contains `userManaged: true` for all postgresql entries
CommonService CR example
```yaml
metadata:
labels:
foundationservices.cloudpak.ibm.com: commonservice
spec:
license:
accept: false
operatorConfigs:
- name: common-service-postgresql
userManaged: true
operatorNamespace: byo
servicesNamespace: byo
```
=> added new flag to indicate whether service is user managed

preload_data.sh
Metrics pod user and secret values are exposed in the script. We can take the values from the existing mongo in the original namespace instead and obfuscate the value in the script itself.
Fixes #
Successful run of preload data script
3. The PR will be automatically created in the target branch after merging this PR
4. If this PR is already merged, you can still add the label with the target branch name `backport <branch-name>` and leave a comment `/backport` to trigger the backport action
=> obfuscate metrics secret values

controllers/commonservice_controller.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64775
The reconciliation request on CommonService CR is constantly generated [by the status update in OperandRegistry](https://github.com/IBM/ibm-common-service-operator/blob/963f33528827d0e73f1db0c5b53c0ec5b2cd81e9/controllers/commonservice_controller.go#L561)
By looking into the status update in OperandRegistry, the sequence of items listed in `reconcileRequests` for one operator is changing. This is due to the constant reconciliation on OperandRegistry by ODLM.
So looking into ODLM logs, ODLM is constantly reconciling OperandRequest because of missing correct Catalog for Zen operator. And the reconciliation on OperandRequest will trigger the reconciliation of OperandRegistry.
```
E0912 14:59:53.975913 1 manager.go:183] Not found …
```
=> check length of operatorsStatus in OperandRegistry to trigger the CR reconciliation

controllers/bootstrap/init.go, controllers/common/util.go, controllers/recocile_pause.go
issue: https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/28858
When there are old CS 3.x installed together with CS 4.x in the same cluster, it is usual that old CS 3.x installed later on the cluster, so entire OCP cluster is using the old CRD from CS 3.x. In this case, the field `.spec.services[*].spec` is a required field on old CRD from CS 3.x.
And we have documented that user has to explicitly set field `.spec.services[*].spec: {}` even it is empty
```
metadata:
namespace: operator-ns
spec:
license:
accept: true
operatorNamespace: latest-validated
services:
- name: common-service-postgresql
resources:
...
spec: {}
```
When CS 4.x propagates CS CR from operator namespace into other namespaces into …
=> Use Unstructured obj to copy CR to other ns

cp3pt0-deployment/migrate_tenant.sh
There is [a corner case](https://github.com/IBM/ibm-common-service-operator/blob/a61e662e2c984fe8effbd51d5203327eda9dacf0/cp3pt0-deployment/migrate_tenant.sh#L149) in `migrate_tenant.sh` where
1. **Common Service operator is upgraded to v4.x**
- So it detects its own installation mode, and clean NSS operator and CR when following requirements are all met
- NamespaceScope Operator is at v3.x level
- namespace-scope ConfigMap only contains one namespace or empty(single topology or all namespace mode)
- no `no-op` service is requested in OperandRegistry
3. **NamespaceScope Operator is not yet upgraded**
4. **All NamespaceScope CRs from CPFS v3.x are cleaned**
- So `namespace-scope` ConfigMap only contains one namespace.
CS operator will delete the NamespaceScope CR that are just created by …
=> Re-create NSS CR after NSS operator upgrade in migration

cp3pt0-deployment/setup_singleton.sh
Handle the edge case which v3 and v4 licensing operator co-existence in the same cluster.
- If multiple Licensing operators is found, we use `ibm-licensing-service-instance` deployment to ensure the exact namespace where licensing v4 is installed.
- If multiple licensing-service-instance found, error out
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64782
=> using`ibm-licensing-service-instance` deployment to ensure the exact namespace

velero/backup/common-service/env.properties, velero/backup/common-service/label-common-service.sh
Update the labeling scripts to no longer label operandconfig and the platform-auth-idp cm. After more testing with the CPD team, it is more of a hassle to include these items than it is to regenerate them. Both of these items should be configured by changes to the commonservice CR which we already backup and restore.
This change also labels the namespacescope related resources so we can move away from using setup tenant (specifically in Fusion recipes).
Fixes #
2. The PR will be automatically created in the target branch after merging …
=> stop labeling opconfig, platform-auth-idp cm, label nss

controllers/constant/odlm.go
After upgrade keycloak from 22 to 24, email will required by default. We want to keep the consistency with keycloak-22, so we need to apply a customized user-profile-config
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64707
=> [SC2] apply customized user-profile for keycloak-24

controllers/constant/odlm.go
When we wanna add the new entry in the array, it should be added at the end of array. This could avoid messing the original items in the list due to ODLM deep merge limitation.
This is the intermediate workaround to bypass the ODLM limitation in https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64707#issuecomment-91811361
The final solution will be implemented in ODLM via ticket https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64893
=> Add new entry at the end of array to bypass ODLM limitation on object update

velero/backup/mongoDB/mongo-backup.sh, velero/restore/mongoDB/mongo-restore.sh, velero/restore/mongoDB/mongodbrestore.yaml, velero/schedule/mongodb-backup-deployment.yaml
Ensure that with more restrictive SCC environments the BR resources have appropriate access to fulfill their designated tasks.
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63657
Related to https://github.com/IBM/ibm-common-service-operator/pull/2215
=> add service account to mongo BR resources

go.mod, go.sum
Fix for: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65006
=> Update go module

br-testing-automation/env.properties, br-testing-automation/fusion-backup-setup.sh, velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-multi-ns.yaml, velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-single-ns.yaml, velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml, velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
label-common-service.sh is using variable `TETHERED_NS`, but fusion-backup-setup.sh is using variable `TETHERED_NAMESPACE1="" TETHERED_NAMESPACE2=""`
We need to report new variable name for different script
since we are not labeling operandconfig, we need to remove it from recipe. Otherwise recipe will fail in backup
add fusion catalog name and common-service catalog name, so we can use different catalogsource to install cs and fusion
update namespace in the recipe
=> Fix fusion script/recipe issue found in SERT testing

Dockerfile
Reverts IBM/ibm-common-service-operator#2231
The new golang image does not appear to support ppc or s390 currently
=> Revert "Bump golang from 1.23.0-bullseye to 1.23.2-bullseye"

cp3pt0-deployment/setup_tenant.sh
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65030
Updated the version comparison logic to assess channel, ensuring that channel like `v4.10` are recognized as greater than `v4.2`, while still maintaining backward compatibility for `v4.0` and `v4.1`
=> Update channels comparison

velero/backup/common-service/label-bedrock-role.yaml, velero/backup/common-service/label-common-service.sh
**What this PR does / why we need it**: The label-common-service script currently looks for the namespacescope configmap in the services namespace instead of the operator namespace where it will always live. Also updated the role for the label job to specify rbac resources.
Fixes # https://github.ibm.com/PrivateCloud-analytics/Zen/issues/38771#issuecomment-93472154
3. If this PR is already merged, you can still add the label with the target branch name `backport <branch-name>` and leave a …
=> Correct permissions and nss cm namespace in labeling script

Dockerfile
Reverts IBM/ibm-common-service-operator#2183
Looks like this build worked 2 weeks ago, but there is no ppc or s390 1.23.1-bullseye image now so builds are failing after the version bump.  Reverting this temporarily until we can switch to bookworm.
=> Revert "Bump golang from 1.23.0-bullseye to 1.23.1-bullseye"

api/v3/commonservice_types.go, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, bundle/manifests/operator.ibm.com_commonservices.yaml, config/crd/bases/operator.ibm.com_commonservices.yaml, controllers/constant/instanaEnable.go, controllers/render_template.go
1. Install cs-operator
2. Update image on cluster with changes from this PR
3. Update CRD on cluster with changes from this PR
4. Update CommonService CR with `enableInstanaMetricCollection: true`
5. Verify that setting propagates to OperandConfig for IM and UI
=> added configuration for instana metrics collection

controllers/size/starterset_amd64.go, controllers/size/starterset_ppc64le.go, controllers/size/starterset_s390x.go
Using one replica prevents cluster upgrade due to the pod disruption budget, so set the default to use two.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65103
=> Use 2 replicas for Keycloak EDB on starterset

controllers/size/starterset_amd64.go, controllers/size/starterset_ppc64le.go, controllers/size/starterset_s390x.go
Using one replica prevents cluster upgrade due to the pod disruption budget, so set the default to use two.
cherry pick of #2256
=> Use 2 replicas for Keycloak EDB on starterset (#2256)

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/setup_tenant.sh
k8s label name length limit to 64 characters, so olm will cut off any label longer than 64 characters
We rely on label to find csv and subscription, so we also need to cut of the label if it is longer than 64 characters.
script enhancement for # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64378
(will open pr for odlm and nss operator)
=> label length limited to 64 characters

controllers/constant/odlm.go
In Keycloak 24, when it is behind re-encrypt Route, any incoming http requests fail with http/500, with NPE exception saying http Host header is missing. Seems the fix is to add the proxy headers setting to parse `x-forwarded` http header.
Fixes  https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65100 and https://github.com/keycloak/keycloak/issues/33988
Do fresh deploy of Keycloak 24 on ROSA cluster. Check Route `keycloak` created works fine and renders Keycloak Admin UI
=> Add support for Keycloak 24/re-encrypt Route

controllers/constant/odlm.go
cherry-pick of https://github.com/IBM/ibm-common-service-operator/pull/2261 to fix issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65100
=> [SC2] Add support for Keycloak 24/re-encrypt Route (#2261)

controllers/bootstrap/init.go, controllers/common/util.go
What this PR does / why we need it:
k8s label name length limit to 64 characters, so olm will cut off any label longer than 64 characters
We rely on label to find csv and subscription, so we also need to cut of the label if it is longer than 64 characters.
Which issue(s) this PR fixes:
enhancement for # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64378
=> label-length-limitation

controllers/bootstrap/init.go, controllers/bootstrap/init_test.go, controllers/common/util.go, go.mod
cherry-pick from https://github.com/IBM/ibm-common-service-operator/pull/2263  and https://github.com/IBM/ibm-common-service-operator/pull/1971
=> Odlm subcheck and label length in CD

controllers/constant/odlm.go
add new entry for ibm-events-operator-v5.1
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65011
=> [CD] new entry for event-v5.1

controllers/constant/odlm.go
Revert the changes to add the velero addon annotation and its required accompanying annotation `k8s.enterprisedb.io/snapshotAllowColdBackupOnPrimary: enabled` since we have never adopted its use in BR and it is causing problems with CPD BR process.
Originally, this was implemented because this addon method is what is officially supported by EDB and the CPD team is able to overwrite it with their own addon (external-backup-adapter). However, the `k8s.enterprisedb.io/snapshotAllowColdBackupOnPrimary: enabled` annotation is not overwritten and there is an edge case defined in the linked issue where this label is problematic. Since we do not use these sets of annotations, I believe it best to go ahead and remove them for the 4.10 release.
**Which …
=> remove velero addon and cold backup annotations

controllers/constant/odlm.go
During the upgrade, ODLM should be able to reclaim the ownership of EDB License Job `create-postgres-license-config` when the label `opreq-control` is explicitly specified in OperandConfig template
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64885#issuecomment-91863036
=> [SC2] add opreq-control label for EDB License Job

velero/schedule/common-service-db/cs-db-backup-deployment.yaml
**What this PR does / why we need it**: Ran into a problem when working with CP4BA testing where the database dir and its contents were not carried over from backup cluster to restore cluster. After some trial and error, the necessary files were copied over after removing the line where the database dir was removed as part of the backup posthook. We need the dir to be gone for the script to run smoothly but we can remove it at the beginning of a run instead of at the end to side step this problem where the dir is never present after restore. 
What makes this test weird is I am not sure I have ever seen this be a problem, we have had this pre/posthook setup since we started BR'ing EDB. But this change should be more consistent and it matches what we do with zen so I think it's worth …
=> [scripts dev] change when the database dir cleanup takes place

velero/schedule/common-service-db/cs-db-backup-deployment.yaml
**What this PR does / why we need it**: Exact same change as https://github.com/IBM/ibm-common-service-operator/pull/2270 but ported to the scripts branch. See there for more details
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65149
=>  [scripts] change when the database dir cleanup takes place

cp3-networkpolicy/egress/flink/bedrock-egress-ibm-flink-operand.yaml, cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operand.yaml, cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operator.yaml, cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operand.yaml, cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operator.yaml, cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operand.yaml, cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operator.yaml
cherry-pick from https://github.com/IBM/ibm-common-service-operator/pull/2246
=> update flink and opensearch networkpolicy port

controllers/size/large_amd64.go, controllers/size/large_ppc64le.go, controllers/size/large_s390x.go, controllers/size/medium_amd64.go, controllers/size/medium_ppc64le.go, controllers/size/medium_s390x.go, controllers/size/small_amd64.go, controllers/size/small_ppc64le.go, controllers/size/small_s390x.go, controllers/size/starterset_amd64.go, controllers/size/starterset_ppc64le.go, controllers/size/starterset_s390x.go
Reverts IBM/ibm-common-service-operator#2229
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64521#issuecomment-94988153
=> Revert "Update size limit for shared EDB"

cp3pt0-deployment/common/utils.sh, cp3pt0-deployment/setup_singleton.sh
We should only wait for ibm-licensing-instance when ibm-licensing operator is found, it could help to reducing the waiting time.
=> conditionally wait for ibm-licensing-instance

controllers/constant/cloudNativePostgresql.go
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64969
=> Pick up EDB 1.22.7 images for release 4.6.8

controllers/constant/odlm.go
**What this PR does / why we need it**: 
Added zen deployment `meta-api-deploy` with label `operator.ibm.com/opreq-control: 'true'` into each zen/platformui operator entry in OperandConfig so that ODLM can delete this specific deployment when the Zen/Platform operator is removed.
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64488
1. test image: quay.io/yuchen_shen/cs_operator:cleanzen
2. test step could refer to:  https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1095
=> Add meta api deployment in zen/platformUI entries

controllers/constant/odlm.go
Update namespace as service namespace for v3 meta api deployment
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64488
=> Update zen deployment meta api ns

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/bootstrap/init.go, controllers/constant/constant.go, main.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64483
Clean up unused resources when upgrading from the v3 operator:
-  MutatingWebhookConfiguration ibm-common-service-webhook-configuration
-  MutatingWebhookConfiguration ibm-operandrequest-webhook-configuration
- ValidatingWebhookConfiguration ibm-cs-ns-mapping-webhook-configuration 
- secretshare in all namespaces
- podpresets.operator.ibm.com in all namespaces
- deployment ibm-common-service-webhook in ibm-common-services 
- deployment secretshare in ibm-common-services
test image: quay.io/yuchen_shen/cs_operator:cleanv3
=> Clean up v3 leftover resources

controllers/constant/odlm.go
cherry-picked https://github.com/IBM/ibm-common-service-operator/pull/2278
=> Meta api entry cherry-pick

controllers/bootstrap/init.go, controllers/bootstrap/init_test.go, controllers/commonservice_controller.go
CS operator should wait ODLM to be upgraded, which will bring new schema for the ODLM CRDs before CS operator apply the latest OperandRegistry and OperandConfig CRs. Otherwise, it is possible that new field in ODLM CRs is pruned by old CRDs.
1. After ODLM is upgraded to desired version via `waitOperatorCSV` func, the OperandRegistry and OperandConfig will be refreshed.
2. Improve function `waitOperatorCSV` to get the subscription by name first, because there is a chance that the label added by OLM is not immediately available.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65138
1. Install Dev build of CPFS
2. Observe the logs that it does not refresh OperandRegistry and OperandConfig after waiting for …
=> Update ODLM CRs after ODLM is upgraded to desired version

controllers/bootstrap/init.go, controllers/bootstrap/init_test.go, controllers/commonservice_controller.go
cherry-pick of #2280 
To solve issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65138
=> [CD] Update ODLM CRs after ODLM is upgraded to desired version (#2280)

controllers/operandconfig.go
Currently limited to setting `.spec.services[].resources.data.resources.limits.cpu` to `{}` value instead of entire `limits` field because some internal functionality is removing the `{}` value for entire `limits` field.
The code as-is will work regardless because when one of the k8s resources fields gets set to `{}`, then ODLM will ignore sizing.
How to test
1. build image from this PR
2. install cs-operator on your cluster
3. update image on cluster with image from step 1
4. add the following to CommonService CR `profileController: turbo`
5. verify that OperandConfig has `cpu: {}` for the EDB and Keycloak CRs
=> updated turbo profile controller to handle data.resource

velero/backup/common-service/label-common-service.sh
stop labelling operandrequest which is generated by odlm or other services, those operandrequests should be regenerated in restore. 
We should only label primary OperandRequests
Fixes # https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/31736
=> exclude internal generated operandrequest from Backup/Restore

velero/backup/common-service/label-common-service.sh
**What this PR does / why we need it**: add common-web-ui-config cm to labeling script so it can be included in the backup
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65250
=> add common-web-ui-config cm to labeling script

velero/backup/common-service/label-common-service.sh
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64979
cherry pick: https://github.com/IBM/ibm-common-service-operator/pull/2273
=> exclude internal generated operandrequest from Backup/Restore (#2273)

controllers/goroutines/cleanup_resources.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65226
The ConfigMap `mongodb-preload-endpoint` will be removed if an MongoDB statefulSet with owner Reference is running  in the service namespace.
An MongoDB statefulSet with owner Reference indicates that it is an active instance in CPFS 4.0-4.5, and it will be used for IM database migration, meaning the ConfigMap `mongodb-preload-endpoint` is no longer required.
1. Install CS operator from daily CD build.
2. Create following dummy ConfigMap `mongodb-preload-endpoint`
```yaml
apiVersion: v1
metadata:
name: mongodb-preload-endpoint
labels:
app.kubernetes.io/component: database
app.kubernetes.io/instance: mongodb-preload-endpoint
app.kubernetes.io/managed-by: preload_data.sh
app.kubernetes.io/name: …
```
=> Clean MongoDB preload ConfigMap when the local MongoDB instance is owned by CR

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Fix https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65347
Test result: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65347#issuecomment-97316777
1. Install latest CPFS 4.10 dev build with full permission in advanced topology
2. Create OperandRequest to install IM, Zen and Events services
```yaml
kind: OperandRequest
metadata:
spec:
requests:
- operands:
- name: ibm-im-operator
- name: ibm-platformui-operator
- name: ibm-events-operator
registry: common-service
```
3. Create ZenService CR
```yaml
apiVersion: zen.cpd.ibm.com/v1
kind: ZenService
metadata:
name: lite-zen
spec:
blockStorageClass: rook-ceph-block
fileStorageClass: rook-cephfs
iamIntegration: true
iam_provider_card_enabled: true
```
4. After ZenService CR …
=> add related permission for MongoDB cleanup in post DB migration

isolate.sh
Base on comment: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65281#issuecomment-96802240
- `isolate.sh` requests and checks cert manager before and after isolation IFF `ibm-cert-manager-operator` is requested via OperandRequest in the tenant before isolation.
- `isolate.sh` would check a cert manager presenting **BEFORE** isolation if any OperandRequest in the tenant contains operand `ibm-cert-manager-operator`.
- if no `ibm-cert-manager-operator` is requested in OperandRequest, skip checking if cert manager deployment in the cluster
- `isolate.sh` would wait for cert manager presenting  **AFTER** isolation only if `isolate.sh` checked cert manager presenting before isolation.
Fixes # …
=> isolate script should check if cert manager is requested before isolation

controllers/constant/odlm_operatorconfig.go, controllers/operatorconfig.go
- When ODLM configures Postgres operator pod with multiple replicas, ODLM will update overwrite the entire `Affinity` field for Postgres operator CSV/deployment. So the configuration for Postgres Operator should contain necessary `nodeAffinity` to ensure pods are distributed on nodes with supported architecture.
- Add an new entry for `cloud-native-postgresql-v1.22` in OperatorConfig, so the Postgres operator requested via `cloud-native-postgresql-v1.22` will get the multi replicas configuration as well.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65071
1. Install dev build of SC2 4.6.x
2. Patch CS operator CSV with image `docker-na-public.artifactory.swg-devops.com/hyc-cloud-private-scratch-docker-lo …
=> Add nodeAffinity for Postgres operator, and add new entry cloud-native-postgresql-v1.22

controllers/bootstrap/init.go
This is an issue where resources outside the runtime cache scope caused errors during retrieval and deletion. Using `Reader.Get()` instead of `Client.Get` in `deleteResource` function to bypass the cache when necessary, ensuring reliable access to all resources.
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65386
Test image: quay.io/yuchen_shen/cs_operator:error_msg
1. Install v4 in single namespace
2. See the following error msg:
```
I1128 16:04:26.927875 1 init.go:960] MutatingWebhookConfiguration /ibm-common-service-webhook-configuration not found, skipping deletion
I1128 16:04:26.931228 1 init.go:960] MutatingWebhookConfiguration /ibm-operandrequest-webhook-configuration not found, skipping deletion
I1128 16:04:26.934923 1 init.go:960] ValidatingWebhookConfiguration …
```
=> Use Reader.Get() to retrieve the resource outside of cache scope

controllers/bootstrap/init.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65386
Cherry-pick: https://github.com/IBM/ibm-common-service-operator/pull/2315
=> Use Reader.Get() to retrieve the resource outside of cache scope (#2315)

cp3pt0-deployment/common/cleanup_cp2_control.sh, cp3pt0-deployment/common/utils.sh
cleanup Namespace scope operator and cs-webhook service
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65254
=> cleanup cs-control

velero/backup/common-service/label-common-service.sh, velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-multi-ns.yaml, velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-single-ns.yaml, velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns-multi-zen.yaml, velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml, velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65357
=> Refresh Recipe by removing setup tenant job

controllers/goroutines/cleanup_resources.go, controllers/goroutines/operator_status.go, controllers/goroutines/waitToCreateCsCR.go, main.go
Go routines in ibm-common-service operator relies on operator [controller's cache](https://github.com/IBM/ibm-common-service-operator/blob/b947cd93e81eccefd769c64628de3c730fa1797a/main.go#L124) to be ready. It will be ready when [Manager is set up](https://github.com/IBM/ibm-common-service-operator/blob/b947cd93e81eccefd769c64628de3c730fa1797a/main.go#L253). So we need to suspend go routines until manager is setup
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58246
=> suspend go routines until operator cache is ready

velero/schedule/common-service-db/cs-db-backup-deployment.yaml, velero/schedule/keycloak/keycloak-backup-deployment.yaml, velero/schedule/license_service_reporter/lsr-backup-deployment.yaml, velero/schedule/mongodb-backup-deployment.yaml, velero/schedule/zen-backup-deployment.yaml, velero/schedule/zen5-backup-deployment.yaml
Add on-error annotations for Velero hooks
If script specified in velero hooks failed, the status of restore CR should be fail as well.
Enhancement for # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62663
=> add on-error annotation for Velero hooks

controllers/goroutines/cleanup_resources.go, controllers/goroutines/operator_status.go, controllers/goroutines/waitToCreateCsCR.go, main.go
Given there are multiple receivers(multiple go routines) on a single channel `ch := make(chan *bootstrap.Bootstrap)` and we are only sending one data into the channel  `ch <- bs`, only a single random go routines will receive the data, and unblock the code. See [this article](https://stackoverflow.com/questions/31539804/multiple-receivers-on-a-single-channel-who-gets-the-data) for details
Thus, it is complicated to use the same single channel for multiple go routines. Instead we just start go routines after cs controller manager is set properly.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65568
After applying the dev build image `docker-na-public.artifactory.swg-devops.com/hyc-cloud-private-scratch-do …
=> start go routines after cs controller manager setup

preload_data.sh
preload_data script should delete storageclass from cs cr 
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65562
=> delete storageclass from cs cr

preload_data.sh
Update the Certificate icp-mongodb-client-cert in original namespace to include the DNS name `mongodb.<original-ns>.svc.cluster.local`
Fixes #  https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65642
=> add full DNS name to mongo certificate

controllers/constant/odlm.go
**What this PR does / why we need it**: 
If the clients that want to exchange tokens for a different client need to be authorized in the Admin Console, so a token-exchange fine grain permission `- admin-fine-grained-authz` was enabled by default in Keycloak CR
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65708
1. After `- admin-fine-grained-authz` is enabled, the permission section in the client is shown up
_**Before adding into CR:**_
_**After**:_
**Doc reference:** 
https://www.keycloak.org/securing-apps/token-exchange#_internal-token-to-internal-token-exchange
=> Enable granting permission for token exchange

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
..as defined in https://docs.redhat.com/en/documentation/red_hat_software_certification/2024/html-single/red_hat_openshift_software_certification_policy_guide/index#con-operator-requirements_openshift-sw-cert-policy-products-managed and required by RH Certification
OLM has introduced several required annotations which operator bundle is missing.
=> Adding OLM required metadata

controllers/constant/cloudNativePostgresql.go
**What this PR does / why we need it**: 
Pick up PostgreSQL 14.15 image for CP4I consuming the latest version EDB 1.22.8
Cherry pick:  https://github.com/IBM/ibm-common-service-operator/pull/2347
=> Pick up PostgreSQL 14.15 image

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
cherry-pick: https://github.com/IBM/ibm-common-service-operator/pull/2339
Adding OLM required metadataas defined in https://docs.redhat.com/en/documentation/red_hat_software_certification/2024/html-single/red_hat_openshift_software_certification_policy_guide/index#con-operator-requirements_openshift-sw-cert-policy-products-managed and required by RH Certification
OLM has introduced several required annotations which operator bundle is missing.
=> Adding OLM required metadata (#2339)

controllers/bootstrap/init.go, controllers/commonservice_controller.go, main.go
The common-service-operator makes use of some OLM APIs, which need to be de-coupled so that cs-operator can be installed and work in cluster without OLM.
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65720
=> Decouple common service operator from OLM

preload_data.sh
enhancement for DNS name patch, previous PR only update the DNSnames in certificate `icp-mongodb-client-cert` is not enough, this certificaet isn't used directly by the MongoDB runtime. Mongodb init container will use a leaf certificate and that leaf certificate is signed by `icp-mongodb-client-cert`, we need to update that leaf certificate instead.
While preload_data.sh is executed, the script would:
1. Scale down ibm-mongodb-operator
2. Update the script in icp-mongodb-init CM's .data["on-start.sh"] [field](https://github.com/IBM/ibm-common-service-operator/blob/scripts-dev/preload_data.sh#L2037) and add the additional DNS names
3. Trigger a rolling upgrade on the icp-mongodb StatefulSet, adding `migrating: "true"` to …
=> Mongo certficate DNS name patch

helm-cluster-scoped/Chart.yaml, helm/Chart.yaml, helm/templates/operator-deployment.yaml, helm/values.yaml
added operatorVersion variable to values.yaml
fixed typo for entitlement key
=> updated helm chart version to 4.11.0

helm/templates/operator-deployment.yaml, helm/values.yaml
because Chart.yaml is less accessible for configuration
=> changed from using Chart.AppVersion to values.yaml

controllers/bootstrap/init.go, controllers/commonservice_controller.go
**What this PR does / why we need it**: EDB image list ConfigMap will be included in EDB helm charts,  and cs oeprator will not manager this ConfigMap in non-OLM case any more.
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65815
**How the test is done**:
Test image: quay.io/yuchen_shen/cs_operator:edb
1. Apply image in OLM-base operator, the ConfigMap `cloud-native-postgresql-image-list` is still created with log 
```
I0211 03:03:41.575718 1 init.go:228] It is not a non-OLM mode, create EDB Image ConfigMap
```
2. Apply image in non-OLM deployment, ConfigMap will not shown up with log
```
I0211 03:03:28.390738       1 commonservice_controller.go:133] It is a non-OLM mode, skip creating EDB Image ConfigMap...
```
=> Removed EDB image list created by cs operator for non-olm case

cp3pt0-deployment/migrate_tenant.sh
- Since CPFS 4.11, we have to bump up ODLM channel for each future release, then updating the ODLM channel in `migrate-tenant.sh` as well
- ODLM channel is still kept as v4.3 between CPFS v4.5 and v4.10.
- ODLM channel is the same as CPFS channel if it is less than 4.5
Issue:  https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65907
=> Update ODLM channel with v4.4 for CPFS v4.11

Makefile, controllers/bootstrap/init.go, controllers/common/util.go, controllers/commonservice_controller.go, controllers/constant/constant.go, controllers/deploy/manager.go, controllers/goroutines/no_olm_operator_status.go, main.go
Refactor cs-operator to de-couple it from OLM API
Enable common-service controller, so most of the key feature in cs-operators working in no olm environment, except:
1. webhooks (need to create webhook service and inject webhook-secret)
2. odlm and nss cleanup if it is upgrade from LTSR (need to cleanup sub and csv)
3. ~~operator status check (need to check deployment instead of sub and csv)~~
Fixes #  https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65720
=> refactor cs-operator to enable common-service controller

bedrock-migration/.helmignore, bedrock-migration/Chart.yaml, bedrock-migration/templates/adopt-cs-cr.yaml, bedrock-migration/templates/adopt-nss-cr.yaml, bedrock-migration/templates/bedrock-migration-job.yaml, bedrock-migration/templates/rbac.yaml, bedrock-migration/values.yaml
Create migration job chart for migration from OLM install to no OLM install for bedrock components.
Job is based on CPD migration template found here https://github.ibm.com/Mengdie-Chu/non-olm-installer/tree/main/charts/cpd-platform-migration and essentially runs a script where the sub, csv, and rbac for installer and bedrock services are cleaned up so they can be replaced by a helm install. CRs like NSS and CS are included to "adopt" the existing ones without outright replacing them.
Cleans up services and tethered namespaces as well.
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65830
- Install CS, ODLM, NSS, IM, EDB, and UI via OLM (so …
=> create olm -> no olm migration chart in master branch

Dockerfile, Makefile, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, common/scripts/next-csv.sh, config/ibm-common-service-operator.yaml, config/manager/kustomization.yaml, config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
- name: Image name ✅
- maintainer: Maintainer name 🔴
- vendor: Company name ✅
- version: Version of the image 🔴
- release: A number used to identify the specific build for this image 🔴
- summary: A short overview of the application or component in this image ✅
- description: A long description of the application or component in this image ✅
- `com.redhat.openshift.versions: v4.12-v4.17`
- `icr.io/cpopen/common-service-operator:4.11.0`
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65704
following the instructions here run the pipeline certification against your own repo. https://ibm-analytics.slack.com/archives/C08CCB76L0J/p1739552810788419
Please let me know if you are not able to access the above link
=> Add corresponding metadata to pass RH certification

Makefile, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manager/non-olm-env-patch.yaml
When we run `make generate-all` to update the bundle for RH certification, the non-OLM env variables are accidentally added into the `bundle` folder from `config` folder.
Makefile is updated, so that `make generate-all` will not add non-OLM env variables into bundle folder.
Those non-OLM env variables will only be introduced when it is rendering the helm chart via `make helm`.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65966
=> Remove non-OLM env from OLM bundle

controllers/constant/odlm.go
**What this PR changes**:
- Scheduling Enhancements:
- Keycloak 26 CRD intrduced: 
`.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.scheduling`
- Added `spec.scheduling` with affinity spread constraints to ensured compatibility across node architectures
- Keycloak 26 doc reference: https://www.keycloak.org/operator/advanced-configuration#_scheduling
- Startup and Readiness Probe Adjustments:
-  Increased `initialDelaySeconds` for `startupProbe` to handle longer initialization times and avoid the error msg: 
```
Startup probe failed: Get "https://10.254.19.137:9000/health/started": dial tcp 10.254.19.137:9000: connect: connection refused
```
Fixes # 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65326#issuecomment-101278516 …
=> Enhance Keycloak 26 pod scheduling and startup probe configurations

preload_data.sh
preload_data script will scale down mongodb operator and never scale it up.
In this case, mongodb operartor will not revert the changes in icp-mongodb-init configmap
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65937
=> scale down mongodb operator 

api/v3/commonservice_types.go, controllers/bootstrap/init.go, controllers/constant/odlm.go
Introduce `ServiceNames` as a slice of strings in CSData to include all the EDB version (1.18, 1.22 and 1.25). This allows for better maintainability and flexibility when adding or modifying EDB configs in the future.
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65976
1. Test image: `quay.io/yuchen_shen/cs_operator:edb`
2. Check `operandRegistry` and `operandConfig` created with correct `cloud-native-postgresql-v1.25` entry.
=> Generate EDB config template for all EDB service versions using

controllers/rules/rules.go, controllers/size/large_amd64.go, controllers/size/large_ppc64le.go, controllers/size/large_s390x.go, controllers/size/medium_amd64.go, controllers/size/medium_ppc64le.go, controllers/size/medium_s390x.go, controllers/size/small_amd64.go, controllers/size/small_ppc64le.go, controllers/size/small_s390x.go, controllers/size/starterset_amd64.go, controllers/size/starterset_ppc64le.go, controllers/size/starterset_s390x.go
Support different default shared_buffers values for common-service-db cluster by sizing configuration
Cherry-pick: https://github.com/IBM/ibm-common-service-operator/pull/2403
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65422
=> Support shared buffer values for common service db cluster

helm/templates/operator-deployment.yaml
Originally was .Values.imageRegistryNamespaceOperator which didn't reference imageRegistryNamespaceOperator value correctly. Added the correct referencing.
Fixes #
=> Fixed reference value for imageRegistryNamespaceOperator

preload_data.sh
increas timeout limit and cleanup resource in rerun
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65997
=> increas timeout limit and cleanup resource in rerun

controllers/operandconfig.go, controllers/rules/resource_comparison.go
The resource quantities of `shared_buffers` like `96MB`, `1GB` are not the standard resource quantity formats in Kubernetes like `96M`, `1G`.
When Common Service Operator is doing the resource comparison across multiple CommonService CRs, it returns error for `96MB`
```
quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```
The PR is to normalize the resource quantity before value comparison by converting `96MB` to `96M`.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66050
1. Install latest dev build
2. Patch CSV with image `docker-na-public.artifactory.swg-devops.com/hyc-cloud-private-scratch-docker-local/ibmcom/common-service-operator-amd64:dev` and change …
=> Add shared_buffers to comparable keys and normalize resource quantity formats

internal/controller/commonservice_controller.go, internal/controller/no_olm_commonservice_controller.go
There is a corner case that Cs operator is hitting [an error from line 289](https://github.com/IBM/ibm-common-service-operator/blob/1a36d1997101cdbc5414933994cf5c510fa95090/internal/controller/commonservice_controller.go#L289).
However, there is a discrepancy between [what err is returned from `err := r.Bootstrap.UpdateEDBUserManaged()`](https://github.com/IBM/ibm-common-service-operator/blob/1a36d1997101cdbc5414933994cf5c510fa95090/internal/controller/commonservice_controller.go#L285C5-L285C46) and [what error is returned for reconciliation](https://github.com/IBM/ibm-common-service-operator/blob/1a36d1997101cdbc5414933994cf5c510fa95090/internal/controller/commonservice_controller.go#L290). Thus, the error was not actually returned to trigger the …
=> handle error returning

helm/templates/operator-deployment.yaml, helm/values.yaml
To handle different dev images being in different dev registries. Has no impact for GA
=> added cpfs specific imagePullPrefix, use global if empty

velero/backup/common-service/label-common-service.sh
**What this PR does / why we need it**: Update the labeling script to include the cluster scoped resources now that we append the operator namespace to the end of the resource name.
Fixes # related to https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65980
=> add op namespace value to each cluster scoped resource name

internal/controller/constant/odlm.go
Enable dynamic backchannel and hostnamev configuration in OperandConfig for keycloak 26+
keycloak 26: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65922
1. Test image: `quay.io/yuchen_shen/cs_operator:hostnamev2`
2. Install keycloak 26+
3. Apply ODLM image:  `quay.io/yuchen_shen/odlm:templating`
4. Check if kc 26 is working
=> Enable dynamic backchannel and hostnamev configuration in OperandConfig

bedrock-migration/templates/bedrock-migration-job.yaml, bedrock-migration/templates/rbac.yaml
**What this PR does / why we need it**: Part of the migration job is to verify the NSS CR is deleted when NSS is uninstalled. Currently, the job does not possess enough permissions to do so
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66194
=> add permissions to delete and patch nss cr

internal/controller/bootstrap/init.go
CommonService Operator should skip checking `no-op` operator status since `no-op` operator will no longer be deployed by ODLM. If CommonService Operator is trying to check `no-op` operator's status, its status will never go into `Ready`.
=> Skip no-op operators when retrieving operator status

api/v3/commonservice_types.go, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manager/manager.yaml, internal/controller/bootstrap/init.go, internal/controller/common/util.go, internal/controller/constant/odlm.go
**What this PR does**: In Keycloak 24 and 26, it supports the truststore field directly defined in the spec field, allowing to specify the secret in it. Additionally, when running on a Kubernetes or OpenShift environment, well-known locations of trusted certificates, such as `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`, are included automatically. 
Therefore, we can remove the import of kube service account certificates from the startup script.
Doc reference: https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/26.0/html/operator_guide/advanced-configuration-#advanced-configuration-truststores
**Issue**: 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65326#issuecomment-101278352
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65678 …
=> Enhance Keycloak 26 truststore file and sa certs import

api/v3/commonservice_types.go, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/manager/manager.yaml, internal/controller/bootstrap/init.go, internal/controller/common/util.go, internal/controller/constant/odlm.go
In Keycloak 24 and 26, it supports the truststore field directly defined in the spec field, allowing to specify the secret in it. Additionally, when running on a Kubernetes or OpenShift environment, well-known locations of trusted certificates, such as `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`, are included automatically.
Therefore, we can remove startup script which includes truststore setup and the import of kube service account certificates.
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65326#issuecomment-101278352
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65678
1. Test image: `quay.io/yuchen_shen/cs_operator:truststore`
2. Check the new created `common-service` OperandConfig with the new optionalFields, this mean, if it is new CRD with …
=> Remove truststore startup script for keycloak 24 and 26

Makefile, bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/ibm-common-service-operator.yaml, config/rbac/role.yaml, helm/templates/rbac.yaml, internal/controller/bootstrap/init.go, internal/controller/common/util.go
The issue happened on both olm and no-olm environment
- cs-operator is looking for `common-services-maps`and `namespace-scope` in [serviceNamespace](https://github.com/IBM/ibm-common-service-operator/blob/master/internal/controller/bootstrap/init.go#L1966),but they are not in service namespace in 4.x version, so it will return an empty value
- we [forgot to check](https://github.com/IBM/ibm-common-service-operator/blob/master/internal/controller/bootstrap/init.go#L2054) if input values is nil or not before we update the label
- cs-operator don't have update permission on certificates and issuers, so it can't update the label in those resources
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66196
=> Enhancement on EnsureLabels function

bedrock-migration/templates/adopt-cs-cr.yaml, bedrock-migration/templates/bedrock-migration-job.yaml, bedrock-migration/templates/rbac.yaml
**What this PR does / why we need it**: Resolves issue with certain resources being created by the edb chart. These resources are ok to be regenerated and do not need to be carried over so we can remove them in the migration process and allow the EDB chart to recreate them as normal.
Fixes #
=> Remove image list cm and edb config secret during migration

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
**What this PR does / why we need it**: EDB 1.25 introduces new permissions that are not currently accounted for in the min rbac yaml causing some problems with deployments using nss min rbac
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66139
=> update min rbac permissions for edb 1.25

internal/controller/constant/odlm.go
Update postgresql operator to 1.25.1 for both `common-service-postgresql ` and `cloud-native-postgresql`
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65978
=> Adopt postgresql operator to 1.25.1 for CS 4.6.12

internal/controller/constant/odlm.go
Update postgresql operator to 1.25.1 for both `common-service-postgresql ` and `cloud-native-postgresql`
Cherry-pick: https://github.com/IBM/ibm-common-service-operator/pull/2456
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65978
=> Adopt postgres operator to 1.25.1 (#2456)

internal/controller/bootstrap/init.go, internal/controller/commonservice_controller.go, internal/controller/configurationcollector/collector.go, internal/controller/constant/constant.go, internal/controller/constant/odlm.go
Enhance the Common Service Operator to support dynamic default channel fallback channels management for operators in the OperandRegistry.
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66249
1. Test image: quay.io/yuchen_shen/cs_operator:keycloak_version
2. Change `keycloak_preferred_channel` in `ibm-cpp-config` configmap and check if the channels for keycloak are updated in Opreg
=> Implement dynamic default and fallback channels for operators in OperandRegistry

internal/controller/constant/odlm.go
Update stable-v25 for Keycloak EDB fallback channel list
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65978
=> update fallback channels for Keycloak EDB

internal/controller/constant/odlm.go
Update stable-v25 for Keycloak EDB fallback channel list
Cherry-pick: https://github.com/IBM/ibm-common-service-operator/pull/2461
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65978
=> Update fallback channels for Keycloak EDB (#2461)

internal/controller/constant/cloudNativePostgresql.go
Update EDB operand image and License image reference in `cloud-native-postgresql-image-list`
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65977
=> Update Postgresql 1.25.1 operand image for CASE 5.15.0

internal/controller/constant/odlm.go
As the script is not used since Keycloak v24, move customized user-profile declarative config onto `AdditionalOptions` in Keycloak CR directly.
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66272
1. Test image: quay.io/yuchen_shen/cs_operator:sc2_kc_profile
2. login keycloak console, CloudPak/ Email field is required is on `OFF` by default
=> Move customized user profile config onto additional options

internal/controller/constant/odlm.go
As the script is not used since Keycloak v24, move customized user-profile declarative config onto `AdditionalOptions` in Keycloak CR directly.
Cherry-pick: https://github.com/IBM/ibm-common-service-operator/pull/2468
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66272
1. Test image: quay.io/yuchen_shen/cs_operator:sc2_kc_profile
2. login keycloak console, CloudPak/ Email field is required is on `OFF` by default
=> Move customized user profile config under additional options

go.mod, go.sum, internal/controller/constant/odlm.go
- Consolidate OperandConfig for entry `keycloak-operator` and `keycloak-operator-v26`
- Consolidate OperandConfig for entry `cloud-native-postgresql`, `cloud-native-postgresql-v1.22` and `cloud-native-postgresql-v1.25`
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66289
=> adopt configName in OperandRegistry API

internal/controller/constant/odlm.go
Add labels into topologySpread `zone` and `region` for EDB Cluster pod
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65924
1. Build dev image and patch it on the cluster.
2. The OperandConfig would be updated the template containing the labelselector
3. Create OperandRequest to request `common-service-postgresql`
4. Observe `common-service-db` pod having label selector for `topologyKey: topology.kubernetes.io/zone` and `topologyKey: topology.kubernetes.io/region`
=> [SC2] add labelSelector for common-service-db in topology constraints

Makefile, api/v3/commonservice_types.go, config/crd/bases/operator.ibm.com_commonservices.yaml, internal/controller/bootstrap/init.go, internal/controller/commonservice_controller.go, internal/controller/constant/certmanager.go, internal/controller/no_olm_commonservice_controller.go
add `manage-cert-rotation: yes` label to cs-ca-certificate CR 
update operator code to ignore reconciling `renewBefore` field
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66198
How the test is done?
we could use this image to test `quay.io/yuchen_li1/common-service-operator-amd64:dev`
1. update the RenewBefore time in cs-ca-certificate
2. delete cs-operator pod to trigger a new reconcile
3. updated renewBefore time shouldn't get reverted after a new reconcile
5. The PR will be automatically created in the target branch after merging this PR
6. …
=> add `manage-cert-rotation: yes` label to cs-ca-certificate CR 

helm/templates/operator-deployment.yaml
if Values.cpfs.labels is empty in helm chart, the last ',' in labels might cause issue in creating commonservice cr, so we need to move it into loop
=> remove last , in commonservice label template

internal/controller/bootstrap/init.go
When CS operator detects a no-op operator requested by users from OperandRegistry status, it should skip checking no-op operator status given no-op operator will not deployed by ODLM
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66456
=> [CD] add handling for no-op mode in operator status checks

velero/schedule/common-service-db/cs-db-br-script-cm-4.6.10.4.11.yaml, velero/schedule/common-service-db/cs-db-br-script-cm.yaml
**What this PR does / why we need it**: Checking column output can be unstable since columns are not always in the same position cluster to cluster. Changed to check the actual completion condition in the job instead at the suggestion of Arie from CPD
Fixes #
=> make oidc job completion check more stable

internal/controller/constant/odlm.go
Based on the CRD schema, the `backchannel-dynamic` setting should be configured as a boolean property under the `hostname` section, not as an option in additionalOptions
**Which issue(s) this PR fixes** 
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66572
1. Test images
CS: quay.io/yuchen_shen/cs_operator:kc_warning
ODLM: quay.io/yuchen_shen/odlm:kc_warning
2. Install CS 4.6.14 and replaced by above images
3. Request a Keycloak 26 and check the `backchannelDynamic` is under `hostname` field and no warning msg
=> Update backchannel-dynamic as the first-class citizen of the Keycloak CR

internal/controller/constant/odlm.go
upgrade zen default channel to v6.2
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66595
=> upgrade zen default channel to v6.2

internal/controller/constant/odlm.go
add an new entry in operandreg for ibm-events-operator-v5.2
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66631
=> add an new entry for events v5.2

common/scripts/lint_go.sh, internal/controller/constant/odlm.go
By using EDB CASE 5.16+, request EDB 1.22/1.25. 
1. ODLM will read `cloud-native-postgresql-operand-images-config` ConfigMap, find the image digest and then put the value into Cluster CR `.spec.imageName`
2. If such ConfigMap does not exist, ODLM will fall back to read from `cloud-native-postgresql-image-list` ConfigMap to update imageName as before
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66594
1. Test Image: quay.io/yuchen_shen/cs_operator:edb_cm
2. Change the test image for cs operator and request `ibm-im-operator`
3. Check the value under `.spec.imageName` in the Cluster CR is the same as the value in `cloud-native-postgresql-operand-images-config` ConfigMap
=> Update the image digest in the Cluster CR as referenced from the ConfigMap in the PostgreSQL operator bundle

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, bundle/manifests/operator.ibm.com_commonservices.yaml
Follow up PR because the previous one did not update the bundle manifests https://github.com/IBM/ibm-common-service-operator/pull/2507
=> updated bundle CRD with hpa toggle

cp3pt0-deployment/migrate_tenant.sh, cp3pt0-deployment/setup_tenant.sh
Modify the maintained channel logic to:
- Keeps the existing logic to set `MAINTAINED_CHANNEL=$CHANNEL` when CS channel is less than v4.2
- Adds a new condition to set `MAINTAINED_CHANNEL="v4.3"` when CS channel is greater than v4.12
- For any other CS case (v4.2-v4.12), it keeps the default value of `MAINTAINED_CHANNEL="v4.2"`
- Keep ODLM channel same as `MAINTAINED_CHANNEL` when CS channel is less than v4.5
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66642
=> Update NSS operator channel logic for CPFS 4.13

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml, helm/templates/rbac.yaml, internal/controller/bootstrap/init.go, internal/controller/commonservice_controller.go, internal/controller/constant/cloudNativePostgresql.go, internal/controller/constant/constant.go
Postgres operator webhook will deny the EDB Cluster CR update when the update contains both image and configuration changes.
```
- failed to update k8s resource -- Kind: Cluster, NamespacedName: aiops/common-service-db: failed to update k8s resource -- Kind: Cluster, NamespacedName: aiops/common-service-db: admission webhook "vcluster.k8s.enterprisedb.io" denied the request: Cluster.cluster.k8s.enterprisedb.io "common-service-db" is invalid: spec.imageName: Invalid value: "icr.io/cpopen/edb/postgresql:16.8@sha256:43599de779d84195ffc7558541883545068aec300a2b745303327ea8b7b5aaf4": Can't change image name and configuration at the same time. There are differences in PostgreSQL configuration parameters: …
```
=> Add functionality to wait for Postgres Cluster image updates before applying configuration setting

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Add the necessary permissions for new version events operator 5.2.0
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66711
=> Add new permission in nss managed role for Events 5.2.0

api/v3/commonservice_types.go, bundle/manifests/operator.ibm.com_commonservices.yaml, config/crd/bases/operator.ibm.com_commonservices.yaml, internal/controller/bootstrap/init.go, internal/controller/constant/odlm.go, internal/controller/webhooks/commonservice/validatingwebhook.go
1.  User-Configurable Catalog Source for Services:
*   Adopters can now specify their preferred catalog source (`spec.catalogName` and `spec.catalogNamespace`) directly in the `CommonService` CR.
*   These values, when provided, will be propagated to `status.configStatus` in CS CR and subsequently used into `OperandRegistry`
*   Operators and services deployed will then be sourced from this user-defined catalog
*   If they are not provided in the CS CR, ODLM will select appropriate catalog for the operators
*   The user-defined catalog are supported to be added, removed and changed to another one in CS CR
*   Webhook will deny the request if only catalogsource name or catalogsource namespace is set in the CR, they should be set together
2. …
=> Enable user-defined catalog source and namespace in CS CR

bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml, config/rbac/role.yaml, internal/controller/bootstrap/init.go, internal/controller/commonservice_controller.go
1. Wait Postgres Cluster image update after OperandConfig is updated with latest configuration.
2. If the waiting for Postgres Cluster image update is timeout, it means that ODLM is not able to update the Postgres Cluster image, CS controller will directly update the Postgres Cluster image.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66478
1. Patch the CS operator CSV with image `docker-na-public.artifactory.swg-devops.com/hyc-cloud-private-scratch-docker-local/ibmcom/common-service-operator-amd64:dev`
2. Install OperandRequest with `common-service-postgresql`
3. Scale down ODLM pod
4. Change  `ibm-postgresql-16-operand-image` to `'icr.io/cpopen/edb/postgresql:16.4@sha256:d87a804d9bb7558d124bd83a83c26 …
=> enhance Postgres Cluster image update function

api/v3/commonservice_types.go, bundle/manifests/operator.ibm.com_commonservices.yaml, config/crd/bases/operator.ibm.com_commonservices.yaml, internal/controller/bootstrap/init.go, internal/controller/constant/odlm.go, internal/controller/webhooks/commonservice/validatingwebhook.go
1.  User-Configurable Catalog Source for Services:
*   Adopters can now specify their preferred catalog source (`spec.catalogName` and `spec.catalogNamespace`) directly in the `CommonService` CR.
*   These values, when provided, will be propagated to `status.configStatus` in CS CR and subsequently used into `OperandRegistry`
*   Operators and services deployed will then be sourced from this user-defined catalog
*   If they are not provided in the CS CR, ODLM will select appropriate catalog for the operators
*   The user-defined catalog are supported to be added, removed and changed to another one in CS CR
*   Webhook will deny the request if only catalogsource name or catalogsource namespace is set in the CR, they should be set together
2. …
=> [CD] Enable user-defined catalog source and namespace in CS CR (#2543)

cp3-networkpolicy/install_networkpolicy.sh, networkpolicy/install_networkpolicy.sh
This is the copy of #2526, to add clarify usage instructions for CP3.0 NetworkPolicies installation script.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66645
=> Clarify usage instructions for CP3.0 NetworkPolicies installation script

cp3pt0-deployment/setup_tenant.sh
If someone was using `oc apply` to manually update the CommonService CR without removing `.metadata.resourceVersion`, this leads to the issue that `.metadata.resourceVersion` was included in annotation `kubectl.kubernetes.io/last-applied-configuration` as well.
And next time when the script is trying to update the CommonService CR, script is following the best practice, to remove `.metadata.resourceVersion` from CommonService CR. However, due to the `.metadata.resourceVersion` in annotation `kubectl.kubernetes.io/last-applied-configuration`, such action is rejected.
The change is to always fetch the latest `.metadata.resourceVersion` from the existing CR in the cluster, and attach it to the CR in the local file before `oc apply`
**Which issue(s) …
=> update resource version in commonservice.yaml during setup

preload_data.sh
Add an new label to icp-mongodb statefulSet to indicate the time it is being migrated
For ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67128
=> add a time label to mongodb statefulset

internal/controller/constant/cloudNativePostgresql.go
Updated EDB operand images sha values in pg configmap for 1.25.2
Catalog image:  icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog@sha256:00eec4d39354aa03d0c85d594223a1280011bbdcb05619e317beedce844446e7
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67088
=> Update EDB operand image and License image reference in ConfigMap for Postgres operator version 1.25.2

cp3pt0-deployment/common/utils.sh
If we found 2 catalogsource in get_catalogsource function, there are two cases:
**case 1**: "catalog_source_1" and "catalog_source_2", we return both of them
**case 2**: "certified-operators" and "catalog_source_2", we only return "catalog_source_2"
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67140
=> Ignore certified-operators if found another catalogsource

velero/spectrum-fusion/application.yaml, velero/spectrum-fusion/recipes/dynamic-recipes/core/child-ums-recipe.yaml
Add backup and restore support for IBM Usage Metering Service resources on OLM in fusion by creating a child recipe and intergrating it with the parent CPFS recipe 
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67328
=> Create Child recipe for UMS supported on OLM to fusion BR process

internal/controller/constant/cloudNativePostgresql.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67858
=> Refresh the Postgres operand image digest for new 5.22.0+20250912.112649.2639 (EDB1.25.3)

helm/templates/rbac.yaml
**What this PR does / why we need it**: When testing the helm charts with the updated conditional labeling today, I saw a problem with the rbac.yaml. It is because of how variables are referenced from inside of a loop. This PR fixes this bug
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67932
=> Update rbac yaml template due to error when using variables inside of loop

cp3pt0-deployment/uninstall_tenant.sh
**What this PR does / why we need it**: CPD has asked for an uninstall script that does not delete the namespaces and only deletes CPFS resources. The difficulty with this is that we use the namespace deletion to determine which resources to delete (when a namespace is terminating, it highlights the remaining resources with finalizers to remove to facilitate namespace deletion). No deleting the namespace means we have to be more prescriptive about what we are deleting.
In this PR, I have created a fork that would skip deleting the namespaces of the tenant in favor of deleting specific resources associated with CPFS after operand requests and operators are uninstalled. This is a relatively short list of resources though so its possible this would need to expand. For example, right now this …
=> Make namespace deletion optional for uninstall tenant script

cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
BTS operator updates its namespace scoped RBAC with following additional permissions
```
E1006 14:32:34.797256 1 namespacescope_controller.go:668] Failed to create role cp1-ns/ibm-bts-operator-9269668ecad89c: roles.rbac.authorization.k8s.io "ibm-bts-operator-9269668ecad89c" is forbidden: user "system:serviceaccount:cs-operators:ibm-namespace-scope-operator" (groups=["system:serviceaccounts" "system:serviceaccounts:cs-operators" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:[""], Resources:["leases"], Verbs:["create" "delete" "get" "list" "patch" "update" "watch"]}
{APIGroups:["certmanager.k8s.io"], Resources:["certificaterequests"], Verbs:["create" "patch" "update"]} …
```
=> add required permission for BTS service
